# WARNING: Under review - generated by LLM.

"""Content-addressed KV checkpoint export and import.

A cache checkpoint is a durable manifest that binds the exact token prefix to
the model, tokenizer, layer geometry, and the checkpoint validity rule: the
workspace fingerprint and enabled tool catalog under which it was produced.
Importing a manifest fails closed on any mismatch; a failed or partial import
releases everything and falls back cold.

The manifest is content-addressed: its digest covers every binding field, so
the checkpoint file itself can be verified end to end.  Warm resume reuses
only the exact token prefix; everything after the first changed causal token
must be recomputed.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .generation import GenerationSession


class ManifestError(ValueError):
    """A checkpoint manifest is invalid, mismatched, or cannot be imported."""


def _json_copy(value: Any) -> Any:
    try:
        return json.loads(
            json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
        )
    except (TypeError, ValueError) as error:
        raise ManifestError("manifest payload must be JSON serializable") from error


def _canonical(value: Any) -> bytes:
    return json.dumps(
        value, ensure_ascii=True, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def _valid_hash(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


@dataclass(frozen=True)
class CacheManifest:
    """Durable, content-addressed description of one KV checkpoint.

    Fields
    ------
    model_hash:
        Content hash of the model weights/revision that produced the cache.
    tokenizer_hash:
        Content hash of the tokenizer/chat-template identity.
    layers:
        Number of layer caches; every layer must agree on the token offset.
    position:
        Exact token offset represented by the cache at every layer.
    prefix_hash:
        Content hash of the exact token IDs cached at this checkpoint.
    tool_catalog_hash:
        Hash of the enabled tool schema catalog at export time.
    workspace_fingerprint:
        Fingerprint of the workspace-visible state at export time (observed
        file digests plus a mutation counter).  A changed workspace makes the
        checkpoint stale even when the token prefix is identical.
    """

    model_hash: str
    tokenizer_hash: str
    layers: int
    position: int
    prefix_hash: str
    tool_catalog_hash: str = ""
    workspace_fingerprint: str = ""

    def __post_init__(self) -> None:
        for name, value in (
            ("model_hash", self.model_hash),
            ("tokenizer_hash", self.tokenizer_hash),
            ("prefix_hash", self.prefix_hash),
        ):
            if not _valid_hash(value):
                raise ManifestError(f"invalid {name}: must be a sha256 hex digest")
        if isinstance(self.layers, bool) or not isinstance(self.layers, int):
            raise ManifestError("invalid layer count")
        if self.layers <= 0:
            raise ManifestError("layer count must be positive")
        if isinstance(self.position, bool) or not isinstance(self.position, int):
            raise ManifestError("invalid cache position")
        if self.position < 0:
            raise ManifestError("cache position must be non-negative")
        if not isinstance(self.tool_catalog_hash, str):
            raise ManifestError("invalid tool catalog hash")
        if not isinstance(self.workspace_fingerprint, str):
            raise ManifestError("invalid workspace fingerprint")

    def digest(self) -> str:
        """Content address of this manifest over every binding field."""

        return hashlib.sha256(self._payload()).hexdigest()

    def _payload(self) -> bytes:
        return _canonical(
            {
                "model_hash": self.model_hash,
                "tokenizer_hash": self.tokenizer_hash,
                "layers": self.layers,
                "position": self.position,
                "prefix_hash": self.prefix_hash,
                "tool_catalog_hash": self.tool_catalog_hash,
                "workspace_fingerprint": self.workspace_fingerprint,
            }
        )

    def to_dict(self) -> dict[str, Any]:
        return _json_copy(
            {
                "digest": self.digest(),
                "model_hash": self.model_hash,
                "tokenizer_hash": self.tokenizer_hash,
                "layers": self.layers,
                "position": self.position,
                "prefix_hash": self.prefix_hash,
                "tool_catalog_hash": self.tool_catalog_hash,
                "workspace_fingerprint": self.workspace_fingerprint,
            }
        )

    @classmethod
    def from_dict(cls, value: Any) -> "CacheManifest":
        """Reconstruct and verify a manifest from its durable JSON form."""

        if not isinstance(value, dict):
            raise ManifestError("manifest must be a JSON object")
        required = {
            "digest",
            "model_hash",
            "tokenizer_hash",
            "layers",
            "position",
            "prefix_hash",
            "tool_catalog_hash",
            "workspace_fingerprint",
        }
        if set(value) != required:
            raise ManifestError("invalid manifest fields")
        manifest = cls(
            model_hash=value["model_hash"],
            tokenizer_hash=value["tokenizer_hash"],
            layers=value["layers"],
            position=value["position"],
            prefix_hash=value["prefix_hash"],
            tool_catalog_hash=value["tool_catalog_hash"],
            workspace_fingerprint=value["workspace_fingerprint"],
        )
        if manifest.digest() != value["digest"]:
            raise ManifestError("manifest digest does not match its payload")
        return manifest

    def require_current(
        self,
        *,
        model_hash: str,
        tokenizer_hash: str,
        layers: int,
        tool_catalog_hash: str,
        workspace_fingerprint: str,
    ) -> None:
        """Fail closed unless this checkpoint is current and identity-safe.

        KV equality never implies world equality.  The cache is reusable only
        when the exact model, tokenizer, layer geometry, tool catalog, and
        workspace fingerprint all still match; any difference forces a cold
        fallback or a reconciliation from a safe boundary.
        """

        if self.model_hash != model_hash:
            raise ManifestError("checkpoint model does not match the live model")
        if self.tokenizer_hash != tokenizer_hash:
            raise ManifestError("checkpoint tokenizer does not match the live one")
        if self.layers != layers:
            raise ManifestError("checkpoint layer geometry does not match")
        if self.tool_catalog_hash != tool_catalog_hash:
            raise ManifestError("tool catalog changed since this checkpoint")
        if self.workspace_fingerprint != workspace_fingerprint:
            raise ManifestError("workspace changed since this checkpoint")


def export_cache_manifest(
    session: "GenerationSession",
    token_ids: tuple[int, ...],
    *,
    tool_catalog_hash: str = "",
    workspace_fingerprint: str = "",
) -> CacheManifest:
    """Export a durable content-addressed manifest for a live cache state.

    ``token_ids`` is the exact token prefix represented by the session's
    layer caches (``session.cached_token_ids``).  The manifest binds it to the
    session's model/tokenizer identity and the current validity rule inputs.
    """

    if not isinstance(token_ids, tuple) or any(
        isinstance(token, bool) or not isinstance(token, int) or token < 0
        for token in token_ids
    ):
        raise ManifestError("token prefix must be a tuple of non-negative ints")
    if session.layer_count == 0:
        raise ManifestError("cannot export a manifest from a cold cache")
    prefix_hash = hashlib.sha256(
        json.dumps(list(token_ids), ensure_ascii=True, separators=(",", ":")).encode(
            "utf-8"
        )
    ).hexdigest()
    return CacheManifest(
        model_hash=session.model_identity,
        tokenizer_hash=session.tokenizer_identity,
        layers=session.layer_count,
        position=len(token_ids),
        prefix_hash=prefix_hash,
        tool_catalog_hash=tool_catalog_hash,
        workspace_fingerprint=workspace_fingerprint,
    )


def validate_resume(
    manifest: CacheManifest,
    session: "GenerationSession",
    token_ids: tuple[int, ...],
    *,
    tool_catalog_hash: str,
    workspace_fingerprint: str,
) -> None:
    """Fail closed before resuming from a manifest.

    This is the import gate: the live session must present the exact token
    prefix the manifest describes (same model, tokenizer, layer count,
    position, content hash, tool catalog, and workspace fingerprint).  Any
    mismatch rejects the resume; callers then go cold or reconcile from a
    safe boundary.
    """

    manifest.require_current(
        model_hash=session.model_identity,
        tokenizer_hash=session.tokenizer_identity,
        layers=session.layer_count,
        tool_catalog_hash=tool_catalog_hash,
        workspace_fingerprint=workspace_fingerprint,
    )
    if len(token_ids) != manifest.position:
        raise ManifestError(
            f"checkpoint position {manifest.position} does not match "
            f"the presented prefix {len(token_ids)}"
        )
    prefix_hash = hashlib.sha256(
        json.dumps(list(token_ids), ensure_ascii=True, separators=(",", ":")).encode(
            "utf-8"
        )
    ).hexdigest()
    if prefix_hash != manifest.prefix_hash:
        raise ManifestError("checkpoint token prefix does not match its hash")
