# WARNING: Under review - generated by LLM.

from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from time import perf_counter
from typing import Any

from .control import CancellationToken


Message = dict[str, str]
Generate = Callable[[list[Message]], str]


@dataclass(frozen=True)
class GenerationStats:
    """Token work performed by the most recent generation turn."""

    input_tokens: int = 0
    reused_tokens: int = 0
    rewound_tokens: int = 0
    prefilled_tokens: int = 0
    output_tokens: int = 0
    cold_start: bool = True
    latency_seconds: float | None = None


def initial_messages(task: str, system_prompt: str) -> list[Message]:
    """Week 4, Day 1: create the durable beginning of an agent conversation."""

    if not task.strip():
        raise ValueError("task must not be empty")
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": task},
    ]


class GenerationSession:
    """Generate responses while reusing compatible model KV-cache state."""

    last_stats: GenerationStats

    def __init__(
        self,
        model,
        tokenizer,
        cache_factory: Callable[[], Iterable[Any]],
        max_tokens: int,
        enable_thinking: bool = False,
        cancellation: CancellationToken | None = None,
    ):
        if max_tokens <= 0:
            raise ValueError("max_tokens must be positive")
        self._model = model
        self._tokenizer = tokenizer
        self._cache_factory = cache_factory
        self._max_tokens = max_tokens
        self._enable_thinking = enable_thinking
        self._cancellation = cancellation
        self._caches: list[Any] = []
        self._cached_token_ids: list[int] = []
        self._closed = False
        self.last_stats = GenerationStats()

    @property
    def cached_token_ids(self) -> tuple[int, ...]:
        """Return the exact token prefix currently represented by the caches."""

        return tuple(self._cached_token_ids)

    def encode_messages(self, messages: list[Message]) -> tuple[int, ...]:
        """Render semantic messages and return the model's prompt token IDs."""

        prompt = self._tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=self._enable_thinking,
        )
        return tuple(
            int(token)
            for token in self._tokenizer.encode(prompt, add_special_tokens=False)
        )

    @staticmethod
    def _release(caches: Sequence[Any]) -> None:
        for cache in caches:
            try:
                release = getattr(cache, "release", None)
                if release is not None:
                    release()
            except BaseException:
                # Continue releasing the remaining layers. The discarded cache
                # objects are never reused after cleanup starts.
                pass

    @staticmethod
    def _cache_offset(caches: Sequence[Any]) -> int:
        if not caches:
            raise ValueError("cache_factory must create at least one layer cache")
        offsets: list[int] = []
        for cache in caches:
            offset = getattr(cache, "offset", None)
            if isinstance(offset, bool) or not isinstance(offset, int) or offset < 0:
                raise ValueError(
                    "every layer cache must expose a non-negative integer offset"
                )
            offsets.append(offset)
        if any(offset != offsets[0] for offset in offsets[1:]):
            raise ValueError("all layer cache offsets must agree")
        return offsets[0]

    def _drop_caches(self) -> None:
        caches, self._caches = self._caches, []
        self._cached_token_ids = []
        self._release(caches)

    def _create_caches(self) -> None:
        caches: list[Any] = []
        try:
            created = self._cache_factory()
            iterator = iter(created)
            while True:
                try:
                    cache = next(iterator)
                except StopIteration:
                    break
                caches.append(cache)
            if self._cache_offset(caches) != 0:
                raise ValueError("new layer caches must start at offset zero")
        except BaseException:
            self._release(caches)
            raise
        self._caches = caches
        self._cached_token_ids = []

    def _reset_caches(self) -> None:
        self._drop_caches()
        self._create_caches()

    def _validated_offset(self, expected: int) -> int:
        offset = self._cache_offset(self._caches)
        if offset != expected:
            raise ValueError(
                f"layer cache offset {offset} does not match token prefix {expected}"
            )
        return offset

    @staticmethod
    def _common_prefix(left: Sequence[int], right: Sequence[int]) -> int:
        length = 0
        for left_token, right_token in zip(left, right):
            if left_token != right_token:
                break
            length += 1
        return length

    def _rewind(self, count: int, expected_offset: int) -> None:
        if count == 0:
            return
        # Validate the complete layer set before mutating any cache. A failure
        # partway through is handled by discarding the whole set.
        self._validated_offset(expected_offset)
        for cache in self._caches:
            rewind = getattr(cache, "rewind", None)
            if rewind is None:
                raise ValueError("every layer cache must support rewind")
            rewind(count)
        self._validated_offset(expected_offset - count)

    def __call__(self, messages: list[Message]) -> str:
        """Render and decode one response, reusing the safe token prefix."""

        if self._closed:
            raise RuntimeError("generation session is closed")
        if self._cancellation is not None:
            self._cancellation.raise_if_cancelled("model_request")

        import mlx.core as mx

        started = perf_counter()
        desired_tokens = self.encode_messages(messages)
        if not desired_tokens:
            raise ValueError("rendered prompt must contain at least one token")

        cold_start = not self._caches
        rewound_tokens = 0
        if cold_start:
            self._create_caches()
            common_prefix = 0
        else:
            try:
                cached_length = self._validated_offset(len(self._cached_token_ids))
                common_prefix = self._common_prefix(
                    self._cached_token_ids, desired_tokens
                )
                rewind_count = cached_length - common_prefix
                self._rewind(rewind_count, cached_length)
                rewound_tokens = rewind_count
            except Exception:
                # Offset disagreement, unsupported rewind, or a partially
                # failed rewind makes every layer unsafe to reuse.
                self._reset_caches()
                cold_start = True
                common_prefix = 0
                rewound_tokens = 0
            except BaseException:
                self._drop_caches()
                raise

        # A model call needs at least one token to produce next-token logits.
        # If the desired prompt is already represented, replay its final token.
        if common_prefix == len(desired_tokens):
            try:
                self._rewind(1, common_prefix)
                common_prefix -= 1
                rewound_tokens += 1
            except Exception:
                self._reset_caches()
                cold_start = True
                common_prefix = 0
                rewound_tokens = 0
            except BaseException:
                self._drop_caches()
                raise

        reused_tokens = common_prefix
        prompt_suffix = list(desired_tokens[common_prefix:])
        represented_tokens = list(desired_tokens[:common_prefix])
        output: list[int] = []
        input_ids = prompt_suffix
        offset = common_prefix

        try:
            for _ in range(self._max_tokens):
                if self._cancellation is not None:
                    self._cancellation.raise_if_cancelled("model_decode")
                tokens = mx.array(input_ids)
                logits = self._model(tokens[None], offset, self._caches)[:, -1, :]
                offset += len(input_ids)
                self._validated_offset(offset)
                represented_tokens.extend(input_ids)

                token = int(mx.argmax(logits, axis=-1).item())
                if token == self._tokenizer.eos_token_id:
                    break
                output.append(token)
                input_ids = [token]
            if self._cancellation is not None:
                self._cancellation.raise_if_cancelled("model_decode")
        except BaseException:
            self._drop_caches()
            raise

        self._cached_token_ids = represented_tokens
        self.last_stats = GenerationStats(
            input_tokens=len(desired_tokens),
            reused_tokens=reused_tokens,
            rewound_tokens=rewound_tokens,
            prefilled_tokens=len(prompt_suffix),
            output_tokens=len(output),
            cold_start=cold_start,
            latency_seconds=perf_counter() - started,
        )
        return self._tokenizer.decode(output)

    def close(self) -> None:
        """Release every layer cache. Closing more than once is safe."""

        if self._closed:
            return
        self._closed = True
        self._drop_caches()


def generate_response(
    model,
    tokenizer,
    messages: list[Message],
    cache_factory: Callable[[], Sequence[Any]],
    max_tokens: int,
    enable_thinking: bool = False,
) -> str:
    """Week 4, Day 1: decode one action with the course model and a fresh cache."""

    import mlx.core as mx

    if max_tokens <= 0:
        raise ValueError("max_tokens must be positive")
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking,
    )
    tokens = mx.array(tokenizer.encode(prompt, add_special_tokens=False))
    caches = list(cache_factory())
    output: list[int] = []
    offset = 0
    try:
        for _ in range(max_tokens):
            logits = model(tokens[None], offset, caches)[:, -1, :]
            token = int(mx.argmax(logits, axis=-1).item())
            if token == tokenizer.eos_token_id:
                break
            output.append(token)
            offset += tokens.size
            tokens = mx.array([token])
        return tokenizer.decode(output)
    finally:
        for cache in caches:
            release = getattr(cache, "release", None)
            if release is not None:
                release()
