# WARNING: Under review - generated by LLM.

import json
from collections.abc import Callable
from dataclasses import asdict, dataclass, is_dataclass

from .context import (
    ContextLimitError,
    ContextManager,
    ContextWindow,
    append_tool_result,
    compact_messages,
)
from .generation import Generate, Message, initial_messages
from .protocol import (
    AgentAction,
    AgentError,
    FinalAction,
    build_system_prompt,
    parse_action,
)
from .session import SessionLog
from .workspace import Workspace


@dataclass(frozen=True)
class AgentLimits:
    """Week 4, Day 6: budgets that guarantee the loop eventually stops."""

    max_steps: int = 8
    max_context_chars: int = 48_000
    max_invalid_actions: int = 3
    max_identical_actions: int = 2

    def __post_init__(self) -> None:
        """Week 4, Day 6: reject budgets that could disable a stop condition."""

        if (
            min(
                self.max_steps,
                self.max_context_chars,
                self.max_invalid_actions,
                self.max_identical_actions,
            )
            <= 0
        ):
            raise ValueError("agent limits must be positive")


@dataclass(frozen=True)
class AgentEvent:
    """Week 4, Day 7: one auditable model/action/tool interaction."""

    step: int
    response: str
    action: AgentAction | None
    result: str | None


@dataclass(frozen=True)
class AgentRun:
    """One bounded run; ``completed`` means the model returned a valid final."""

    completed: bool
    reason: str
    final: str | None
    events: tuple[AgentEvent, ...]
    modified_files: tuple[str, ...]
    task_success: bool | None = None
    command_side_effects_untracked: bool = False
    uncertain_modified_files: tuple[str, ...] = ()
    command_cleanup_incomplete: bool = False
    session_id: str | None = None


def run_agent(
    task: str | None,
    generate: Generate,
    workspace: Workspace,
    limits: AgentLimits | None = None,
    on_event: Callable[[AgentEvent], None] | None = None,
    *,
    session: SessionLog | None = None,
    context_manager: ContextManager | None = None,
    summarize: Callable[[list[Message]], str] | None = None,
) -> AgentRun:
    """Run a bounded loop, optionally recording its canonical durable events."""

    limits = limits or AgentLimits()
    if context_manager is not None and session is None:
        raise ValueError("token context management requires a session")
    system_prompt = build_system_prompt(workspace)
    if session is None:
        if task is None:
            raise ValueError("task is required without a session")
        messages = initial_messages(task, system_prompt)
    else:
        if session.workspace != workspace.policy.root:
            raise ValueError("session belongs to a different workspace")
        session.recover_incomplete_turns()
        prior_user_messages = any(
            event.type == "user_message" for event in session.events
        )
        finished = next(
            (
                event
                for event in reversed(session.events)
                if event.type == "run_finished"
            ),
            None,
        )
        if task is None and finished is not None and finished.data.get("completed"):
            raise ValueError("completed session requires a follow-up message")
        if task is not None:
            if not task.strip():
                raise ValueError("task must not be empty")
            session.append(
                "user_message",
                content=task,
                kind="follow_up" if prior_user_messages else "task",
            )
        elif not prior_user_messages:
            raise ValueError("session has no task to resume")
        session.append("run_started")
        messages = session.messages(system_prompt)
        if context_manager is None:
            messages = compact_messages(messages, limits.max_context_chars)
    events: list[AgentEvent] = []
    invalid_actions = 0
    previous_signature: str | None = None
    identical_actions = 0
    context_window: ContextWindow | None = None

    def finish(completed: bool, reason: str, final: str | None = None) -> AgentRun:
        """Week 4, Day 7: freeze the trace and modified paths into a result."""

        if session is not None:
            session.append(
                "run_finished", completed=completed, reason=reason, final=final
            )

        modified = tuple(
            sorted(
                str(path.relative_to(workspace.policy.root))
                for path in workspace.modified_files
            )
        )
        uncertain = tuple(
            sorted(
                str(path.relative_to(workspace.policy.root))
                for path in workspace.uncertain_modified_files
            )
        )
        return AgentRun(
            completed,
            reason,
            final,
            tuple(events),
            modified,
            task_success=None,
            command_side_effects_untracked=(workspace.command_side_effects_untracked),
            uncertain_modified_files=uncertain,
            command_cleanup_incomplete=workspace.command_cleanup_incomplete,
            session_id=session.session_id if session is not None else None,
        )

    def rebuild_messages() -> list[dict[str, str]]:
        if session is None:
            return compact_messages(messages, limits.max_context_chars)
        return compact_messages(
            session.messages(system_prompt), limits.max_context_chars
        )

    def prepare_messages() -> bool:
        """Prepare one immutable model request, stopping cleanly on overflow."""

        nonlocal context_window, messages
        if context_manager is None:
            context_window = None
            return True
        assert session is not None
        try:
            context_window = context_manager.prepare(session, system_prompt, summarize)
        except ContextLimitError:
            return False
        messages = [dict(message) for message in context_window.messages]
        return True

    def record_assistant(response: str) -> None:
        if session is None:
            return
        stats = getattr(generate, "last_stats", None)
        generation = asdict(stats) if is_dataclass(stats) else None
        context = None
        if context_window is not None:
            max_tokens = context_manager.policy.max_tokens
            context = {
                "input_tokens": len(context_window.token_ids),
                "utilization": len(context_window.token_ids) / max_tokens,
                "visible_tool_result_bytes": (context_window.visible_tool_result_bytes),
                "followed_compaction": context_window.followed_compaction,
                "compaction_event_id": context_window.compaction_event_id,
            }
        session.append(
            "assistant_message",
            content=response,
            generation=generation,
            context=context,
        )

    initial_chars = sum(len(message["content"]) for message in messages)
    if context_manager is None and initial_chars > limits.max_context_chars:
        return finish(False, "context_limit")

    for step in range(1, limits.max_steps + 1):
        if not prepare_messages():
            return finish(False, "context_limit")
        if (
            context_manager is None
            and sum(len(message["content"]) for message in messages)
            > limits.max_context_chars
        ):
            return finish(False, "context_limit")
        response = generate(messages)
        record_assistant(response)
        try:
            action = parse_action(response, workspace.available_tools)
        except AgentError as error:
            invalid_actions += 1
            previous_signature = None
            identical_actions = 0
            result = f"error: {error}"
            event = AgentEvent(step, response, None, result)
            events.append(event)
            if on_event is not None:
                on_event(event)
            if invalid_actions >= limits.max_invalid_actions:
                if session is not None:
                    session.append(
                        "tool_result",
                        tool_call_id=None,
                        tool=None,
                        is_error=True,
                        content=result,
                    )
                return finish(False, "invalid_action_limit")
            if session is not None:
                session.append(
                    "tool_result",
                    tool_call_id=None,
                    tool=None,
                    is_error=True,
                    content=result,
                )
            else:
                messages = append_tool_result(messages, response, result)
            if context_manager is None:
                messages = rebuild_messages()
            continue

        if isinstance(action, FinalAction):
            event = AgentEvent(step, response, action, None)
            events.append(event)
            if on_event is not None:
                on_event(event)
            return finish(True, "completed", action.final)

        signature = json.dumps(
            {"tool": action.tool, **action.arguments}, sort_keys=True
        )
        if signature == previous_signature:
            identical_actions += 1
        else:
            previous_signature = signature
            identical_actions = 1
        if identical_actions > limits.max_identical_actions:
            result = "error: identical action loop detected"
            event = AgentEvent(step, response, action, result)
            events.append(event)
            if on_event is not None:
                on_event(event)
            if session is not None:
                session.append(
                    "tool_result",
                    tool_call_id=None,
                    tool=action.tool,
                    is_error=True,
                    content=result,
                )
            return finish(False, "repeated_action_limit")

        tool_call = None
        if session is not None:
            tool_call = session.append(
                "tool_call", tool=action.tool, arguments=action.arguments
            )
        result = workspace.execute(action)
        if session is not None:
            session.append(
                "tool_result",
                tool_call_id=tool_call.id,
                tool=action.tool,
                arguments=action.arguments,
                is_error=result.startswith("error:"),
                content=result,
            )
        event = AgentEvent(step, response, action, result)
        events.append(event)
        if on_event is not None:
            on_event(event)
        if session is None:
            messages = append_tool_result(messages, response, result)
        if context_manager is None:
            messages = rebuild_messages()

    return finish(False, "step_limit")
