# WARNING: Under review - generated by LLM.

"""Refcounted immutable prefix pages and copy-on-write forks.

Day 6 of Week 4: derived KV state is not just a token buffer.  A
``PrefixRegistry`` owns immutable, content-addressed prefix pages; every
session or subagent holds a fork whose page table references shared immutable
pages plus a private copy-on-write tail.  Pages are never mutated after
publish, forks release their references deterministically, and a memory budget
evicts only unreferenced pages.

The registry is model-scoped: publishing or acquiring under a different
model/tokenizer identity fails closed, because a cache hit requires exact
model, tokenizer, and token identity.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any


class PrefixError(RuntimeError):
    """A prefix registry operation is invalid, unsafe, or over budget."""


def _canonical_tokens(token_ids: tuple[int, ...]) -> bytes:
    return json.dumps(list(token_ids), ensure_ascii=True, separators=(",", ":")).encode(
        "utf-8"
    )


def _valid_identity(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


@dataclass(frozen=True)
class PrefixStats:
    """Deterministic page accounting for one registry snapshot."""

    live_pages: int
    shared_pages: int
    private_pages: int
    live_refs: int
    budget_pages: int

    def to_dict(self) -> dict[str, int]:
        return {
            "live_pages": self.live_pages,
            "shared_pages": self.shared_pages,
            "private_pages": self.private_pages,
            "live_refs": self.live_refs,
            "budget_pages": self.budget_pages,
        }


@dataclass(frozen=True)
class _Page:
    """One immutable block of tokens with a live reference count."""

    page_id: int
    token_block: tuple[int, ...]
    refs: int

    @property
    def digest(self) -> str:
        return hashlib.sha256(_canonical_tokens(self.token_block)).hexdigest()


class PrefixRegistry:
    """Content-addressed registry of refcounted immutable prefix pages.

    Parameters
    ----------
    model_hash:
        Model identity; all pages are scoped to it.
    tokenizer_hash:
        Tokenizer identity; all pages are scoped to it.
    block_size:
        Tokens per immutable page.  Prefix reuse is block-aligned.
    page_budget:
        Maximum number of live pages.  Publishing past the budget fails
        closed after evicting unreferenced pages.
    """

    def __init__(
        self,
        *,
        model_hash: str,
        tokenizer_hash: str,
        block_size: int = 4,
        page_budget: int = 64,
    ):
        if not _valid_identity(model_hash) or not _valid_identity(tokenizer_hash):
            raise PrefixError("registry identity must be a sha256 hex digest")
        if isinstance(block_size, bool) or not isinstance(block_size, int):
            raise PrefixError("block size must be an integer")
        if block_size <= 0:
            raise PrefixError("block size must be positive")
        if isinstance(page_budget, bool) or not isinstance(page_budget, int):
            raise PrefixError("page budget must be an integer")
        if page_budget <= 0:
            raise PrefixError("page budget must be positive")
        self.model_hash = model_hash
        self.tokenizer_hash = tokenizer_hash
        self.block_size = block_size
        self.page_budget = page_budget
        self._pages: dict[int, _Page] = {}
        self._by_digest: dict[str, int] = {}
        self._next_page_id = 0
        self._live_refs = 0

    def _blocks(self, token_ids: tuple[int, ...]) -> list[tuple[int, ...]]:
        if any(
            isinstance(token, bool) or not isinstance(token, int) or token < 0
            for token in token_ids
        ):
            raise PrefixError("token IDs must be non-negative integers")
        return [
            tuple(token_ids[index : index + self.block_size])
            for index in range(0, len(token_ids), self.block_size)
        ]

    def publish(self, token_ids: tuple[int, ...]) -> tuple[int, ...]:
        """Publish validated token blocks as immutable pages.

        Idempotent: publishing a block already present returns its existing
        page ID and increments no reference.  Returns the page IDs in token
        order.
        """

        page_ids: list[int] = []
        for block in self._blocks(token_ids):
            digest = hashlib.sha256(_canonical_tokens(block)).hexdigest()
            existing = self._by_digest.get(digest)
            if existing is not None:
                page_ids.append(existing)
                continue
            if len(self._pages) >= self.page_budget:
                self._evict_unreferenced()
            if len(self._pages) >= self.page_budget:
                raise PrefixError("prefix registry page budget exceeded")
            page_id = self._next_page_id
            self._next_page_id += 1
            self._pages[page_id] = _Page(page_id, block, refs=0)
            self._by_digest[digest] = page_id
            page_ids.append(page_id)
        return tuple(page_ids)

    def _evict_unreferenced(self) -> None:
        for page_id in list(self._pages):
            if self._pages[page_id].refs == 0:
                digest = self._pages[page_id].digest
                del self._pages[page_id]
                del self._by_digest[digest]

    def acquire(self, token_ids: tuple[int, ...]) -> "ForkedPrefix":
        """Fork the longest block-aligned published prefix of ``token_ids``.

        Returns a fork whose page table references the shared immutable pages
        (incrementing their refcounts).  The fork's private tail is empty; the
        caller appends divergent blocks with ``append``.
        """

        blocks = self._blocks(token_ids)
        page_ids: list[int] = []
        for block in blocks:
            digest = hashlib.sha256(_canonical_tokens(block)).hexdigest()
            page_id = self._by_digest.get(digest)
            if page_id is None:
                break
            page_ids.append(page_id)
        for page_id in page_ids:
            self._pages[page_id] = _Page(
                page_id,
                self._pages[page_id].token_block,
                refs=self._pages[page_id].refs + 1,
            )
            self._live_refs += 1
        prefix_tokens = tuple(
            token for page_id in page_ids for token in self._pages[page_id].token_block
        )
        return ForkedPrefix(
            self,
            shared_page_ids=tuple(page_ids),
            private_page_ids=(),
            token_ids=prefix_tokens,
        )

    def release(self, page_ids: tuple[int, ...]) -> None:
        """Release references to shared pages; never double-frees or leaks."""

        for page_id in page_ids:
            page = self._pages.get(page_id)
            if page is None:
                raise PrefixError(f"page {page_id} is not live")
            if page.refs <= 0:
                raise PrefixError(f"page {page_id} reference count is corrupted")
            self._pages[page_id] = _Page(page_id, page.token_block, refs=page.refs - 1)
            self._live_refs -= 1

    def stats(self) -> PrefixStats:
        """Return deterministic page/ref accounting for this registry."""

        shared = sum(1 for page in self._pages.values() if page.refs > 0)
        return PrefixStats(
            live_pages=len(self._pages),
            shared_pages=shared,
            private_pages=len(self._pages) - shared,
            live_refs=self._live_refs,
            budget_pages=self.page_budget,
        )

    def shared_page_stats(self, forks: list["ForkedPrefix"]) -> dict[str, int]:
        """Report how many pages the given forks share with the registry.

        Used by Day 6 to teach radix-cache economics: total shared page
        references across the forks, plus their combined private tail.
        """

        shared = sum(len(fork.shared_page_ids) for fork in forks)
        private = sum(len(fork.private_page_ids) for fork in forks)
        return {"shared_refs": shared, "private_pages": private}


class ForkedPrefix:
    """A page table over shared immutable pages plus a private COW tail.

    A fork references immutable registry pages (never mutated) and owns a
    private tail of pages written only by this fork.  Closing the fork
    releases every shared reference exactly once.
    """

    def __init__(
        self,
        registry: PrefixRegistry,
        *,
        shared_page_ids: tuple[int, ...],
        private_page_ids: tuple[int, ...],
        token_ids: tuple[int, ...],
    ):
        self._registry = registry
        self.shared_page_ids = shared_page_ids
        self.private_page_ids = private_page_ids
        self.token_ids = token_ids
        self._closed = False

    def fork(self, boundary: int) -> "ForkedPrefix":
        """Copy-on-write fork at a stable token boundary.

        The child shares the same immutable prefix pages; its private tail is
        empty.  Closing the child can never affect the parent's cache because
        pages are immutable and refcounted.
        """

        if self._closed:
            raise PrefixError("cannot fork a closed prefix")
        if boundary < 0 or boundary > len(self.token_ids):
            raise PrefixError("fork boundary is outside the token prefix")
        if boundary % self._registry.block_size != 0:
            raise PrefixError("fork boundary must be block-aligned")
        blocks = self._registry._blocks(self.token_ids[:boundary])
        shared_ids = []
        for block in blocks:
            digest = hashlib.sha256(_canonical_tokens(block)).hexdigest()
            page_id = self._registry._by_digest[digest]
            shared_ids.append(page_id)
        for page_id in shared_ids:
            page = self._registry._pages[page_id]
            self._registry._pages[page_id] = _Page(
                page_id, page.token_block, refs=page.refs + 1
            )
            self._registry._live_refs += 1
        return ForkedPrefix(
            self._registry,
            shared_page_ids=tuple(shared_ids),
            private_page_ids=(),
            token_ids=self.token_ids[:boundary],
        )

    def append(self, token_ids: tuple[int, ...]) -> "ForkedPrefix":
        """Allocate a private divergent tail and return a new fork handle.

        Every fork handle owns its own references to the shared prefix pages,
        so each handle created by ``acquire``, ``fork``, or ``append`` must be
        closed exactly once.  Private tail pages hold no registry reference
        and become evictable when the fork is closed.
        """

        if self._closed:
            raise PrefixError("cannot append to a closed prefix")
        page_ids = self._registry.publish(token_ids)
        for page_id in self.shared_page_ids:
            page = self._registry._pages[page_id]
            self._registry._pages[page_id] = _Page(
                page_id, page.token_block, refs=page.refs + 1
            )
            self._registry._live_refs += 1
        return ForkedPrefix(
            self._registry,
            shared_page_ids=self.shared_page_ids,
            private_page_ids=self.private_page_ids + page_ids,
            token_ids=self.token_ids + token_ids,
        )

    def close(self) -> None:
        """Release every shared reference; safe against double close."""

        if self._closed:
            return
        self._registry.release(self.shared_page_ids)
        self._closed = True
