# WARNING: Under review - generated by LLM.

"""Immutable effect receipts and their durable store.

An ``EffectReceipt`` is the canonical evidence record of one executed tool
effect: the validated action, its normalized inputs, the exit/result state,
the changed artifacts, and the world/approval epoch under which it ran.  A
receipt is immutable and content-addressed: its ID is the SHA-256 of its
canonical payload, so a later compaction, replay, or audit can verify that the
bytes it points at have not been altered.

The receipt store is append-only and durable.  Compaction never deletes
canonical evidence; it only replaces the model-visible rendering.  Re-expansion
fails closed on digest or epoch mismatch, and unmatched call/result pairs are
never split.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .epoch import ApprovalEpoch, WorldStamp


def _json_copy(value: Any) -> Any:
    """Validate and detach a JSON-compatible receipt payload."""

    try:
        return json.loads(
            json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
        )
    except (TypeError, ValueError) as error:
        raise ValueError("receipt payload must be JSON serializable") from error


def _canonical_payload(value: Any) -> bytes:
    """Serialize a receipt payload into stable canonical bytes."""

    return json.dumps(
        value, ensure_ascii=True, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


@dataclass(frozen=True)
class EffectReceipt:
    """Immutable evidence of one executed tool effect."""

    tool_call_id: str
    tool: str
    arguments: dict[str, Any]
    exit_state: str  # "ok" | "error" | "uncertain"
    result: str
    changed_artifacts: tuple[str, ...]
    world_stamp: WorldStamp
    approval_epoch: ApprovalEpoch
    # Optional bounded head/tail rendering used by Day 7 compaction.
    head: str = ""
    tail: str = ""

    def __post_init__(self) -> None:
        if not isinstance(self.tool_call_id, str) or not self.tool_call_id:
            raise ValueError("tool call ID must be a non-empty string")
        if not isinstance(self.tool, str) or not self.tool:
            raise ValueError("tool name must be a non-empty string")
        if self.exit_state not in {"ok", "error", "uncertain"}:
            raise ValueError("exit state must be ok, error, or uncertain")
        if not isinstance(self.result, str):
            raise ValueError("result must be a string")
        if not isinstance(self.changed_artifacts, tuple) or not all(
            isinstance(path, str) and path for path in self.changed_artifacts
        ):
            raise ValueError("changed artifacts must be a tuple of paths")
        object.__setattr__(self, "arguments", _json_copy(self.arguments))
        object.__setattr__(
            self, "changed_artifacts", tuple(sorted(self.changed_artifacts))
        )
        if not isinstance(self.head, str) or not isinstance(self.tail, str):
            raise ValueError("head and tail must be strings")

    @property
    def receipt_id(self) -> str:
        """Content address: SHA-256 of the canonical payload."""

        return hashlib.sha256(self._payload()).hexdigest()

    def _payload(self) -> bytes:
        return _canonical_payload(
            {
                "tool_call_id": self.tool_call_id,
                "tool": self.tool,
                "arguments": self.arguments,
                "exit_state": self.exit_state,
                "result": self.result,
                "changed_artifacts": self.changed_artifacts,
                "world_stamp": self.world_stamp.to_dict(),
                "approval_epoch": self.approval_epoch.to_dict(),
                "head": self.head,
                "tail": self.tail,
            }
        )

    def to_dict(self) -> dict[str, Any]:
        return _json_copy(
            {
                "receipt_id": self.receipt_id,
                "tool_call_id": self.tool_call_id,
                "tool": self.tool,
                "arguments": self.arguments,
                "exit_state": self.exit_state,
                "result": self.result,
                "changed_artifacts": self.changed_artifacts,
                "world_stamp": self.world_stamp.to_dict(),
                "approval_epoch": self.approval_epoch.to_dict(),
                "head": self.head,
                "tail": self.tail,
            }
        )

    @classmethod
    def from_dict(cls, value: Any) -> "EffectReceipt":
        """Reconstruct and verify a receipt from its durable JSON form."""

        if not isinstance(value, dict):
            raise ValueError("receipt must be a JSON object")
        required = {
            "receipt_id",
            "tool_call_id",
            "tool",
            "arguments",
            "exit_state",
            "result",
            "changed_artifacts",
            "world_stamp",
            "approval_epoch",
            "head",
            "tail",
        }
        if set(value) != required:
            raise ValueError("invalid receipt fields")
        world_stamp = WorldStamp.from_dict(value["world_stamp"])
        approval_epoch = ApprovalEpoch.from_dict(value["approval_epoch"])
        receipt = cls(
            tool_call_id=value["tool_call_id"],
            tool=value["tool"],
            arguments=value["arguments"],
            exit_state=value["exit_state"],
            result=value["result"],
            changed_artifacts=tuple(value["changed_artifacts"]),
            world_stamp=world_stamp,
            approval_epoch=approval_epoch,
            head=value["head"],
            tail=value["tail"],
        )
        if receipt.receipt_id != value["receipt_id"]:
            raise ValueError("receipt digest does not match its payload")
        return receipt

    def verify_epoch(self, world: WorldStamp, approval: ApprovalEpoch) -> None:
        """Fail closed unless this receipt's epochs are still current."""

        self.world_stamp.require_current(world)
        self.approval_epoch.require_current(approval)


class ReceiptStore:
    """Append-only durable store of immutable effect receipts.

    Each receipt is persisted as one canonical JSON line with an fsync at the
    store level.  The store never mutates or deletes a published receipt;
    ``put`` is idempotent by content address, and ``get`` verifies the digest.
    """

    def __init__(self, path: Path | None = None):
        self._path = path
        self._receipts: dict[str, EffectReceipt] = {}
        self._order: list[str] = []
        if path is not None:
            self._load(path)

    def _load(self, path: Path) -> None:
        path = path.resolve()
        if path.exists():
            with path.open("r", encoding="utf-8") as handle:
                for line in handle:
                    line = line.strip()
                    if not line:
                        continue
                    receipt = EffectReceipt.from_dict(json.loads(line))
                    if receipt.receipt_id not in self._receipts:
                        self._receipts[receipt.receipt_id] = receipt
                        self._order.append(receipt.receipt_id)

    def put(self, receipt: EffectReceipt) -> str:
        """Durably publish one receipt; idempotent by content address."""

        receipt_id = receipt.receipt_id
        if receipt_id in self._receipts:
            return receipt_id
        if self._path is not None:
            self._path = self._path.resolve()
            self._path.parent.mkdir(parents=True, exist_ok=True)
            line = (
                json.dumps(
                    receipt.to_dict(),
                    ensure_ascii=True,
                    sort_keys=True,
                    separators=(",", ":"),
                )
                + "\n"
            )
            with self._path.open("a", encoding="utf-8") as handle:
                handle.write(line)
                handle.flush()
                os.fsync(handle.fileno())
        self._receipts[receipt_id] = receipt
        self._order.append(receipt_id)
        return receipt_id

    def get(self, receipt_id: str) -> EffectReceipt | None:
        """Return the verified receipt or None when absent."""

        return self._receipts.get(receipt_id)

    def require(self, receipt_id: str) -> EffectReceipt:
        receipt = self.get(receipt_id)
        if receipt is None:
            raise KeyError(f"receipt not found: {receipt_id}")
        return receipt

    def __iter__(self):
        for receipt_id in self._order:
            yield self._receipts[receipt_id]

    def __len__(self) -> int:
        return len(self._order)

    def close(self) -> None:
        """Drop the in-memory index; the durable file is already fsynced."""

        self._receipts.clear()
        self._order = []
