# WARNING: Under review - generated by LLM.

import hashlib
import json
import os
import stat
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from .protocol import AgentError
from .session import SessionEvent, SessionLog


_MAX_BEFORE_IMAGE_BYTES = 64 * 1024
_MAX_CAUSE_CHARS = 256
_MAX_CHECKPOINT_NAME_CHARS = 128
_HEX_DIGEST_LENGTH = 64
_PROTECTED_NAMES = frozenset(
    {
        ".env",
        ".aws",
        ".azure",
        ".docker",
        ".git",
        ".gnupg",
        ".kube",
        ".netrc",
        ".npmrc",
        ".pypirc",
        ".ssh",
        ".tiny-llm",
        "id_ed25519",
        "id_rsa",
    }
)


@dataclass(frozen=True)
class MutationIntent:
    """A durable write-ahead description of one intended text-file replace."""

    id: str
    path: str
    parent_dev: int
    parent_ino: int
    before_sha256: str | None
    before_content: str | None
    before_mode: int | None
    after_sha256: str
    after_mode: int
    cause: Literal["tool", "undo"]


@dataclass(frozen=True)
class PlannedRestore:
    """One conflict-checked file operation in an undo plan."""

    intent_id: str
    path: str
    expected_parent_dev: int
    expected_parent_ino: int
    expected_sha256: str
    expected_mode: int
    restore_content: str | None
    restore_mode: int | None
    remove: bool
    covered_intent_ids: tuple[str, ...]


@dataclass(frozen=True)
class Checkpoint:
    """A named, branch-local boundary in the durable event stream."""

    id: str
    name: str
    event_id: str
    branch_id: str


@dataclass(frozen=True)
class RecoveryResult:
    """The observed outcome of resolving one interrupted mutation intent."""

    intent_id: str
    path: str
    status: Literal["committed", "not_applied", "conflict"]


@dataclass(frozen=True)
class UndoPlan:
    """A reviewable, side-effect-free plan for restoring one checkpoint."""

    checkpoint: Checkpoint
    changes: tuple[PlannedRestore, ...]
    warnings: tuple[str, ...]


@dataclass(frozen=True)
class UndoResult:
    """An honest account of the file operations an undo did or did not apply."""

    restored: tuple[str, ...]
    removed: tuple[str, ...]
    conflicts: tuple[str, ...]
    warnings: tuple[str, ...]
    retained_recovery_files: tuple[str, ...] = ()


@dataclass(frozen=True)
class _LoggedIntent:
    intent: MutationIntent
    branch_id: str
    event_index: int


class MutationJournal:
    """Durably journal bounded text mutations and undo them without clobbering."""

    def __init__(self, session: SessionLog, workspace_root: Path):
        root = Path(workspace_root)
        if root.is_symlink():
            raise ValueError("workspace root must not be a symlink")
        root = root.resolve()
        if not root.is_dir():
            raise ValueError("workspace root must be an existing directory")
        if root.parent == root or root == Path.home().resolve():
            raise ValueError("workspace root is too broad")
        if any(
            part.lower() in _PROTECTED_NAMES
            or part.lower().startswith((".tiny-llm-agent-", ".tiny-llm-undo-"))
            for part in root.parts
        ):
            raise ValueError("workspace root is protected")
        if Path(session.workspace).resolve() != root:
            raise ValueError("mutation journal must use the session workspace")
        flags = (
            os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
        )
        descriptor = None
        try:
            descriptor = os.open(root, flags)
            opened = os.fstat(descriptor)
            named = os.stat(root, follow_symlinks=False)
            if (
                not stat.S_ISDIR(opened.st_mode)
                or not stat.S_ISDIR(named.st_mode)
                or (opened.st_dev, opened.st_ino) != (named.st_dev, named.st_ino)
            ):
                raise ValueError("workspace root changed during journal setup")
        except OSError as error:
            raise ValueError("workspace root is unsafe") from error
        finally:
            if descriptor is not None:
                os.close(descriptor)
        self.session = session
        self.workspace_root = root
        self._workspace_root_identity = (opened.st_dev, opened.st_ino)

    def record_intent(
        self,
        path: str,
        after_content: str,
        cause: Literal["tool", "undo"] = "tool",
        *,
        after_mode: int | None = None,
    ) -> MutationIntent:
        """Fsync a bounded before-image before a caller replaces the file."""

        if not isinstance(after_content, str):
            raise TypeError("after_content must be a string")
        after_bytes = after_content.encode("utf-8")
        if len(after_bytes) > _MAX_BEFORE_IMAGE_BYTES:
            raise AgentError(
                f"mutation content exceeds {_MAX_BEFORE_IMAGE_BYTES} bytes"
            )
        if not isinstance(cause, str) or cause not in {"tool", "undo"}:
            raise ValueError("mutation cause is invalid")

        relative, parent, name = self._open_parent_dir(path)
        before_sha256 = None
        before_content = None
        before_mode = None
        try:
            parent_status = os.fstat(parent)
            parent_identity = (parent_status.st_dev, parent_status.st_ino)
            observed = self._read_regular_at(parent, name, allow_missing=True)
        finally:
            os.close(parent)
        if observed is not None:
            content, status = observed
            try:
                before_content = content.decode("utf-8")
            except UnicodeDecodeError as error:
                raise AgentError("mutation before-image must be UTF-8 text") from error
            before_sha256 = self._digest(content)
            before_mode = stat.S_IMODE(status.st_mode)

        if after_mode is None:
            after_mode = 0o600 if before_mode is None else before_mode & 0o777
        if (
            isinstance(after_mode, bool)
            or not isinstance(after_mode, int)
            or not 0 <= after_mode <= 0o7777
        ):
            raise ValueError("mutation after mode is invalid")

        intent = MutationIntent(
            uuid.uuid4().hex,
            relative,
            *parent_identity,
            before_sha256,
            before_content,
            before_mode,
            self._digest(after_bytes),
            after_mode,
            cause,
        )
        self.session.append(
            "mutation_intent",
            intent_id=intent.id,
            path=intent.path,
            parent_dev=intent.parent_dev,
            parent_ino=intent.parent_ino,
            before_sha256=intent.before_sha256,
            before_content=intent.before_content,
            before_mode=intent.before_mode,
            after_sha256=intent.after_sha256,
            after_mode=intent.after_mode,
            cause=intent.cause,
            branch_id=self._active_branch_id(),
        )
        return intent

    def commit(self, intent: MutationIntent) -> RecoveryResult:
        """Record completion only when the workspace has the intended after-image."""

        logged, resolutions = self._journal_state()
        entry = logged.get(intent.id)
        if entry is None or entry.intent != intent:
            raise ValueError("mutation intent is not present in this session")
        if intent.id in resolutions:
            raise ValueError("mutation intent is already resolved")
        try:
            current_sha256, current_mode = self._current_fingerprint(
                intent.path,
                expected_parent=(intent.parent_dev, intent.parent_ino),
            )
        except AgentError as error:
            raise AgentError("mutation target is unsafe after the write") from error
        if (current_sha256, current_mode) != (
            intent.after_sha256,
            intent.after_mode,
        ):
            raise AgentError("mutation result does not match its recorded intent")
        self._append_resolution(
            entry,
            "committed",
            current_sha256,
            current_mode,
            recovered=False,
        )
        return RecoveryResult(intent.id, intent.path, "committed")

    def recover_pending(self) -> tuple[RecoveryResult, ...]:
        """Classify crash-interrupted intents by hashes without changing any file."""

        logged, resolutions = self._journal_state()
        recovered: list[RecoveryResult] = []
        for entry in sorted(logged.values(), key=lambda item: item.event_index):
            intent = entry.intent
            if intent.id in resolutions:
                continue
            unsafe = False
            try:
                current_sha256, current_mode = self._current_fingerprint(
                    intent.path,
                    expected_parent=(intent.parent_dev, intent.parent_ino),
                )
            except AgentError:
                current_sha256 = None
                current_mode = None
                unsafe = True
            if not unsafe and (current_sha256, current_mode) == (
                intent.after_sha256,
                intent.after_mode,
            ):
                status: Literal["committed", "not_applied", "conflict"] = "committed"
            elif not unsafe and (current_sha256, current_mode) == (
                intent.before_sha256,
                intent.before_mode,
            ):
                status = "not_applied"
            else:
                status = "conflict"
            self._append_resolution(
                entry,
                status,
                current_sha256,
                current_mode,
                recovered=True,
            )
            recovered.append(RecoveryResult(intent.id, intent.path, status))
        return tuple(recovered)

    def recover(self) -> tuple[RecoveryResult, ...]:
        """Alias for startup recovery of pending mutation intents."""

        return self.recover_pending()

    def create_checkpoint(self, name: str) -> Checkpoint:
        """Append a branch-local checkpoint after resolving uncertain writes."""

        if (
            not isinstance(name, str)
            or not name.strip()
            or len(name) > _MAX_CHECKPOINT_NAME_CHARS
            or "\x00" in name
        ):
            raise ValueError("checkpoint name is invalid")
        self.recover_pending()
        events = self.session.events
        if not events:
            raise ValueError("checkpoint requires a started session")
        checkpoint = Checkpoint(
            uuid.uuid4().hex,
            name,
            events[-1].id,
            self._active_branch_id(),
        )
        self.session.append(
            "checkpoint",
            checkpoint_id=checkpoint.id,
            name=checkpoint.name,
            event_id=checkpoint.event_id,
            branch_id=checkpoint.branch_id,
        )
        return checkpoint

    def checkpoint(self, name: str) -> Checkpoint:
        """Alias for ``create_checkpoint`` used by the interactive command layer."""

        return self.create_checkpoint(name)

    def plan_undo(self, checkpoint: Checkpoint | str) -> UndoPlan:
        """Collapse committed post-checkpoint writes into one restore per path."""

        self.recover_pending()
        events = self.session.events
        selected, checkpoint_index = self._select_checkpoint(checkpoint, events)
        if selected.branch_id != self._active_branch_id():
            raise ValueError("checkpoint belongs to a different session branch")

        logged, resolutions = self._journal_state(events)
        already_undone = self._applied_undo_intent_ids(events, selected.branch_id)
        grouped: dict[str, list[_LoggedIntent]] = {}
        warnings: list[str] = []
        for entry in sorted(logged.values(), key=lambda item: item.event_index):
            if entry.event_index <= checkpoint_index:
                continue
            if entry.branch_id != selected.branch_id:
                continue
            if entry.intent.id in already_undone:
                continue
            resolution = resolutions.get(entry.intent.id)
            if resolution == "committed":
                grouped.setdefault(entry.intent.path, []).append(entry)
            elif resolution == "conflict":
                warnings.append(
                    f"unresolved external change prevents undo of {entry.intent.path}"
                )

        ordered: list[tuple[int, PlannedRestore]] = []
        for path, entries in grouped.items():
            first = entries[0].intent
            latest = entries[-1].intent
            continuous = all(
                (
                    current.intent.parent_dev,
                    current.intent.parent_ino,
                    current.intent.before_sha256,
                    current.intent.before_mode,
                )
                == (
                    previous.intent.parent_dev,
                    previous.intent.parent_ino,
                    previous.intent.after_sha256,
                    previous.intent.after_mode,
                )
                for previous, current in zip(entries, entries[1:], strict=False)
            )
            if not continuous:
                warnings.append(
                    f"mutation history for {path} is discontinuous; "
                    "the path was omitted from undo"
                )
                continue
            ordered.append(
                (
                    entries[-1].event_index,
                    PlannedRestore(
                        intent_id=latest.id,
                        path=path,
                        expected_parent_dev=latest.parent_dev,
                        expected_parent_ino=latest.parent_ino,
                        expected_sha256=latest.after_sha256,
                        expected_mode=latest.after_mode,
                        restore_content=first.before_content,
                        restore_mode=first.before_mode,
                        remove=first.before_sha256 is None,
                        covered_intent_ids=tuple(entry.intent.id for entry in entries),
                    ),
                )
            )

        command_warning = self._command_warning_after(
            events, checkpoint_index, selected.branch_id
        )
        if command_warning is not None:
            warnings.append(command_warning)
        changes = tuple(item for _, item in sorted(ordered, key=lambda item: item[0]))
        return UndoPlan(selected, changes, tuple(dict.fromkeys(warnings)))

    def _applied_undo_intent_ids(
        self, events: tuple[SessionEvent, ...], branch_id: str
    ) -> set[str]:
        """Return only source intents durably covered by finished undo changes."""

        def valid_hex(value: object, length: int) -> bool:
            return (
                isinstance(value, str)
                and len(value) == length
                and all(character in "0123456789abcdef" for character in value)
            )

        intents: dict[str, tuple[str, int, int, int]] = {}
        committed: set[str] = set()
        starts: dict[str, dict[str, object]] = {}
        finished: set[str] = set()
        applied: set[str] = set()
        for index, event in enumerate(events):
            data = event.data
            event_branch = data.get("branch_id")
            if event.type == "mutation_intent" and event_branch == branch_id:
                intent_id = data.get("intent_id")
                path = data.get("path")
                parent_dev = data.get("parent_dev")
                parent_ino = data.get("parent_ino")
                if (
                    not valid_hex(intent_id, 32)
                    or not isinstance(path, str)
                    or not self._valid_identity_component(parent_dev)
                    or not self._valid_identity_component(parent_ino)
                ):
                    raise ValueError("undo source intent is invalid")
                intents[intent_id] = (path, index, parent_dev, parent_ino)
                continue
            if event.type == "mutation_committed" and event_branch == branch_id:
                intent_id = data.get("intent_id")
                if intent_id not in intents:
                    raise ValueError("undo source resolution is invalid")
                committed.add(intent_id)
                continue
            if event.type not in {"undo_change_started", "undo_change_finished"}:
                continue
            if event_branch != branch_id:
                continue
            change_id = data.get("undo_change_id")
            if not valid_hex(change_id, 32):
                raise ValueError("undo change event has an invalid ID")
            if event.type == "undo_change_started":
                covered = data.get("covered_intent_ids")
                if (
                    change_id in starts
                    or not isinstance(covered, list)
                    or not covered
                    or len(set(covered)) != len(covered)
                    or any(not valid_hex(intent_id, 32) for intent_id in covered)
                    or any(intent_id not in committed for intent_id in covered)
                ):
                    raise ValueError("undo change coverage is invalid")
                path = data.get("path")
                operation = data.get("operation")
                expected_parent = (
                    data.get("expected_parent_dev"),
                    data.get("expected_parent_ino"),
                )
                if (
                    not isinstance(path, str)
                    or any(intents[intent_id][0] != path for intent_id in covered)
                    or any(
                        intents[intent_id][2:] != expected_parent
                        for intent_id in covered
                    )
                    or data.get("intent_id") != covered[-1]
                    or not valid_hex(data.get("checkpoint_id"), 32)
                    or not valid_hex(data.get("plan_fingerprint"), 64)
                    or operation not in {"remove", "restore"}
                    or data.get("retained_recovery_path")
                    != self._expected_retained_recovery_path(
                        path,
                        operation,
                        change_id,
                    )
                    or not self._valid_identity_component(
                        data.get("expected_parent_dev")
                    )
                    or not self._valid_identity_component(
                        data.get("expected_parent_ino")
                    )
                    or not valid_hex(data.get("expected_sha256"), 64)
                    or isinstance(data.get("expected_mode"), bool)
                    or not isinstance(data.get("expected_mode"), int)
                    or not 0 <= data["expected_mode"] <= 0o7777
                ):
                    raise ValueError("undo change does not match its source intents")
                starts[change_id] = {
                    "covered_intent_ids": tuple(covered),
                    "checkpoint_id": data.get("checkpoint_id"),
                    "plan_fingerprint": data.get("plan_fingerprint"),
                    "intent_id": data.get("intent_id"),
                    "path": path,
                    "operation": operation,
                    "retained_recovery_path": data.get("retained_recovery_path"),
                }
            else:
                if change_id not in starts or change_id in finished:
                    raise ValueError("undo change completion is invalid")
                start = starts[change_id]
                if any(
                    data.get(field) != value
                    for field, value in start.items()
                    if field != "covered_intent_ids"
                ) or data.get("covered_intent_ids") != list(
                    start["covered_intent_ids"]
                ):
                    raise ValueError("undo change completion coverage changed")
                covered = set(start["covered_intent_ids"])
                if covered & applied:
                    raise ValueError("undo source intent was completed more than once")
                applied.update(covered)
                finished.add(change_id)
        return applied

    def apply_undo(
        self,
        plan: UndoPlan,
        confirm: Callable[[UndoPlan], bool] | None = None,
    ) -> UndoResult:
        """Apply or safely resume a reviewed, write-ahead-journaled undo plan."""

        warnings = list(plan.warnings)
        completed_artifacts = self._undo_already_completed(plan)
        if completed_artifacts is not None:
            warnings.append("undo was already completed")
            return UndoResult(
                (),
                (),
                (),
                tuple(dict.fromkeys(warnings)),
                completed_artifacts,
            )
        if not plan.changes:
            warnings.append("undo plan has no reversible file changes")
            return UndoResult((), (), (), tuple(dict.fromkeys(warnings)))

        (
            completed,
            recovery_conflicts,
            durably_covered,
            recovered_artifacts,
        ) = self._reconcile_undo_changes(plan)
        remaining = tuple(
            change for change in plan.changes if change.path not in durably_covered
        )
        canonical_plan = self.plan_undo(plan.checkpoint)
        if (
            canonical_plan.checkpoint != plan.checkpoint
            or canonical_plan.changes != remaining
            or not set(canonical_plan.warnings).issubset(plan.warnings)
        ):
            raise ValueError("undo plan is stale or does not match the session journal")
        restored = [
            change.path
            for change in plan.changes
            if completed.get(change.path) == "restore"
        ]
        removed = [
            change.path
            for change in plan.changes
            if completed.get(change.path) == "remove"
        ]
        retained_recovery_files = list(recovered_artifacts)
        if completed:
            warnings.append("resumed a partially applied undo from its durable journal")
        if recovery_conflicts:
            warnings.append("undo recovery found externally changed files")
            return UndoResult(
                tuple(restored),
                tuple(removed),
                tuple(recovery_conflicts),
                tuple(dict.fromkeys(warnings)),
                tuple(retained_recovery_files),
            )

        if not remaining:
            self._append_undo_completed(
                plan,
                restored,
                removed,
                [],
                retained_recovery_files,
                recovered=True,
            )
            return UndoResult(
                tuple(restored),
                tuple(removed),
                (),
                tuple(dict.fromkeys(warnings)),
                tuple(retained_recovery_files),
            )
        if confirm is None:
            warnings.append("undo requires explicit operator confirmation")
            return UndoResult(
                tuple(restored),
                tuple(removed),
                (),
                tuple(dict.fromkeys(warnings)),
                tuple(retained_recovery_files),
            )

        conflicts = self._preflight(remaining)
        if conflicts:
            warnings.append("undo was not applied because preflight found conflicts")
            return UndoResult(
                tuple(restored),
                tuple(removed),
                tuple(conflicts),
                tuple(dict.fromkeys(warnings)),
                tuple(retained_recovery_files),
            )
        active_plan = UndoPlan(plan.checkpoint, remaining, tuple(warnings))
        if not confirm(active_plan):
            warnings.append("operator denied undo")
            return UndoResult(
                tuple(restored),
                tuple(removed),
                (),
                tuple(dict.fromkeys(warnings)),
                tuple(retained_recovery_files),
            )

        self.session.append(
            "undo_started",
            checkpoint_id=plan.checkpoint.id,
            branch_id=plan.checkpoint.branch_id,
            plan_fingerprint=self._undo_plan_fingerprint(plan),
            paths=[change.path for change in remaining],
            resumed=bool(completed),
        )
        conflicts = []
        for change in reversed(remaining):
            operation = "remove" if change.remove else "restore"
            change_id = uuid.uuid4().hex
            retained_recovery_path = self._retained_recovery_path(change, change_id)
            retained_basename = Path(retained_recovery_path).name
            try:
                if self._current_fingerprint(
                    change.path,
                    expected_parent=(
                        change.expected_parent_dev,
                        change.expected_parent_ino,
                    ),
                ) != (
                    change.expected_sha256,
                    change.expected_mode,
                ):
                    conflicts.append(change.path)
                    continue
                started_event = self.session.append(
                    "undo_change_started",
                    undo_change_id=change_id,
                    checkpoint_id=plan.checkpoint.id,
                    plan_fingerprint=self._undo_plan_fingerprint(plan),
                    intent_id=change.intent_id,
                    covered_intent_ids=list(change.covered_intent_ids),
                    path=change.path,
                    operation=operation,
                    retained_recovery_path=retained_recovery_path,
                    expected_parent_dev=change.expected_parent_dev,
                    expected_parent_ino=change.expected_parent_ino,
                    expected_sha256=change.expected_sha256,
                    expected_mode=change.expected_mode,
                    result_sha256=self._undo_result_sha256(change),
                    result_mode=change.restore_mode,
                    branch_id=plan.checkpoint.branch_id,
                )
                if (
                    started_event.data.get("retained_recovery_path")
                    != retained_recovery_path
                ):
                    raise ValueError("undo retained recovery path changed on append")
                retained_recovery_files.append(retained_recovery_path)
                if change.remove:
                    self._remove_exact(
                        change.path,
                        change.expected_sha256,
                        change.expected_mode,
                        expected_parent=(
                            change.expected_parent_dev,
                            change.expected_parent_ino,
                        ),
                        quarantine_name=retained_basename,
                    )
                    removed.append(change.path)
                else:
                    if change.restore_content is None or change.restore_mode is None:
                        conflicts.append(change.path)
                        continue
                    self._restore_exact(
                        change,
                        backup_name=retained_basename,
                    )
                    restored.append(change.path)
                finished_event = self.session.append(
                    "undo_change_finished",
                    undo_change_id=change_id,
                    checkpoint_id=plan.checkpoint.id,
                    plan_fingerprint=self._undo_plan_fingerprint(plan),
                    intent_id=change.intent_id,
                    covered_intent_ids=list(change.covered_intent_ids),
                    path=change.path,
                    operation=operation,
                    retained_recovery_path=retained_recovery_path,
                    branch_id=plan.checkpoint.branch_id,
                    recovered=False,
                )
                if (
                    finished_event.data.get("retained_recovery_path")
                    != retained_recovery_path
                ):
                    raise ValueError("undo retained recovery path changed on append")
            except (AgentError, OSError, ValueError) as error:
                conflicts.append(change.path)
                warnings.append(f"could not undo {change.path}: {error}")

        self._append_undo_completed(
            plan,
            restored,
            removed,
            conflicts,
            retained_recovery_files,
            recovered=False,
        )
        return UndoResult(
            tuple(restored),
            tuple(removed),
            tuple(dict.fromkeys(conflicts)),
            tuple(dict.fromkeys(warnings)),
            tuple(dict.fromkeys(retained_recovery_files)),
        )

    def _append_undo_completed(
        self,
        plan: UndoPlan,
        restored: list[str],
        removed: list[str],
        conflicts: list[str],
        retained_recovery_files: list[str],
        *,
        recovered: bool,
    ) -> None:
        retained_recovery_files = list(dict.fromkeys(retained_recovery_files))
        self.session.append(
            "undo_completed",
            checkpoint_id=plan.checkpoint.id,
            branch_id=plan.checkpoint.branch_id,
            plan_fingerprint=self._undo_plan_fingerprint(plan),
            paths=[change.path for change in plan.changes],
            restored=restored,
            removed=removed,
            conflicts=conflicts,
            retained_recovery_files=retained_recovery_files,
            recovered=recovered,
        )

    def _undo_result_sha256(self, change: PlannedRestore) -> str | None:
        if change.remove:
            return None
        if change.restore_content is None:
            raise ValueError("undo restore has no before-image")
        return self._digest(change.restore_content.encode("utf-8"))

    @staticmethod
    def _expected_retained_recovery_path(
        path: str,
        operation: Literal["remove", "restore"],
        change_id: str,
    ) -> str:
        prefix = (
            ".tiny-llm-undo-remove-"
            if operation == "remove"
            else ".tiny-llm-undo-backup-"
        )
        parent = Path(path).parent
        return (parent / f"{prefix}{change_id}.tmp").as_posix()

    @classmethod
    def _retained_recovery_path(
        cls,
        change: PlannedRestore,
        change_id: str,
    ) -> str:
        operation: Literal["remove", "restore"] = (
            "remove" if change.remove else "restore"
        )
        return cls._expected_retained_recovery_path(
            change.path,
            operation,
            change_id,
        )

    def _undo_plan_fingerprint(self, plan: UndoPlan) -> str:
        payload = {
            "checkpoint_id": plan.checkpoint.id,
            "branch_id": plan.checkpoint.branch_id,
            "changes": [
                {
                    "intent_id": change.intent_id,
                    "path": change.path,
                    "expected_parent_dev": change.expected_parent_dev,
                    "expected_parent_ino": change.expected_parent_ino,
                    "expected_sha256": change.expected_sha256,
                    "expected_mode": change.expected_mode,
                    "result_sha256": self._undo_result_sha256(change),
                    "result_mode": change.restore_mode,
                    "remove": change.remove,
                    "covered_intent_ids": list(change.covered_intent_ids),
                }
                for change in plan.changes
            ],
        }
        encoded = json.dumps(
            payload,
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        return self._digest(encoded)

    def _reconcile_undo_changes(
        self, plan: UndoPlan
    ) -> tuple[dict[str, str], list[str], set[str], tuple[str, ...]]:
        """Resolve started undo changes by state without replaying or clobbering."""

        changes = {change.path: change for change in plan.changes}
        plan_fingerprint = self._undo_plan_fingerprint(plan)
        starts: dict[str, tuple[SessionEvent, PlannedRestore, str]] = {}
        retained_recovery_files: list[str] = []
        resolutions: dict[str, str] = {}
        for event in self.session.events:
            if event.type not in {
                "undo_change_started",
                "undo_change_finished",
                "undo_change_recovered",
            }:
                continue
            data = event.data
            if (
                data.get("checkpoint_id") != plan.checkpoint.id
                or data.get("branch_id") != plan.checkpoint.branch_id
                or data.get("plan_fingerprint") != plan_fingerprint
            ):
                continue
            change_id = data.get("undo_change_id")
            if (
                not isinstance(change_id, str)
                or len(change_id) != 32
                or any(character not in "0123456789abcdef" for character in change_id)
            ):
                raise ValueError("undo change event has an invalid ID")
            if event.type == "undo_change_started":
                path = data.get("path")
                change = changes.get(path)
                if change_id in starts or change is None:
                    raise ValueError("undo change start is invalid")
                operation = "remove" if change.remove else "restore"
                retained_recovery_path = self._retained_recovery_path(
                    change,
                    change_id,
                )
                if (
                    data.get("intent_id") != change.intent_id
                    or data.get("covered_intent_ids") != list(change.covered_intent_ids)
                    or data.get("operation") != operation
                    or data.get("retained_recovery_path") != retained_recovery_path
                    or data.get("expected_parent_dev") != change.expected_parent_dev
                    or data.get("expected_parent_ino") != change.expected_parent_ino
                    or data.get("expected_sha256") != change.expected_sha256
                    or data.get("expected_mode") != change.expected_mode
                    or data.get("result_sha256") != self._undo_result_sha256(change)
                    or data.get("result_mode") != change.restore_mode
                ):
                    raise ValueError("undo change start does not match its plan")
                starts[change_id] = (event, change, retained_recovery_path)
                retained_recovery_files.append(retained_recovery_path)
                continue
            if change_id not in starts or change_id in resolutions:
                raise ValueError("undo change resolution is invalid")
            _started, change, retained_recovery_path = starts[change_id]
            operation = "remove" if change.remove else "restore"
            if (
                data.get("intent_id") != change.intent_id
                or data.get("covered_intent_ids") != list(change.covered_intent_ids)
                or data.get("path") != change.path
                or data.get("operation") != operation
                or data.get("retained_recovery_path") != retained_recovery_path
            ):
                raise ValueError("undo change resolution does not match its start")
            if event.type == "undo_change_finished":
                resolutions[change_id] = "applied"
            else:
                status = data.get("status")
                if status not in {"not_applied", "conflict"}:
                    raise ValueError("undo recovery status is invalid")
                resolutions[change_id] = status

        completed: dict[str, str] = {}
        conflicts: list[str] = []
        durably_covered: set[str] = set()
        for change_id, (_event, change, retained_recovery_path) in starts.items():
            resolution = resolutions.get(change_id)
            operation = "remove" if change.remove else "restore"
            if resolution == "applied":
                if change.path in durably_covered:
                    raise ValueError("undo path was completed more than once")
                durably_covered.add(change.path)
                try:
                    result_matches = self._undo_result_matches(change)
                except AgentError:
                    result_matches = False
                if result_matches:
                    if change.path in completed:
                        raise ValueError("undo path was completed more than once")
                    completed[change.path] = operation
                else:
                    conflicts.append(change.path)
                continue
            if resolution is not None:
                continue

            try:
                current_sha256, current_mode = self._current_fingerprint(
                    change.path,
                    expected_parent=(
                        change.expected_parent_dev,
                        change.expected_parent_ino,
                    ),
                )
                result_matches = self._undo_result_matches(change)
                if result_matches:
                    self._fsync_reconciled_undo_result(change)
            except AgentError:
                self.session.append(
                    "undo_change_recovered",
                    undo_change_id=change_id,
                    checkpoint_id=plan.checkpoint.id,
                    plan_fingerprint=plan_fingerprint,
                    intent_id=change.intent_id,
                    covered_intent_ids=list(change.covered_intent_ids),
                    path=change.path,
                    operation=operation,
                    retained_recovery_path=retained_recovery_path,
                    branch_id=plan.checkpoint.branch_id,
                    status="conflict",
                    current_sha256=None,
                    current_mode=None,
                )
                conflicts.append(change.path)
                continue
            if result_matches:
                if change.path in completed or change.path in durably_covered:
                    raise ValueError("undo path was completed more than once")
                self.session.append(
                    "undo_change_finished",
                    undo_change_id=change_id,
                    checkpoint_id=plan.checkpoint.id,
                    plan_fingerprint=plan_fingerprint,
                    intent_id=change.intent_id,
                    covered_intent_ids=list(change.covered_intent_ids),
                    path=change.path,
                    operation=operation,
                    retained_recovery_path=retained_recovery_path,
                    branch_id=plan.checkpoint.branch_id,
                    recovered=True,
                )
                completed[change.path] = operation
                durably_covered.add(change.path)
            else:
                status = (
                    "not_applied"
                    if (current_sha256, current_mode)
                    == (change.expected_sha256, change.expected_mode)
                    else "conflict"
                )
                self.session.append(
                    "undo_change_recovered",
                    undo_change_id=change_id,
                    checkpoint_id=plan.checkpoint.id,
                    plan_fingerprint=plan_fingerprint,
                    intent_id=change.intent_id,
                    covered_intent_ids=list(change.covered_intent_ids),
                    path=change.path,
                    operation=operation,
                    retained_recovery_path=retained_recovery_path,
                    branch_id=plan.checkpoint.branch_id,
                    status=status,
                    current_sha256=current_sha256,
                    current_mode=current_mode,
                )
                if status == "conflict":
                    conflicts.append(change.path)
        return (
            completed,
            list(dict.fromkeys(conflicts)),
            durably_covered,
            tuple(dict.fromkeys(retained_recovery_files)),
        )

    def _undo_result_matches(self, change: PlannedRestore) -> bool:
        result_mode = None if change.remove else change.restore_mode
        return self._current_fingerprint(
            change.path,
            expected_parent=(
                change.expected_parent_dev,
                change.expected_parent_ino,
            ),
        ) == (
            self._undo_result_sha256(change),
            result_mode,
        )

    def _fsync_reconciled_undo_result(self, change: PlannedRestore) -> None:
        """Make an observed crash-reconciled namespace result durable."""

        expected_parent = (
            change.expected_parent_dev,
            change.expected_parent_ino,
        )
        _relative, parent, name = self._open_parent_dir(
            change.path,
            expected_parent=expected_parent,
        )
        expected_result = (
            self._undo_result_sha256(change),
            None if change.remove else change.restore_mode,
        )

        def result_fingerprint() -> tuple[str | None, int | None]:
            current = self._read_regular_at(
                parent,
                name,
                allow_missing=change.remove,
            )
            if current is None:
                return None, None
            content, status = current
            return self._digest(content), stat.S_IMODE(status.st_mode)

        try:
            if result_fingerprint() != expected_result:
                raise AgentError("undo result changed during crash reconciliation")
            os.fsync(parent)
            parent_status = os.fstat(parent)
            if (parent_status.st_dev, parent_status.st_ino) != expected_parent:
                raise AgentError("mutation parent directory was replaced")
            if result_fingerprint() != expected_result:
                raise AgentError("undo result changed during crash reconciliation")
        except OSError as error:
            raise AgentError(
                "could not make crash-reconciled undo result durable"
            ) from error
        finally:
            os.close(parent)

    def _current_mode(self, raw: str) -> int | None:
        return self._current_fingerprint(raw)[1]

    def _undo_already_completed(self, plan: UndoPlan) -> tuple[str, ...] | None:
        """Return retained artifacts for a durably completed exact undo plan."""

        paths = [change.path for change in plan.changes]
        plan_fingerprint = self._undo_plan_fingerprint(plan)
        changes = {change.path: change for change in plan.changes}
        starts: dict[str, tuple[str, str, int]] = {}
        finished_artifacts: dict[str, tuple[str, int]] = {}
        started_artifacts: list[tuple[str, int]] = []
        events = self.session.events
        for event_index, event in enumerate(events):
            if event.type not in {"undo_change_started", "undo_change_finished"}:
                continue
            data = event.data
            if (
                data.get("checkpoint_id") != plan.checkpoint.id
                or data.get("branch_id") != plan.checkpoint.branch_id
                or data.get("plan_fingerprint") != plan_fingerprint
            ):
                continue
            change_id = data.get("undo_change_id")
            if (
                not isinstance(change_id, str)
                or len(change_id) != 32
                or any(character not in "0123456789abcdef" for character in change_id)
            ):
                raise ValueError("undo change event has an invalid ID")
            if event.type == "undo_change_started":
                path = data.get("path")
                change = changes.get(path)
                if change_id in starts or change is None:
                    raise ValueError("undo change start is invalid")
                retained = self._retained_recovery_path(change, change_id)
                if data.get("retained_recovery_path") != retained:
                    raise ValueError("undo retained recovery path is invalid")
                starts[change_id] = (change.path, retained, event_index)
                started_artifacts.append((retained, event_index))
                continue
            if change_id not in starts:
                raise ValueError("undo change completion is invalid")
            path, retained, _started_index = starts[change_id]
            if (
                data.get("path") != path
                or data.get("retained_recovery_path") != retained
                or path in finished_artifacts
            ):
                raise ValueError("undo retained recovery path changed")
            finished_artifacts[path] = (retained, event_index)

        for completion_index in range(len(events) - 1, -1, -1):
            event = events[completion_index]
            if event.type != "undo_completed":
                continue
            data = event.data
            if (
                data.get("checkpoint_id") != plan.checkpoint.id
                or data.get("branch_id") != plan.checkpoint.branch_id
                or data.get("plan_fingerprint") != plan_fingerprint
            ):
                continue
            restored = data.get("restored")
            removed = data.get("removed")
            conflicts = data.get("conflicts")
            retained = data.get("retained_recovery_files")
            if not all(
                isinstance(value, list)
                for value in (restored, removed, conflicts, retained)
            ):
                raise ValueError("undo completion event is invalid")
            if any(not isinstance(path, str) for path in retained) or len(
                set(retained)
            ) != len(retained):
                raise ValueError("undo completion retained paths are invalid")
            expected_started = {
                path
                for path, event_index in started_artifacts
                if event_index < completion_index
            }
            if set(retained) != expected_started:
                raise ValueError("undo completion omitted retained recovery paths")
            if (
                data.get("paths") != paths
                or conflicts
                or sorted((*restored, *removed)) != sorted(paths)
            ):
                return None
            if any(
                change.path not in finished_artifacts
                or finished_artifacts[change.path][1] >= completion_index
                for change in plan.changes
            ):
                raise ValueError("undo completion has no retained recovery evidence")
            expected_retained = tuple(
                finished_artifacts[change.path][0] for change in plan.changes
            )
            if not set(expected_retained).issubset(retained):
                raise ValueError("undo completion omitted finished recovery evidence")
            return tuple(retained)
        return None

    def _open_parent_dir(
        self,
        raw: str,
        *,
        expected_parent: tuple[int, int] | None = None,
    ) -> tuple[str, int, str]:
        """Open every parent component beneath a held workspace-root descriptor."""

        relative = self._validate_relative_path(raw)
        parts = Path(relative).parts
        flags = (
            os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
        )
        current = None
        try:
            current = os.open(self.workspace_root, flags)
            opened_root = os.fstat(current)
            named_root = os.stat(self.workspace_root, follow_symlinks=False)
            if (
                not stat.S_ISDIR(opened_root.st_mode)
                or not stat.S_ISDIR(named_root.st_mode)
                or (opened_root.st_dev, opened_root.st_ino)
                != (named_root.st_dev, named_root.st_ino)
                or (opened_root.st_dev, opened_root.st_ino)
                != self._workspace_root_identity
            ):
                raise AgentError("workspace root changed during journal access")
            for component in parts[:-1]:
                next_descriptor = os.open(component, flags, dir_fd=current)
                try:
                    opened = os.fstat(next_descriptor)
                    named = os.stat(
                        component,
                        dir_fd=current,
                        follow_symlinks=False,
                    )
                    if (
                        not stat.S_ISDIR(opened.st_mode)
                        or not stat.S_ISDIR(named.st_mode)
                        or (opened.st_dev, opened.st_ino)
                        != (named.st_dev, named.st_ino)
                    ):
                        raise AgentError("mutation parent changed during traversal")
                except BaseException:
                    os.close(next_descriptor)
                    raise
                os.close(current)
                current = next_descriptor
            if expected_parent is not None:
                parent_status = os.fstat(current)
                if (parent_status.st_dev, parent_status.st_ino) != expected_parent:
                    raise AgentError("mutation parent directory was replaced")
            return relative, current, parts[-1]
        except AgentError:
            if current is not None:
                os.close(current)
            raise
        except OSError as error:
            if current is not None:
                os.close(current)
            raise AgentError("mutation parent is unsafe") from error
        except BaseException:
            if current is not None:
                os.close(current)
            raise

    def _read_regular_at(
        self,
        parent: int,
        name: str,
        *,
        allow_missing: bool,
    ) -> tuple[bytes, os.stat_result] | None:
        """Read one stable regular-file entry relative to a verified parent."""

        descriptor = None
        try:
            descriptor = os.open(
                name,
                os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0),
                dir_fd=parent,
            )
        except FileNotFoundError:
            if allow_missing:
                return None
            raise AgentError("mutation target no longer exists") from None
        except OSError as error:
            raise AgentError("mutation target is not a safe regular file") from error
        try:
            opened = os.fstat(descriptor)
            named = os.stat(name, dir_fd=parent, follow_symlinks=False)
            if (
                not stat.S_ISREG(opened.st_mode)
                or opened.st_nlink != 1
                or opened.st_size > _MAX_BEFORE_IMAGE_BYTES
                or (opened.st_dev, opened.st_ino) != (named.st_dev, named.st_ino)
                or stat.S_IMODE(opened.st_mode) != stat.S_IMODE(named.st_mode)
            ):
                raise AgentError("mutation target is unsafe or too large")
            with os.fdopen(descriptor, "rb", closefd=False) as file:
                content = file.read(_MAX_BEFORE_IMAGE_BYTES + 1)
            latest_opened = os.fstat(descriptor)
            latest = os.stat(name, dir_fd=parent, follow_symlinks=False)
            if (
                len(content) > _MAX_BEFORE_IMAGE_BYTES
                or (latest.st_dev, latest.st_ino) != (opened.st_dev, opened.st_ino)
                or stat.S_IMODE(latest.st_mode) != stat.S_IMODE(opened.st_mode)
                or (
                    latest_opened.st_size,
                    latest_opened.st_mtime_ns,
                    latest_opened.st_ctime_ns,
                )
                != (opened.st_size, opened.st_mtime_ns, opened.st_ctime_ns)
                or (
                    latest.st_size,
                    latest.st_mtime_ns,
                    latest.st_ctime_ns,
                )
                != (
                    latest_opened.st_size,
                    latest_opened.st_mtime_ns,
                    latest_opened.st_ctime_ns,
                )
            ):
                raise AgentError("mutation target changed while it was read")
            return content, opened
        except OSError as error:
            raise AgentError("mutation target changed while it was read") from error
        finally:
            os.close(descriptor)

    def _resolve_path(self, raw: str, *, allow_missing: bool) -> tuple[str, Path]:
        relative = self._validate_relative_path(raw)
        unresolved = Path(relative)
        current = self.workspace_root
        for index, part in enumerate(unresolved.parts):
            current /= part
            if current.is_symlink():
                raise AgentError("symlinks cannot be journaled")
            if index < len(unresolved.parts) - 1:
                if not current.exists() or not current.is_dir():
                    raise AgentError("mutation parent must be an existing directory")
        target = (self.workspace_root / unresolved).resolve(strict=False)
        try:
            resolved_relative = target.relative_to(self.workspace_root).as_posix()
        except ValueError as error:
            raise AgentError("path leaves the workspace") from error
        if resolved_relative != relative:
            raise AgentError("path leaves the workspace")
        if not allow_missing and not target.exists():
            raise AgentError(f"path does not exist: {relative}")
        return relative, target

    @staticmethod
    def _validate_relative_path(raw: str) -> str:
        """Validate a journal path lexically without consulting mutable files."""

        if not isinstance(raw, str) or not raw or "\x00" in raw:
            raise AgentError("path must be a non-empty string")
        unresolved = Path(raw)
        if unresolved.is_absolute():
            raise AgentError("absolute paths are not allowed")
        if unresolved in {Path("."), Path("")} or ".." in unresolved.parts:
            raise AgentError("parent paths and workspace root are not allowed")
        for part in unresolved.parts:
            lower = part.lower()
            if (
                lower in _PROTECTED_NAMES
                or lower.startswith(".env.")
                or lower.startswith(".tiny-llm-agent-")
                or lower.startswith(".tiny-llm-undo-")
                or lower.endswith((".pem", ".key"))
            ):
                raise AgentError("protected paths cannot be journaled")
        relative = unresolved.as_posix()
        if relative != raw:
            raise AgentError("path must be normalized")
        return relative

    @staticmethod
    def _digest(content: bytes) -> str:
        return hashlib.sha256(content).hexdigest()

    @staticmethod
    def _valid_identity_component(value: object) -> bool:
        return not isinstance(value, bool) and isinstance(value, int) and value >= 0

    def _read_regular_file(self, path: Path) -> tuple[bytes, os.stat_result]:
        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        try:
            descriptor = os.open(path, flags)
        except OSError as error:
            raise AgentError("mutation target is not a safe regular file") from error
        try:
            status = os.fstat(descriptor)
            if (
                not stat.S_ISREG(status.st_mode)
                or status.st_nlink != 1
                or status.st_size > _MAX_BEFORE_IMAGE_BYTES
            ):
                raise AgentError("mutation target is unsafe or too large")
            with os.fdopen(descriptor, "rb", closefd=False) as file:
                content = file.read(_MAX_BEFORE_IMAGE_BYTES + 1)
            if len(content) > _MAX_BEFORE_IMAGE_BYTES:
                raise AgentError("mutation target is too large")
            latest = os.stat(path, follow_symlinks=False)
            if (latest.st_dev, latest.st_ino) != (status.st_dev, status.st_ino):
                raise AgentError("mutation target changed while it was read")
            return content, status
        finally:
            os.close(descriptor)

    def _current_sha256(self, raw: str) -> str | None:
        return self._current_fingerprint(raw)[0]

    def _current_fingerprint(
        self,
        raw: str,
        *,
        expected_parent: tuple[int, int] | None = None,
    ) -> tuple[str | None, int | None]:
        """Return one race-checked content-and-mode fingerprint."""

        _, parent, name = self._open_parent_dir(raw, expected_parent=expected_parent)
        try:
            observed = self._read_regular_at(parent, name, allow_missing=True)
        finally:
            os.close(parent)
        if observed is None:
            return None, None
        content, status = observed
        return self._digest(content), stat.S_IMODE(status.st_mode)

    def _active_branch_id(self) -> str:
        events = self.session.events
        branch_id = getattr(self.session, "session_id", "main")
        if events and isinstance(events[0].data.get("branch_id"), str):
            branch_id = events[0].data["branch_id"]
        branch_events = {
            "branch_selected",
            "branch_started",
            "session_branch",
            "session_branched",
        }
        for event in events:
            active = event.data.get("active_branch_id")
            if isinstance(active, str) and active:
                branch_id = active
            elif event.type in branch_events:
                candidate = event.data.get("branch_id")
                if isinstance(candidate, str) and candidate:
                    branch_id = candidate
        return branch_id

    @staticmethod
    def _event_branch(event: SessionEvent, default: str) -> str:
        branch_id = event.data.get("branch_id", default)
        if not isinstance(branch_id, str) or not branch_id:
            raise ValueError("journal event has an invalid branch ID")
        return branch_id

    @staticmethod
    def _valid_digest(value: object, *, optional: bool = False) -> bool:
        if value is None:
            return optional
        return (
            isinstance(value, str)
            and len(value) == _HEX_DIGEST_LENGTH
            and all(character in "0123456789abcdef" for character in value)
        )

    def _parse_intent(self, event: SessionEvent, index: int) -> _LoggedIntent:
        data = event.data
        intent_id = data.get("intent_id")
        path = data.get("path")
        parent_dev = data.get("parent_dev")
        parent_ino = data.get("parent_ino")
        before_sha256 = data.get("before_sha256")
        before_content = data.get("before_content")
        before_mode = data.get("before_mode")
        after_sha256 = data.get("after_sha256")
        after_mode = data.get("after_mode")
        cause = data.get("cause")
        if not isinstance(intent_id, str) or len(intent_id) != 32:
            raise ValueError("journal event has an invalid intent ID")
        if not isinstance(path, str):
            raise ValueError("journal event has an invalid path")
        if not self._valid_identity_component(
            parent_dev
        ) or not self._valid_identity_component(parent_ino):
            raise ValueError("journal event has an invalid parent identity")
        relative = self._validate_relative_path(path)
        if relative != path:
            raise ValueError("journal event path is not normalized")
        if not self._valid_digest(before_sha256, optional=True):
            raise ValueError("journal event has an invalid before hash")
        if not self._valid_digest(after_sha256):
            raise ValueError("journal event has an invalid after hash")
        if (before_content is None) != (before_sha256 is None) or (
            before_mode is None
        ) != (before_sha256 is None):
            raise ValueError("journal event has an incomplete before-image")
        if before_content is not None and (
            not isinstance(before_content, str)
            or len(before_content.encode("utf-8")) > _MAX_BEFORE_IMAGE_BYTES
            or self._digest(before_content.encode("utf-8")) != before_sha256
        ):
            raise ValueError("journal event before-image does not match its hash")
        if before_mode is not None and (
            isinstance(before_mode, bool)
            or not isinstance(before_mode, int)
            or not 0 <= before_mode <= 0o7777
        ):
            raise ValueError("journal event has an invalid file mode")
        if (
            isinstance(after_mode, bool)
            or not isinstance(after_mode, int)
            or not 0 <= after_mode <= 0o7777
        ):
            raise ValueError("journal event has an invalid after mode")
        if cause not in {"tool", "undo"}:
            raise ValueError("journal event has an invalid cause")
        intent = MutationIntent(
            intent_id,
            path,
            parent_dev,
            parent_ino,
            before_sha256,
            before_content,
            before_mode,
            after_sha256,
            after_mode,
            cause,
        )
        return _LoggedIntent(
            intent, self._event_branch(event, self._root_branch()), index
        )

    def _journal_state(
        self, events: tuple[SessionEvent, ...] | None = None
    ) -> tuple[dict[str, _LoggedIntent], dict[str, str]]:
        events = self.session.events if events is None else events
        intents: dict[str, _LoggedIntent] = {}
        resolutions: dict[str, str] = {}
        for index, event in enumerate(events):
            if event.type == "mutation_intent":
                entry = self._parse_intent(event, index)
                if entry.intent.id in intents:
                    raise ValueError("duplicate mutation intent ID")
                intents[entry.intent.id] = entry
            elif event.type in {"mutation_committed", "mutation_recovered"}:
                intent_id = event.data.get("intent_id")
                if not isinstance(intent_id, str) or intent_id not in intents:
                    raise ValueError("mutation resolution references an unknown intent")
                if intent_id in resolutions:
                    raise ValueError("mutation intent has multiple resolutions")
                intent = intents[intent_id].intent
                current_sha256 = event.data.get("current_sha256")
                current_mode = event.data.get("current_mode")
                if event.data.get("path") != intent.path:
                    raise ValueError("mutation resolution changed paths")
                if not self._valid_digest(current_sha256, optional=True):
                    raise ValueError("mutation resolution has an invalid current hash")
                if (current_sha256 is None) != (current_mode is None) or (
                    current_mode is not None
                    and (
                        isinstance(current_mode, bool)
                        or not isinstance(current_mode, int)
                        or not 0 <= current_mode <= 0o7777
                    )
                ):
                    raise ValueError("mutation resolution has an invalid current mode")
                if event.type == "mutation_committed":
                    status = "committed"
                    if (current_sha256, current_mode) != (
                        intent.after_sha256,
                        intent.after_mode,
                    ):
                        raise ValueError(
                            "mutation commit does not match its after fingerprint"
                        )
                else:
                    status = event.data.get("status")
                    if status not in {"not_applied", "conflict"}:
                        raise ValueError("mutation recovery status is invalid")
                    if status == "not_applied" and (
                        current_sha256,
                        current_mode,
                    ) != (intent.before_sha256, intent.before_mode):
                        raise ValueError(
                            "unapplied mutation does not match its before fingerprint"
                        )
                if (
                    self._event_branch(event, intents[intent_id].branch_id)
                    != intents[intent_id].branch_id
                ):
                    raise ValueError("mutation resolution changed branches")
                resolutions[intent_id] = status
        return intents, resolutions

    def _root_branch(self) -> str:
        events = self.session.events
        if events:
            candidate = events[0].data.get("branch_id")
            if isinstance(candidate, str) and candidate:
                return candidate
        return getattr(self.session, "session_id", "main")

    def _append_resolution(
        self,
        entry: _LoggedIntent,
        status: Literal["committed", "not_applied", "conflict"],
        current_sha256: str | None,
        current_mode: int | None,
        *,
        recovered: bool,
    ) -> None:
        common = {
            "intent_id": entry.intent.id,
            "path": entry.intent.path,
            "current_sha256": current_sha256,
            "current_mode": current_mode,
            "branch_id": entry.branch_id,
        }
        if status == "committed":
            self.session.append("mutation_committed", recovered=recovered, **common)
        else:
            self.session.append(
                "mutation_recovered", status=status, recovered=recovered, **common
            )

    def _select_checkpoint(
        self,
        checkpoint: Checkpoint | str,
        events: tuple[SessionEvent, ...],
    ) -> tuple[Checkpoint, int]:
        matches: list[tuple[Checkpoint, int]] = []
        for index, event in enumerate(events):
            if event.type != "checkpoint":
                continue
            data = event.data
            value = Checkpoint(
                data.get("checkpoint_id"),
                data.get("name"),
                data.get("event_id"),
                data.get("branch_id"),
            )
            if not all(
                isinstance(item, str) and item
                for item in (value.id, value.name, value.event_id, value.branch_id)
            ):
                raise ValueError("checkpoint event is invalid")
            if event.parent_id != value.event_id:
                raise ValueError("checkpoint boundary does not match the event chain")
            if isinstance(checkpoint, Checkpoint):
                if value == checkpoint:
                    matches.append((value, index))
            elif value.id == checkpoint or value.name == checkpoint:
                matches.append((value, index))
        if not matches:
            raise ValueError("checkpoint is not present in this session")
        return matches[-1]

    @staticmethod
    def _command_warning_after(
        events: tuple[SessionEvent, ...], index: int, branch_id: str
    ) -> str | None:
        command_events: list[SessionEvent] = []
        for event in events[index + 1 :]:
            event_branch = event.data.get("branch_id", branch_id)
            if event_branch != branch_id:
                continue
            if event.type in {"command_started", "command_finished"}:
                command_events.append(event)
            elif event.type == "tool_call" and event.data.get("tool") == "run_command":
                command_events.append(event)
        if not command_events:
            return None
        return (
            "command side effects are not tracked and cannot be undone "
            f"({len(command_events)} audit event(s); latest {command_events[-1].id})"
        )

    def _preflight(self, changes: tuple[PlannedRestore, ...]) -> list[str]:
        conflicts: list[str] = []
        seen: set[str] = set()
        for change in changes:
            if change.path in seen:
                conflicts.append(change.path)
                continue
            seen.add(change.path)
            try:
                current_fingerprint = self._current_fingerprint(
                    change.path,
                    expected_parent=(
                        change.expected_parent_dev,
                        change.expected_parent_ino,
                    ),
                )
            except AgentError:
                conflicts.append(change.path)
                continue
            if current_fingerprint != (
                change.expected_sha256,
                change.expected_mode,
            ):
                conflicts.append(change.path)
            if change.remove:
                if (
                    change.restore_content is not None
                    or change.restore_mode is not None
                ):
                    conflicts.append(change.path)
            elif change.restore_content is None or change.restore_mode is None:
                conflicts.append(change.path)
        return list(dict.fromkeys(conflicts))

    def _remove_exact(
        self,
        raw: str,
        expected_sha256: str,
        expected_mode: int,
        *,
        expected_parent: tuple[int, int],
        quarantine_name: str,
    ) -> None:
        _relative, parent, name = self._open_parent_dir(
            raw, expected_parent=expected_parent
        )
        if (
            Path(quarantine_name).name != quarantine_name
            or not quarantine_name.startswith(".tiny-llm-undo-remove-")
            or not quarantine_name.endswith(".tmp")
        ):
            os.close(parent)
            raise ValueError("retained removal path is invalid")
        quarantine = quarantine_name
        quarantined = False
        quarantine_identity = None
        try:
            current = self._read_regular_at(parent, name, allow_missing=False)
            assert current is not None
            current_content, current_status = current
            if (
                self._digest(current_content),
                stat.S_IMODE(current_status.st_mode),
            ) != (expected_sha256, expected_mode):
                raise AgentError("file changed immediately before removal")
            expected_identity = (current_status.st_dev, current_status.st_ino)
            quarantined = True
            os.rename(
                name,
                quarantine,
                src_dir_fd=parent,
                dst_dir_fd=parent,
            )
            try:
                observed = self._read_regular_at(
                    parent,
                    quarantine,
                    allow_missing=False,
                )
            except AgentError as error:
                self._restore_quarantined_entry(parent, quarantine, name)
                quarantined = False
                raise AgentError(
                    "file changed immediately before removal; "
                    "the quarantined entry was restored or preserved"
                ) from error
            assert observed is not None
            content, status = observed
            quarantine_identity = (status.st_dev, status.st_ino)
            if (
                quarantine_identity != expected_identity
                or self._digest(content) != expected_sha256
                or stat.S_IMODE(status.st_mode) != expected_mode
            ):
                self._restore_quarantined_entry(
                    parent,
                    quarantine,
                    name,
                    expected_identity=quarantine_identity,
                )
                quarantined = False
                raise AgentError(
                    "file changed immediately before removal; "
                    "the substituted entry was not deleted"
                )
            latest = os.stat(quarantine, dir_fd=parent, follow_symlinks=False)
            if (latest.st_dev, latest.st_ino) != (
                status.st_dev,
                status.st_ino,
            ) or stat.S_IMODE(latest.st_mode) != expected_mode:
                self._restore_quarantined_entry(
                    parent,
                    quarantine,
                    name,
                    expected_identity=quarantine_identity,
                )
                quarantined = False
                raise AgentError(
                    "file changed while quarantined for removal; "
                    "the entry was not deleted"
                )
            os.fsync(parent)
            quarantined = False
        except OSError as error:
            raise AgentError("file changed immediately before removal") from error
        finally:
            if quarantined:
                self._restore_quarantined_entry(
                    parent,
                    quarantine,
                    name,
                    expected_identity=quarantine_identity,
                )
            os.close(parent)

    @staticmethod
    def _unlink_internal_if_identity(
        parent: int,
        name: str,
        expected_identity: tuple[int, int],
    ) -> bool:
        """Clean up an internal temp after an inode check.

        This narrows accidental substitution races; it is not an isolation
        boundary against a same-UID process that can guess internal names.
        Public-target quarantines and backups never use this cleanup path.
        """

        try:
            status = os.stat(name, dir_fd=parent, follow_symlinks=False)
        except FileNotFoundError:
            return True
        except OSError:
            return False
        if (status.st_dev, status.st_ino) != expected_identity:
            return False
        try:
            os.unlink(name, dir_fd=parent)
        except OSError:
            return False
        return True

    @staticmethod
    def _restore_quarantined_entry(
        parent: int,
        quarantine: str,
        name: str,
        *,
        expected_identity: tuple[int, int] | None = None,
    ) -> bool:
        """Restore without replacement while retaining quarantine evidence."""

        try:
            source = os.stat(quarantine, dir_fd=parent, follow_symlinks=False)
            source_identity = (source.st_dev, source.st_ino)
            if expected_identity is not None and source_identity != expected_identity:
                return False
            os.link(
                quarantine,
                name,
                src_dir_fd=parent,
                dst_dir_fd=parent,
                follow_symlinks=False,
            )
        except OSError:
            return False
        try:
            restored = os.stat(name, dir_fd=parent, follow_symlinks=False)
            latest_source = os.stat(quarantine, dir_fd=parent, follow_symlinks=False)
            if (restored.st_dev, restored.st_ino) != source_identity or (
                latest_source.st_dev,
                latest_source.st_ino,
            ) != source_identity:
                return False
            os.fsync(parent)
        except OSError:
            return False
        return True

    def _restore_exact(
        self,
        change: PlannedRestore,
        *,
        backup_name: str,
    ) -> None:
        assert change.restore_content is not None
        assert change.restore_mode is not None
        _relative, parent, name = self._open_parent_dir(
            change.path,
            expected_parent=(
                change.expected_parent_dev,
                change.expected_parent_ino,
            ),
        )
        content = change.restore_content.encode("utf-8")
        if len(content) > _MAX_BEFORE_IMAGE_BYTES:
            os.close(parent)
            raise AgentError("restore image is too large")
        if (
            Path(backup_name).name != backup_name
            or not backup_name.startswith(".tiny-llm-undo-backup-")
            or not backup_name.endswith(".tmp")
        ):
            os.close(parent)
            raise ValueError("retained restore path is invalid")
        temporary_name = f".tiny-llm-undo-{uuid.uuid4().hex}.tmp"
        descriptor = None
        temporary_identity = None
        backup_identity = None
        installed = False
        durable_install = False

        def read_expected(
            entry_name: str,
            expected_sha256: str,
            expected_mode: int,
            expected_identity: tuple[int, int] | None = None,
        ) -> tuple[int, int]:
            observed = self._read_regular_at(
                parent,
                entry_name,
                allow_missing=False,
            )
            assert observed is not None
            observed_content, observed_status = observed
            identity = (observed_status.st_dev, observed_status.st_ino)
            if (
                self._digest(observed_content),
                stat.S_IMODE(observed_status.st_mode),
            ) != (expected_sha256, expected_mode) or (
                expected_identity is not None and identity != expected_identity
            ):
                raise AgentError("restore entry changed during installation")
            return identity

        try:
            current_identity = read_expected(
                name,
                change.expected_sha256,
                change.expected_mode,
            )
            descriptor = os.open(
                temporary_name,
                os.O_WRONLY
                | os.O_CREAT
                | os.O_EXCL
                | getattr(os, "O_NOFOLLOW", 0)
                | getattr(os, "O_CLOEXEC", 0),
                0o600,
                dir_fd=parent,
            )
            temporary_status = os.fstat(descriptor)
            temporary_identity = (
                temporary_status.st_dev,
                temporary_status.st_ino,
            )
            with os.fdopen(descriptor, "wb", closefd=False) as file:
                file.write(content)
                os.fchmod(descriptor, change.restore_mode)
                file.flush()
                os.fsync(file.fileno())
            os.close(descriptor)
            descriptor = None
            read_expected(
                temporary_name,
                self._digest(content),
                change.restore_mode,
                temporary_identity,
            )
            read_expected(
                name,
                change.expected_sha256,
                change.expected_mode,
                current_identity,
            )
            backup_identity = current_identity
            os.rename(
                name,
                backup_name,
                src_dir_fd=parent,
                dst_dir_fd=parent,
            )
            moved_status = os.stat(
                backup_name,
                dir_fd=parent,
                follow_symlinks=False,
            )
            moved_identity = (moved_status.st_dev, moved_status.st_ino)
            if moved_identity != backup_identity:
                backup_identity = moved_identity
                self._restore_quarantined_entry(
                    parent,
                    backup_name,
                    name,
                    expected_identity=backup_identity,
                )
                raise AgentError("restore backup changed during quarantine")
            read_expected(
                backup_name,
                change.expected_sha256,
                change.expected_mode,
                current_identity,
            )
            read_expected(
                temporary_name,
                self._digest(content),
                change.restore_mode,
                temporary_identity,
            )
            os.link(
                temporary_name,
                name,
                src_dir_fd=parent,
                dst_dir_fd=parent,
                follow_symlinks=False,
            )
            installed = True
            installed_status = os.stat(name, dir_fd=parent, follow_symlinks=False)
            if (installed_status.st_dev, installed_status.st_ino) != temporary_identity:
                raise AgentError("restore destination was substituted during install")
            if not self._unlink_internal_if_identity(
                parent, temporary_name, temporary_identity
            ):
                raise AgentError("restore temporary was substituted during install")
            read_expected(
                name,
                self._digest(content),
                change.restore_mode,
                temporary_identity,
            )
            os.fsync(parent)
            durable_install = True
        except OSError as error:
            raise AgentError("file changed immediately before restore") from error
        finally:
            try:
                try:
                    if descriptor is not None:
                        os.close(descriptor)
                finally:
                    try:
                        if temporary_identity is not None:
                            self._unlink_internal_if_identity(
                                parent,
                                temporary_name,
                                temporary_identity,
                            )
                    finally:
                        if backup_identity is not None and not installed:
                            self._restore_quarantined_entry(
                                parent,
                                backup_name,
                                name,
                                expected_identity=backup_identity,
                            )
                        elif backup_identity is not None and not durable_install:
                            try:
                                os.fsync(parent)
                            except OSError:
                                pass
            finally:
                os.close(parent)
