# WARNING: Under review - generated by LLM.

import hashlib
import heapq
import os
import signal
import stat
import subprocess
import uuid
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from threading import Event, Thread
from time import monotonic

from .control import AgentInterrupted, CancellationToken
from .protocol import AgentError, ToolAction
from .recovery import MutationJournal, RecoveryResult
from .session import SessionLog


_PROTECTED_NAMES = frozenset(
    {
        ".env",
        ".aws",
        ".azure",
        ".docker",
        ".git",
        ".gnupg",
        ".kube",
        ".netrc",
        ".npmrc",
        ".pypirc",
        ".ssh",
        ".tiny-llm",
        "id_rsa",
        "id_ed25519",
    }
)


def _protected_path_reason(parts: tuple[str, ...]) -> str | None:
    """Describe why path components cross a protected metadata or secret path."""

    for part in parts:
        lower = part.lower()
        if lower == ".git":
            return ".git is not accessible"
        if (
            lower in _PROTECTED_NAMES
            or lower.startswith(".env.")
            or lower.startswith(".tiny-llm-agent-")
            or lower.startswith(".tiny-llm-undo-")
        ):
            return "potential secret files are not accessible"
        if lower.endswith((".pem", ".key")):
            return "potential key files are not accessible"
    return None


@dataclass(frozen=True)
class _PreparedWrite:
    """A validated write and the file state it is allowed to replace."""

    path: Path
    content: bytes
    expected_digest: bytes | None
    expected_mode: int | None
    after_mode: int
    parent_identity: tuple[int, int]


@dataclass(frozen=True)
class ToolPolicy:
    """Week 4, Day 3: filesystem and command boundaries for one workspace."""

    root: Path
    allow_writes: bool = False
    allowed_commands: tuple[tuple[str, ...], ...] = ()
    max_file_bytes: int = 64 * 1024
    max_write_bytes: int = 64 * 1024
    max_list_entries: int = 200
    max_tool_output_chars: int = 16_000
    command_timeout_seconds: float = 30.0
    _root_identity: tuple[int, int] = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        """Week 4, Day 3: normalize the root and reject invalid limits."""

        root = self.root.resolve()
        object.__setattr__(self, "root", root)
        numeric_limits = (
            self.max_file_bytes,
            self.max_write_bytes,
            self.max_list_entries,
            self.max_tool_output_chars,
            self.command_timeout_seconds,
        )
        if any(limit <= 0 for limit in numeric_limits):
            raise ValueError("tool policy limits must be positive")
        if not root.exists() or not root.is_dir():
            raise ValueError("workspace root must be an existing directory")
        root_status = os.stat(root, follow_symlinks=False)
        if not stat.S_ISDIR(root_status.st_mode):
            raise ValueError("workspace root must be a directory")
        object.__setattr__(
            self,
            "_root_identity",
            (root_status.st_dev, root_status.st_ino),
        )
        home = Path.home().resolve()
        if root.parent == root or root == home or root in home.parents:
            raise ValueError("workspace root is too broad")
        if reason := _protected_path_reason(root.parts):
            raise ValueError(f"workspace root is protected: {reason}")
        for command in self.allowed_commands:
            if not command or any(
                not isinstance(part, str) or not part or "\x00" in part
                for part in command
            ):
                raise ValueError("allowed commands must contain non-empty arguments")


@dataclass
class Workspace:
    """Week 4, Days 3--6: bounded tools over one explicit workspace root."""

    policy: ToolPolicy
    confirm_tool: Callable[[ToolAction], bool] | None = None
    session_log: SessionLog | None = field(default=None, kw_only=True)
    cancellation: CancellationToken | None = field(default=None, kw_only=True)
    observed_files: dict[Path, bytes] = field(default_factory=dict, init=False)
    modified_files: set[Path] = field(default_factory=set, init=False)
    uncertain_modified_files: set[Path] = field(default_factory=set, init=False)
    retained_recovery_files: set[Path] = field(default_factory=set, init=False)
    command_side_effects_untracked: bool = field(default=False, init=False)
    command_cleanup_incomplete: bool = field(default=False, init=False)
    journal: MutationJournal | None = field(default=None, init=False)
    recovery_results: tuple[RecoveryResult, ...] = field(default=(), init=False)

    def __post_init__(self) -> None:
        """Bind durable mutation recovery to the matching session, when present."""

        if self.session_log is not None:
            self.journal = MutationJournal(self.session_log, self.policy.root)
            self.recover_pending()
            self._recover_command_state()

    def bind_session(self, session_log: SessionLog) -> tuple[RecoveryResult, ...]:
        """Bind a pristine workspace to the exact log used by its agent loop."""

        if session_log.workspace != self.policy.root:
            raise ValueError("session belongs to a different workspace")
        if self.session_log is not None:
            if self.session_log is not session_log:
                raise ValueError("workspace journal belongs to a different session")
            if self.journal is None or self.journal.session is not session_log:
                raise ValueError("workspace journal is not bound to its session")
            self._recover_command_state()
            return ()
        if self.journal is not None:
            raise ValueError("workspace has a journal without a session")
        if (
            self.modified_files
            or self.uncertain_modified_files
            or self.retained_recovery_files
            or self.command_side_effects_untracked
        ):
            raise ValueError("workspace has unjournaled side effects")

        journal = MutationJournal(session_log, self.policy.root)
        recovered = journal.recover_pending()
        self.session_log = session_log
        self.journal = journal
        self.recovery_results += recovered
        self._recover_command_state()
        return recovered

    def _recover_command_state(self) -> None:
        """Reconstruct conservative process-side-effect flags from durable events."""

        if self.session_log is None:
            return
        starts: dict[str, object] = {}
        finishes: dict[str, object] = {}
        for event in self.session_log.events:
            if event.type == "command_started":
                command_id = event.data.get("command_id")
                if not isinstance(command_id, str) or command_id in starts:
                    raise ValueError("command start event is invalid")
                starts[command_id] = event
            elif event.type == "command_finished":
                command_id = event.data.get("command_id")
                if (
                    not isinstance(command_id, str)
                    or command_id not in starts
                    or command_id in finishes
                ):
                    raise ValueError("command finish event is invalid")
                finishes[command_id] = event
        for command_id in starts:
            finished = finishes.get(command_id)
            if finished is None:
                self.command_side_effects_untracked = True
                self.command_cleanup_incomplete = True
                continue
            launched = finished.data.get("launched")
            cleanup_incomplete = finished.data.get("cleanup_incomplete")
            if not isinstance(launched, bool) or not isinstance(
                cleanup_incomplete, bool
            ):
                raise ValueError("command finish event is invalid")
            if launched:
                self.command_side_effects_untracked = True
            if cleanup_incomplete:
                self.command_cleanup_incomplete = True

    @property
    def mutation_journal(self) -> MutationJournal | None:
        """Expose the session-bound journal under a descriptive alias."""

        return self.journal

    def recover_pending(self) -> tuple[RecoveryResult, ...]:
        """Classify pending durable intents without changing workspace files."""

        if self.journal is None:
            return ()
        results = self.journal.recover_pending()
        self.recovery_results += results
        return results

    @property
    def available_tools(self) -> frozenset[str]:
        """Week 4, Day 3: expose only tools enabled by operator policy."""

        tools = {"list_files", "read_file"}
        if self.policy.allow_writes:
            tools.update({"write_file", "edit_file"})
        if self.policy.allowed_commands:
            tools.add("run_command")
        return frozenset(tools)

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Week 4, Day 3: reject escapes, protected files, and symlink traversal."""

        if not isinstance(raw, str) or not raw or "\x00" in raw:
            raise AgentError("path must be a non-empty string")
        unresolved = Path(raw)
        if unresolved.is_absolute():
            raise AgentError("absolute paths are not allowed")
        if ".." in unresolved.parts:
            raise AgentError("parent path components are not allowed")
        current = self.policy.root
        for part in unresolved.parts:
            current /= part
            if current.is_symlink():
                raise AgentError("symlinks are not accessible")
        path = (self.policy.root / unresolved).resolve(strict=False)
        try:
            relative = path.relative_to(self.policy.root)
        except ValueError as error:
            raise AgentError("path leaves the workspace") from error
        self._reject_protected(relative)

        if must_exist and not path.exists():
            raise AgentError(f"path does not exist: {relative}")
        return path

    def _reject_protected(self, relative: Path) -> None:
        """Week 4, Day 3: keep repository metadata and common secrets hidden."""

        if reason := _protected_path_reason(relative.parts):
            raise AgentError(reason)

    def list_files(self, raw: str = ".") -> str:
        """Week 4, Day 3: list one directory without following symlinks."""

        path = self.resolve_path(raw)
        if not path.is_dir():
            raise AgentError("list_files path must be a directory")
        lines: list[str] = []
        items = heapq.nsmallest(
            self.policy.max_list_entries,
            path.iterdir(),
            key=lambda entry: entry.name,
        )
        for item in items:
            if item.is_symlink():
                continue
            try:
                relative = item.relative_to(self.policy.root)
                self._reject_protected(relative)
            except AgentError:
                continue
            kind = "dir" if item.is_dir() else "file"
            lines.append(f"{kind} {relative}")
            if len(lines) == self.policy.max_list_entries:
                break
        return "\n".join(lines)

    def read_file(self, raw: str) -> str:
        """Week 4, Day 3: read one bounded UTF-8 regular file."""

        path = self.resolve_path(raw)
        data = self._read_bounded_file(path, tool="read_file")
        content = data.decode("utf-8")
        self.observed_files[path] = self._digest(data)
        return content

    def write_file(self, raw: str, content: str) -> str:
        """Week 4, Day 3: atomically create or replace an inspected file."""

        prepared = self._prepare_write(raw, content)
        return self._commit_write(prepared)

    def _prepare_write(self, raw: str, content: str) -> _PreparedWrite:
        """Validate a write completely before asking for operator approval."""

        if not self.policy.allow_writes:
            raise AgentError("writes are disabled; restart with --allow-writes")
        encoded = content.encode("utf-8")
        if len(encoded) > self.policy.max_write_bytes:
            raise AgentError(f"content exceeds {self.policy.max_write_bytes} bytes")
        path = self.resolve_path(raw, must_exist=False)
        relative = path.relative_to(self.policy.root)
        expected_digest = self.observed_files.get(path)
        parent, name = self._open_parent_directory(relative)
        try:
            parent_status = os.fstat(parent)
            current = self._read_regular_at(parent, name, tool="write_file")
        finally:
            os.close(parent)
        if current is None:
            if expected_digest is not None:
                raise AgentError("file changed since it was read; read it again")
            expected_mode = None
            after_mode = 0o600
        else:
            if expected_digest is None:
                raise AgentError(
                    "existing files must be read before they are overwritten"
                )
            current_content, current_status = current
            if self._digest(current_content) != expected_digest:
                raise AgentError("file changed since it was read; read it again")
            expected_mode = stat.S_IMODE(current_status.st_mode)
            after_mode = expected_mode & 0o777
        return _PreparedWrite(
            path,
            encoded,
            expected_digest,
            expected_mode,
            after_mode,
            (parent_status.st_dev, parent_status.st_ino),
        )

    def _commit_write(self, prepared: _PreparedWrite) -> str:
        """Revalidate and commit one previously prepared write."""

        relative = prepared.path.relative_to(self.policy.root)
        path = prepared.path
        self._revalidate_prepared_write(prepared)
        journal = self.journal
        intent = None
        if journal is not None:
            intent = journal.record_intent(
                relative.as_posix(),
                prepared.content.decode("utf-8"),
                after_mode=prepared.after_mode,
            )
            expected_sha256 = (
                None
                if prepared.expected_digest is None
                else prepared.expected_digest.hex()
            )
            if (
                intent.before_sha256 != expected_sha256
                or intent.before_mode != prepared.expected_mode
                or intent.after_mode != prepared.after_mode
            ):
                self.recover_pending()
                raise AgentError("file changed since it was read; read it again")
        self._raise_if_cancelled("file_mutation")
        self.uncertain_modified_files.add(path)
        self._atomic_write(
            path,
            prepared.content,
            expected_digest=prepared.expected_digest,
            expected_mode=prepared.expected_mode,
            after_mode=prepared.after_mode,
            parent_identity=prepared.parent_identity,
        )
        if journal is not None and intent is not None:
            journal.commit(intent)
        self.observed_files[path] = self._digest(prepared.content)
        self.modified_files.add(path)
        self.uncertain_modified_files.discard(path)
        return f"wrote {relative}"

    def edit_file(self, raw: str, old: str, new: str) -> str:
        """Week 4, Day 5: make one exact, reviewable replacement in a read file."""

        prepared = self._prepare_edit(raw, old, new)
        return self._commit_write(prepared)

    def _prepare_edit(self, raw: str, old: str, new: str) -> _PreparedWrite:
        """Validate and compute an edit without changing the workspace."""

        if not self.policy.allow_writes:
            raise AgentError("writes are disabled; restart with --allow-writes")
        path = self.resolve_path(raw)
        if path not in self.observed_files:
            raise AgentError("files must be read before they are edited")
        if not old:
            raise AgentError("old text must not be empty")
        data = self._read_bounded_file(path, tool="edit_file")
        if self._digest(data) != self.observed_files[path]:
            raise AgentError("file changed since it was read; read it again")
        content = data.decode("utf-8")
        matches = content.count(old)
        if matches != 1:
            raise AgentError(f"old text must match exactly once; found {matches}")
        return self._prepare_write(raw, content.replace(old, new, 1))

    def run_command(self, argv: list[str]) -> str:
        """Week 4, Day 5: run only an operator-approved exact argv without a shell."""

        command = self._prepare_command(argv)
        result, _ = self._run_command(command)
        return result

    def _prepare_command(self, argv: list[str]) -> tuple[str, ...]:
        """Validate an exact command without starting a process."""

        command = tuple(argv)
        if command not in self.policy.allowed_commands:
            raise AgentError("command was not explicitly allowed by the operator")
        return command

    def _run_command(self, argv: tuple[str, ...]) -> tuple[str, tuple[str, ...]]:
        """Execute one previously validated command."""

        environment = {
            name: value
            for name in ("PATH", "LANG", "LC_ALL", "TMPDIR")
            if (value := os.environ.get(name)) is not None
        }
        process = None
        cleaned_up = False
        command_id = uuid.uuid4().hex
        prior_command_side_effects = self.command_side_effects_untracked

        def clean_up() -> None:
            """Kill this command group at most once after it has started."""

            nonlocal cleaned_up
            if process is not None and not cleaned_up:
                self.command_side_effects_untracked = True
                cleaned_up = True
                self._kill_and_reap(process)

        try:
            self._raise_if_cancelled("command")
            if self.session_log is not None:
                self.session_log.append(
                    "command_started",
                    command_id=command_id,
                    argv=list(argv),
                )
            try:
                self._raise_if_cancelled("command")
            except AgentInterrupted:
                if self.session_log is not None:
                    self.session_log.append(
                        "command_finished",
                        command_id=command_id,
                        returncode=130,
                        launched=False,
                        cleanup_incomplete=False,
                    )
                raise
            self.command_side_effects_untracked = True

            def launch():
                return subprocess.Popen(
                    argv,
                    cwd=self.policy.root,
                    env=environment,
                    shell=False,
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    start_new_session=True,
                    bufsize=0,
                )

            try:
                process = (
                    self.cancellation.run_if_active("command", launch)
                    if self.cancellation is not None
                    else launch()
                )
            except AgentInterrupted:
                self.command_side_effects_untracked = prior_command_side_effects
                if self.session_log is not None:
                    self.session_log.append(
                        "command_finished",
                        command_id=command_id,
                        returncode=130,
                        launched=False,
                        cleanup_incomplete=False,
                    )
                raise
            except BaseException:
                self.command_cleanup_incomplete = True
                raise
            assert process.stdout is not None
            captured = bytearray()
            output_truncated = Event()
            output_read_failed = Event()
            output_abandoned = False

            def drain_output() -> None:
                """Drain output without retaining unbounded bytes."""

                try:
                    while chunk := process.stdout.read(4096):
                        remaining = self.policy.max_tool_output_chars - len(captured)
                        if remaining > 0:
                            captured.extend(chunk[:remaining])
                        if len(chunk) > remaining:
                            output_truncated.set()
                except (OSError, ValueError):
                    self.command_cleanup_incomplete = True
                    output_read_failed.set()

            reader = Thread(target=drain_output, daemon=True)
            reader.start()
            try:
                if self.cancellation is None:
                    returncode = process.wait(
                        timeout=self.policy.command_timeout_seconds
                    )
                else:
                    deadline = monotonic() + self.policy.command_timeout_seconds
                    while True:
                        self._raise_if_cancelled("command")
                        remaining = deadline - monotonic()
                        if remaining <= 0:
                            raise subprocess.TimeoutExpired(
                                argv, self.policy.command_timeout_seconds
                            )
                        try:
                            returncode = process.wait(timeout=min(0.1, remaining))
                            break
                        except subprocess.TimeoutExpired:
                            self._raise_if_cancelled("command")
            except subprocess.TimeoutExpired as error:
                clean_up()
                raise AgentError(
                    f"command exceeded {self.policy.command_timeout_seconds:g} seconds"
                ) from error
            except AgentInterrupted:
                clean_up()
                raise
            except KeyboardInterrupt:
                clean_up()
                raise
            finally:
                reader.join(timeout=0.05)
                if reader.is_alive():
                    clean_up()
                    reader.join(timeout=1)
                    if reader.is_alive():
                        output_abandoned = True
                        self.command_cleanup_incomplete = True
                        try:
                            process.stdout.close()
                        except (OSError, ValueError):
                            pass
                        reader.join(timeout=0.1)
        except (AgentError, AgentInterrupted):
            clean_up()
            raise
        except Exception as error:
            clean_up()
            if process is None:
                raise
            raise AgentError(
                f"command runner failed after starting: {error}"
            ) from error
        except BaseException:
            clean_up()
            raise
        finally:
            if process is not None and process.stdout is not None:
                try:
                    process.stdout.close()
                except (OSError, ValueError):
                    pass

        output = bytes(captured).decode("utf-8", errors="replace")
        markers = []
        trusted_warnings = []
        if output_truncated.is_set():
            markers.append("... command output truncated")
        if output_read_failed.is_set():
            self.command_cleanup_incomplete = True
            warning = "command output collection failed"
            markers.append(f"... {warning}")
            trusted_warnings.append(warning)
        if output_abandoned:
            warning = "command output abandoned; a descendant may retain the pipe"
            markers.append(f"... {warning}")
            trusted_warnings.append(warning)
        output = "\n".join(part for part in (output, *markers) if part)
        if self.session_log is not None:
            self.session_log.append(
                "command_finished",
                command_id=command_id,
                returncode=returncode,
                launched=True,
                cleanup_incomplete=self.command_cleanup_incomplete,
            )
        return f"exit code: {returncode}\n{output}".rstrip(), tuple(trusted_warnings)

    def _kill_and_reap(self, process) -> bool:
        """Attempt bounded process-group termination and foreground reaping."""

        try:
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            except (OSError, AttributeError):
                self.command_cleanup_incomplete = True
                try:
                    process.kill()
                except OSError:
                    pass
        except BaseException:
            self.command_cleanup_incomplete = True
            raise
        try:
            process.wait(timeout=1)
        except (OSError, subprocess.TimeoutExpired):
            self.command_cleanup_incomplete = True
            return False
        except BaseException:
            self.command_cleanup_incomplete = True
            raise
        return True

    def _require_confirmation(self, action: ToolAction) -> None:
        """Default-deny one model-requested side effect."""

        if self.confirm_tool is None or not self.confirm_tool(action):
            raise AgentError(f"operator denied {action.tool}")

    def _raise_if_cancelled(self, phase: str) -> None:
        """Observe a cooperative cancellation token at a safe boundary."""

        if self.cancellation is not None:
            self.cancellation.raise_if_cancelled(phase)

    def execute(self, action: ToolAction) -> str:
        """Week 4, Day 3: dispatch a validated action and return recoverable errors."""

        self._raise_if_cancelled("tool")
        preserve_command_warnings: tuple[str, ...] = ()
        try:
            if action.tool == "list_files":
                result = self.list_files(action.arguments.get("path", "."))
            elif action.tool == "read_file":
                result = self.read_file(action.arguments["path"])
            elif action.tool == "write_file":
                prepared = self._prepare_write(
                    action.arguments["path"], action.arguments["content"]
                )
                self._require_confirmation(action)
                result = self._commit_write(prepared)
            elif action.tool == "edit_file":
                prepared = self._prepare_edit(
                    action.arguments["path"],
                    action.arguments["old"],
                    action.arguments["new"],
                )
                self._require_confirmation(action)
                result = self._commit_write(prepared)
            elif action.tool == "run_command":
                command = self._prepare_command(action.arguments["argv"])
                self._require_confirmation(action)
                result, preserve_command_warnings = self._run_command(command)
            else:
                raise AgentError(f"unknown tool: {action.tool}")
        except (
            KeyError,
            OSError,
            subprocess.SubprocessError,
            ValueError,
        ) as error:
            result = f"error: {error}"
        return self._truncate_result(
            result,
            preserve_command_warnings=preserve_command_warnings,
        )

    def _truncate_result(
        self,
        result: str,
        *,
        preserve_command_warnings: tuple[str, ...] = (),
    ) -> str:
        """Bound a result while preserving trusted command-safety warnings."""

        limit = self.policy.max_tool_output_chars
        if len(result) <= limit:
            return result
        marker = "\n... tool output truncated"
        safety = "".join(
            f"\nwarning: {warning}" for warning in preserve_command_warnings
        )
        suffix = marker + safety
        if len(suffix) >= limit:
            if preserve_command_warnings:
                return safety.lstrip()[:limit]
            return result[:limit]
        return result[: limit - len(suffix)] + suffix

    def _open_parent_directory(self, relative: Path) -> tuple[int, str]:
        """Open every parent below the approved root without following links."""

        if relative.is_absolute() or not relative.parts or ".." in relative.parts:
            raise AgentError("write path must stay below the workspace")
        flags = (
            os.O_RDONLY
            | getattr(os, "O_DIRECTORY", 0)
            | getattr(os, "O_NOFOLLOW", 0)
            | getattr(os, "O_CLOEXEC", 0)
        )
        try:
            directory = os.open(self.policy.root, flags)
        except OSError as error:
            raise AgentError("workspace root changed or is unsafe") from error
        try:
            root_status = os.fstat(directory)
            if (
                not stat.S_ISDIR(root_status.st_mode)
                or (root_status.st_dev, root_status.st_ino)
                != self.policy._root_identity
            ):
                raise AgentError("workspace root changed or is unsafe")
            for component in relative.parts[:-1]:
                try:
                    child = os.open(component, flags, dir_fd=directory)
                except OSError as error:
                    raise AgentError("write parent changed or is unsafe") from error
                os.close(directory)
                directory = child
                if not stat.S_ISDIR(os.fstat(directory).st_mode):
                    raise AgentError("write parent changed or is unsafe")
            return directory, relative.name
        except BaseException:
            os.close(directory)
            raise

    def _read_regular_at(
        self,
        parent: int,
        name: str,
        *,
        tool: str,
    ) -> tuple[bytes, os.stat_result] | None:
        """Read and identify one final component relative to an anchored parent."""

        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_CLOEXEC", 0)
        try:
            descriptor = os.open(name, flags, dir_fd=parent)
        except FileNotFoundError:
            return None
        except OSError as error:
            raise AgentError(f"{tool} path must be a safe regular file") from error
        try:
            opened = os.fstat(descriptor)
            if (
                not stat.S_ISREG(opened.st_mode)
                or opened.st_nlink != 1
                or opened.st_size > self.policy.max_file_bytes
            ):
                raise AgentError(f"{tool} path must be a safe regular file")
            with os.fdopen(descriptor, "rb", closefd=False) as file:
                content = file.read(self.policy.max_file_bytes + 1)
            if len(content) > self.policy.max_file_bytes:
                raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
            latest_opened = os.fstat(descriptor)
            try:
                named = os.stat(name, dir_fd=parent, follow_symlinks=False)
            except FileNotFoundError as error:
                raise AgentError("file changed while it was inspected") from error
            if (
                not stat.S_ISREG(named.st_mode)
                or named.st_nlink != 1
                or (named.st_dev, named.st_ino) != (opened.st_dev, opened.st_ino)
                or stat.S_IMODE(named.st_mode) != stat.S_IMODE(opened.st_mode)
                or (
                    latest_opened.st_size,
                    latest_opened.st_mtime_ns,
                    latest_opened.st_ctime_ns,
                )
                != (opened.st_size, opened.st_mtime_ns, opened.st_ctime_ns)
                or (
                    named.st_size,
                    named.st_mtime_ns,
                    named.st_ctime_ns,
                )
                != (
                    latest_opened.st_size,
                    latest_opened.st_mtime_ns,
                    latest_opened.st_ctime_ns,
                )
            ):
                raise AgentError("file changed while it was inspected")
            return content, opened
        finally:
            os.close(descriptor)

    def _revalidate_prepared_write(self, prepared: _PreparedWrite) -> None:
        """Recheck an approved target and parent before journaling its intent."""

        relative = prepared.path.relative_to(self.policy.root)
        try:
            parent, name = self._open_parent_directory(relative)
            try:
                parent_status = os.fstat(parent)
                if (
                    parent_status.st_dev,
                    parent_status.st_ino,
                ) != prepared.parent_identity:
                    raise AgentError("file changed since it was read; read it again")
                current = self._read_regular_at(parent, name, tool="write_file")
            finally:
                os.close(parent)
        except AgentError as error:
            raise AgentError("file changed since it was read; read it again") from error
        if prepared.expected_digest is None:
            if current is not None:
                raise AgentError("write target appeared after approval; read it first")
            return
        if current is None:
            raise AgentError("file changed since it was read; read it again")
        content, status = current
        if (
            self._digest(content) != prepared.expected_digest
            or stat.S_IMODE(status.st_mode) != prepared.expected_mode
        ):
            raise AgentError("file changed since it was read; read it again")

    def _read_bounded_file(self, path: Path, *, tool: str) -> bytes:
        """Read a regular file without accepting a changed type or unbounded size."""

        if path.is_symlink() or not path.is_file():
            raise AgentError(f"{tool} path must be a regular file")
        with path.open("rb") as file:
            data = file.read(self.policy.max_file_bytes + 1)
        if len(data) > self.policy.max_file_bytes:
            raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
        return data

    @staticmethod
    def _digest(content: bytes) -> bytes:
        """Fingerprint observed bytes for stale-write detection."""

        return hashlib.sha256(content).digest()

    def _atomic_write(
        self,
        path: Path,
        content: bytes,
        *,
        expected_digest: bytes | None,
        expected_mode: int | None,
        after_mode: int,
        parent_identity: tuple[int, int],
    ) -> None:
        """Week 4, Day 3: replace a file without exposing a partial write."""

        relative = path.relative_to(self.policy.root)
        parent, name = self._open_parent_directory(relative)
        temporary_name = f".tiny-llm-agent-{uuid.uuid4().hex}.tmp"
        backup_name: str | None = None
        descriptor = None
        temporary_identity: tuple[int, int] | None = None
        installed = False
        succeeded = False

        def discard_private(private_name: str, identity: tuple[int, int]) -> bool:
            """Best-effort cleanup of one unguessable internal entry."""

            try:
                named = os.stat(
                    private_name,
                    dir_fd=parent,
                    follow_symlinks=False,
                )
            except FileNotFoundError:
                return True
            except OSError:
                return False
            if (named.st_dev, named.st_ino) != identity:
                return False
            try:
                os.unlink(private_name, dir_fd=parent)
            except (FileNotFoundError, OSError):
                return False
            return True

        def restore_backup() -> None:
            """Relink without replacing and retain the backup as a safety copy."""

            if backup_name is None:
                return
            try:
                os.link(
                    backup_name,
                    name,
                    src_dir_fd=parent,
                    dst_dir_fd=parent,
                    follow_symlinks=False,
                )
            except (FileExistsError, FileNotFoundError):
                return

        def quarantine_failed_install() -> None:
            """Move a public entry aside; never check-then-unlink that name."""

            if temporary_identity is None:
                return
            quarantine = f".tiny-llm-agent-{uuid.uuid4().hex}.failed"
            self.retained_recovery_files.add(path.parent / quarantine)
            try:
                os.replace(name, quarantine, src_dir_fd=parent, dst_dir_fd=parent)
            except FileNotFoundError:
                return
            try:
                held = os.open(
                    quarantine,
                    os.O_RDONLY
                    | getattr(os, "O_NOFOLLOW", 0)
                    | getattr(os, "O_CLOEXEC", 0),
                    dir_fd=parent,
                )
                try:
                    moved = os.fstat(held)
                    moved_identity = (moved.st_dev, moved.st_ino)
                finally:
                    os.close(held)
            except OSError:
                return
            if moved_identity == temporary_identity:
                return
            try:
                os.link(
                    quarantine,
                    name,
                    src_dir_fd=parent,
                    dst_dir_fd=parent,
                    follow_symlinks=False,
                )
            except FileExistsError:
                pass

        try:
            parent_status = os.fstat(parent)
            if (parent_status.st_dev, parent_status.st_ino) != parent_identity:
                raise AgentError("file changed since it was read; read it again")

            def revalidate_target() -> None:
                current = self._read_regular_at(parent, name, tool="write_file")
                if expected_digest is None:
                    if current is not None:
                        raise AgentError(
                            "write target appeared after approval; read it first"
                        )
                    return
                if current is None:
                    raise AgentError("file changed since it was read; read it again")
                current_content, current_status = current
                if (
                    self._digest(current_content) != expected_digest
                    or stat.S_IMODE(current_status.st_mode) != expected_mode
                ):
                    raise AgentError("file changed since it was read; read it again")

            revalidate_target()
            descriptor = os.open(
                temporary_name,
                os.O_WRONLY
                | os.O_CREAT
                | os.O_EXCL
                | getattr(os, "O_NOFOLLOW", 0)
                | getattr(os, "O_CLOEXEC", 0),
                0o600,
                dir_fd=parent,
            )
            with os.fdopen(descriptor, "wb", closefd=False) as file:
                file.write(content)
                os.fchmod(descriptor, after_mode)
                file.flush()
                os.fsync(file.fileno())
            temporary_status = os.fstat(descriptor)
            temporary_identity = (
                temporary_status.st_dev,
                temporary_status.st_ino,
            )
            os.close(descriptor)
            descriptor = None
            revalidate_target()
            if expected_digest is not None:
                backup_name = f".tiny-llm-agent-{uuid.uuid4().hex}.bak"
                # Register the reserved evidence path before the rename so an
                # asynchronous BaseException cannot make a real backup silent.
                self.retained_recovery_files.add(path.parent / backup_name)
                os.replace(name, backup_name, src_dir_fd=parent, dst_dir_fd=parent)
                moved = self._read_regular_at(parent, backup_name, tool="write_file")
                if moved is None or (
                    self._digest(moved[0]),
                    stat.S_IMODE(moved[1].st_mode),
                ) != (expected_digest, expected_mode):
                    restore_backup()
                    raise AgentError("file changed since it was read; read it again")
            os.link(
                temporary_name,
                name,
                src_dir_fd=parent,
                dst_dir_fd=parent,
                follow_symlinks=False,
            )
            installed = True
            if temporary_identity is None or not discard_private(
                temporary_name, temporary_identity
            ):
                raise AgentError("could not safely clean up the temporary write")
            replaced = self._read_regular_at(parent, name, tool="write_file")
            if replaced is None or (
                self._digest(replaced[0]),
                stat.S_IMODE(replaced[1].st_mode),
            ) != (self._digest(content), after_mode):
                raise AgentError("atomic write result failed verification")
            os.fsync(parent)
            succeeded = True
            # Keep the old inode as an internal backup. A normal editor may
            # still hold a writable descriptor opened before the rename; no
            # portable unlink-if-inode operation can prove it did not append
            # new bytes after our last fingerprint check.
        finally:
            try:
                if descriptor is not None:
                    try:
                        if temporary_identity is None:
                            try:
                                temporary_status = os.fstat(descriptor)
                                temporary_identity = (
                                    temporary_status.st_dev,
                                    temporary_status.st_ino,
                                )
                            except OSError:
                                pass
                    finally:
                        os.close(descriptor)
            finally:
                try:
                    if not succeeded and installed:
                        try:
                            quarantine_failed_install()
                        finally:
                            restore_backup()
                    elif not succeeded:
                        restore_backup()
                finally:
                    try:
                        if temporary_identity is not None and not discard_private(
                            temporary_name, temporary_identity
                        ):
                            self.retained_recovery_files.add(
                                path.parent / temporary_name
                            )
                    finally:
                        try:
                            os.fsync(parent)
                        except OSError:
                            pass
                        finally:
                            os.close(parent)
