# WARNING: Under review - generated by LLM.

"""Week 4, Day 2: small read-only tools for a disposable workspace.

This module teaches the model-to-tool loop. It is a path boundary for a trusted
operator, not a sandbox or a defense against a hostile filesystem.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .protocol import AgentError, ToolAction

_PROTECTED_NAMES = frozenset(
    {".aws", ".env", ".git", ".ssh", "credentials", "id_ed25519", "id_rsa"}
)


def _is_protected(path: Path) -> bool:
    return any(
        part.lower() in _PROTECTED_NAMES
        or part.lower().startswith(".env.")
        or part.lower().endswith((".key", ".pem"))
        for part in path.parts
    )


@dataclass(frozen=True)
class ToolPolicy:
    """Read limits for one explicit workspace root."""

    root: Path
    max_file_bytes: int = 64 * 1024
    max_list_entries: int = 200

    def __post_init__(self) -> None:
        root = Path(self.root)
        if root.is_symlink():
            raise ValueError("workspace root must not be a symlink")
        try:
            root = root.resolve(strict=True)
        except OSError as error:
            raise ValueError("workspace root must exist") from error
        if not root.is_dir():
            raise ValueError("workspace root must be a directory")
        if (
            type(self.max_file_bytes) is not int
            or type(self.max_list_entries) is not int
            or self.max_file_bytes <= 0
            or self.max_list_entries <= 0
        ):
            raise ValueError("workspace limits must be positive integers")
        object.__setattr__(self, "root", root)


@dataclass
class Workspace:
    """List and read files under one policy-bound root."""

    policy: ToolPolicy

    @property
    def available_tools(self) -> frozenset[str]:
        return frozenset({"list_files", "read_file"})

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Resolve one relative path without traversal or symlinks."""

        if not isinstance(raw, str) or not raw.strip():
            raise AgentError("path must be a non-empty string")
        relative = Path(raw)
        if relative.is_absolute() or ".." in relative.parts:
            raise AgentError("path must be relative and stay in the workspace")
        if _is_protected(relative):
            raise AgentError("path is not accessible")

        current = self.policy.root
        for part in relative.parts:
            current /= part
            if current.is_symlink():
                raise AgentError("symlinks are not accessible")
        try:
            resolved = current.resolve(strict=must_exist)
            resolved.relative_to(self.policy.root)
        except (OSError, RuntimeError, ValueError) as error:
            raise AgentError("path is not accessible") from error
        return resolved

    def list_files(self, raw: str = ".") -> str:
        """List one directory, bounded by the policy."""

        path = self.resolve_path(raw)
        if not path.is_dir():
            raise AgentError("path is not a directory")
        try:
            children = sorted(path.iterdir(), key=lambda child: child.name)
        except OSError as error:
            raise AgentError(f"could not list path: {error}") from error

        lines: list[str] = []
        for child in children:
            relative = child.relative_to(self.policy.root)
            if child.is_symlink() or _is_protected(relative):
                continue
            kind = "dir" if child.is_dir() else "file" if child.is_file() else None
            if kind is not None:
                lines.append(f"{kind} {relative.as_posix()}")
            if len(lines) == self.policy.max_list_entries:
                break
        return "\n".join(lines) if lines else "(empty directory)"

    def read_file(self, raw: str) -> str:
        """Read one bounded UTF-8 regular file."""

        path = self.resolve_path(raw)
        if not path.is_file():
            raise AgentError("path is not a regular file")
        try:
            if path.stat().st_size > self.policy.max_file_bytes:
                raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
            data = path.read_bytes()
        except AgentError:
            raise
        except OSError as error:
            raise AgentError(f"could not read file: {error}") from error
        if len(data) > self.policy.max_file_bytes:
            raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
        try:
            return data.decode("utf-8")
        except UnicodeDecodeError as error:
            raise AgentError("file is not valid UTF-8") from error

    def execute(self, action: ToolAction) -> str:
        """Dispatch one enabled read-only action as a model observation."""

        try:
            if action.tool == "list_files":
                return self.list_files(action.arguments.get("path", "."))
            if action.tool == "read_file":
                return self.read_file(action.arguments["path"])
            raise AgentError(f"tool is not enabled: {action.tool}")
        except (AgentError, KeyError, TypeError) as error:
            return f"error: {error}"
