# WARNING: Under review - generated by LLM.

import hashlib
import heapq
import os
import signal
import stat
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from threading import Event, Thread

from .protocol import AgentError, ToolAction


_PROTECTED_NAMES = frozenset(
    {
        ".env",
        ".aws",
        ".azure",
        ".docker",
        ".git",
        ".gnupg",
        ".kube",
        ".netrc",
        ".npmrc",
        ".pypirc",
        ".ssh",
        "id_rsa",
        "id_ed25519",
    }
)


def _protected_path_reason(parts: tuple[str, ...]) -> str | None:
    """Describe why path components cross a protected metadata or secret path."""

    for part in parts:
        lower = part.lower()
        if lower == ".git":
            return ".git is not accessible"
        if lower in _PROTECTED_NAMES or lower.startswith(".env."):
            return "potential secret files are not accessible"
        if lower.endswith((".pem", ".key")):
            return "potential key files are not accessible"
    return None


@dataclass(frozen=True)
class _PreparedWrite:
    """A validated write and the file state it is allowed to replace."""

    path: Path
    content: bytes
    expected_digest: bytes | None
    expected_mode: int | None
    after_mode: int


@dataclass(frozen=True)
class ToolPolicy:
    """Week 4, Day 3: filesystem and command boundaries for one workspace."""

    root: Path
    allow_writes: bool = False
    allowed_commands: tuple[tuple[str, ...], ...] = ()
    max_file_bytes: int = 64 * 1024
    max_write_bytes: int = 64 * 1024
    max_list_entries: int = 200
    max_tool_output_chars: int = 16_000
    command_timeout_seconds: float = 30.0

    def __post_init__(self) -> None:
        """Week 4, Day 3: normalize the root and reject invalid limits."""

        root = self.root.resolve()
        object.__setattr__(self, "root", root)
        numeric_limits = (
            self.max_file_bytes,
            self.max_write_bytes,
            self.max_list_entries,
            self.max_tool_output_chars,
            self.command_timeout_seconds,
        )
        if any(limit <= 0 for limit in numeric_limits):
            raise ValueError("tool policy limits must be positive")
        if not root.exists() or not root.is_dir():
            raise ValueError("workspace root must be an existing directory")
        home = Path.home().resolve()
        if root.parent == root or root == home or root in home.parents:
            raise ValueError("workspace root is too broad")
        if reason := _protected_path_reason(root.parts):
            raise ValueError(f"workspace root is protected: {reason}")
        for command in self.allowed_commands:
            if not command or any(
                not isinstance(part, str) or not part or "\x00" in part
                for part in command
            ):
                raise ValueError("allowed commands must contain non-empty arguments")


@dataclass
class Workspace:
    """Week 4, Days 3 and 5: bounded tools over one explicit workspace root."""

    policy: ToolPolicy
    confirm_tool: Callable[[ToolAction], bool] | None = None
    observed_files: dict[Path, bytes] = field(default_factory=dict, init=False)
    modified_files: set[Path] = field(default_factory=set, init=False)
    uncertain_modified_files: set[Path] = field(default_factory=set, init=False)
    command_side_effects_untracked: bool = field(default=False, init=False)
    command_cleanup_incomplete: bool = field(default=False, init=False)

    @property
    def available_tools(self) -> frozenset[str]:
        """Week 4, Day 3: expose only tools enabled by operator policy."""

        tools = {"list_files", "read_file"}
        if self.policy.allow_writes:
            tools.update({"write_file", "edit_file"})
        if self.policy.allowed_commands:
            tools.add("run_command")
        return frozenset(tools)

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Week 4, Day 3: reject escapes, protected files, and symlink traversal."""

        if not isinstance(raw, str) or not raw or "\x00" in raw:
            raise AgentError("path must be a non-empty string")
        unresolved = Path(raw)
        if unresolved.is_absolute():
            raise AgentError("absolute paths are not allowed")
        if ".." in unresolved.parts:
            raise AgentError("parent path components are not allowed")
        current = self.policy.root
        for part in unresolved.parts:
            current /= part
            if current.is_symlink():
                raise AgentError("symlinks are not accessible")
        path = (self.policy.root / unresolved).resolve(strict=False)
        try:
            relative = path.relative_to(self.policy.root)
        except ValueError as error:
            raise AgentError("path leaves the workspace") from error
        self._reject_protected(relative)

        if must_exist and not path.exists():
            raise AgentError(f"path does not exist: {relative}")
        return path

    def _reject_protected(self, relative: Path) -> None:
        """Week 4, Day 3: keep repository metadata and common secrets hidden."""

        if reason := _protected_path_reason(relative.parts):
            raise AgentError(reason)

    def list_files(self, raw: str = ".") -> str:
        """Week 4, Day 3: list one directory without following symlinks."""

        path = self.resolve_path(raw)
        if not path.is_dir():
            raise AgentError("list_files path must be a directory")
        lines: list[str] = []
        items = heapq.nsmallest(
            self.policy.max_list_entries,
            path.iterdir(),
            key=lambda entry: entry.name,
        )
        for item in items:
            if item.is_symlink():
                continue
            try:
                relative = item.relative_to(self.policy.root)
                self._reject_protected(relative)
            except AgentError:
                continue
            kind = "dir" if item.is_dir() else "file"
            lines.append(f"{kind} {relative}")
            if len(lines) == self.policy.max_list_entries:
                break
        return "\n".join(lines)

    def read_file(self, raw: str) -> str:
        """Week 4, Day 3: read one bounded UTF-8 regular file."""

        path = self.resolve_path(raw)
        data = self._read_bounded_file(path, tool="read_file")
        content = data.decode("utf-8")
        self.observed_files[path] = self._digest(data)
        return content

    def write_file(self, raw: str, content: str) -> str:
        """Week 4, Day 3: atomically create or replace an inspected file."""

        prepared = self._prepare_write(raw, content)
        return self._commit_write(prepared)

    def _prepare_write(self, raw: str, content: str) -> _PreparedWrite:
        """Validate a write completely before asking for operator approval."""

        if not self.policy.allow_writes:
            raise AgentError("writes are disabled; restart with --allow-writes")
        encoded = content.encode("utf-8")
        if len(encoded) > self.policy.max_write_bytes:
            raise AgentError(f"content exceeds {self.policy.max_write_bytes} bytes")
        path = self.resolve_path(raw, must_exist=False)
        expected_digest = self.observed_files.get(path)
        if expected_digest is not None and not path.exists():
            raise AgentError("file changed since it was read; read it again")
        if path.exists():
            if expected_digest is None:
                raise AgentError(
                    "existing files must be read before they are overwritten"
                )
            current = self._read_bounded_file(path, tool="write_file")
            if self._digest(current) != expected_digest:
                raise AgentError("file changed since it was read; read it again")
            expected_mode = stat.S_IMODE(os.stat(path, follow_symlinks=False).st_mode)
            after_mode = expected_mode & 0o777
        else:
            expected_mode = None
            after_mode = 0o600
        if not path.parent.exists() or not path.parent.is_dir():
            raise AgentError("parent directory must already exist")
        return _PreparedWrite(
            path,
            encoded,
            expected_digest,
            expected_mode,
            after_mode,
        )

    def _commit_write(self, prepared: _PreparedWrite) -> str:
        """Revalidate and commit one previously prepared write."""

        relative = prepared.path.relative_to(self.policy.root)
        path = self.resolve_path(str(relative), must_exist=False)
        self._revalidate_prepared_write(prepared)
        self.uncertain_modified_files.add(path)
        self._atomic_write(path, prepared.content, after_mode=prepared.after_mode)
        self.observed_files[path] = self._digest(prepared.content)
        self.modified_files.add(path)
        self.uncertain_modified_files.discard(path)
        return f"wrote {relative}"

    def _revalidate_prepared_write(self, prepared: _PreparedWrite) -> None:
        """Reject content or mode changes made after operator approval."""

        path = prepared.path
        if prepared.expected_digest is None:
            if path.exists():
                raise AgentError("write target appeared after approval; read it first")
        else:
            if not path.exists():
                raise AgentError("file changed since it was read; read it again")
            current = self._read_bounded_file(path, tool="write_file")
            current_mode = stat.S_IMODE(os.stat(path, follow_symlinks=False).st_mode)
            if (
                self._digest(current) != prepared.expected_digest
                or current_mode != prepared.expected_mode
            ):
                raise AgentError("file changed since it was read; read it again")

    def edit_file(self, raw: str, old: str, new: str) -> str:
        """Week 4, Day 5: make one exact, reviewable replacement in a read file."""

        prepared = self._prepare_edit(raw, old, new)
        return self._commit_write(prepared)

    def _prepare_edit(self, raw: str, old: str, new: str) -> _PreparedWrite:
        """Validate and compute an edit without changing the workspace."""

        if not self.policy.allow_writes:
            raise AgentError("writes are disabled; restart with --allow-writes")
        path = self.resolve_path(raw)
        if path not in self.observed_files:
            raise AgentError("files must be read before they are edited")
        if not old:
            raise AgentError("old text must not be empty")
        data = self._read_bounded_file(path, tool="edit_file")
        if self._digest(data) != self.observed_files[path]:
            raise AgentError("file changed since it was read; read it again")
        content = data.decode("utf-8")
        matches = content.count(old)
        if matches != 1:
            raise AgentError(f"old text must match exactly once; found {matches}")
        return self._prepare_write(raw, content.replace(old, new, 1))

    def run_command(self, argv: list[str]) -> str:
        """Week 4, Day 5: run only an operator-approved exact argv without a shell."""

        command = self._prepare_command(argv)
        result, _ = self._run_command(command)
        return result

    def _prepare_command(self, argv: list[str]) -> tuple[str, ...]:
        """Validate an exact command without starting a process."""

        command = tuple(argv)
        if command not in self.policy.allowed_commands:
            raise AgentError("command was not explicitly allowed by the operator")
        return command

    def _run_command(self, argv: tuple[str, ...]) -> tuple[str, tuple[str, ...]]:
        """Execute one previously validated command."""

        environment = {
            name: value
            for name in ("PATH", "LANG", "LC_ALL", "TMPDIR")
            if (value := os.environ.get(name)) is not None
        }
        process = None
        cleaned_up = False

        def clean_up() -> None:
            """Kill this command group at most once after it has started."""

            nonlocal cleaned_up
            if process is not None and not cleaned_up:
                self.command_side_effects_untracked = True
                cleaned_up = True
                self._kill_and_reap(process)

        try:
            process = subprocess.Popen(
                argv,
                cwd=self.policy.root,
                env=environment,
                shell=False,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                start_new_session=True,
                bufsize=0,
            )
            self.command_side_effects_untracked = True
            assert process.stdout is not None
            captured = bytearray()
            output_truncated = Event()
            output_read_failed = Event()
            output_abandoned = False

            def drain_output() -> None:
                """Drain output without retaining unbounded bytes."""

                try:
                    while chunk := process.stdout.read(4096):
                        remaining = self.policy.max_tool_output_chars - len(captured)
                        if remaining > 0:
                            captured.extend(chunk[:remaining])
                        if len(chunk) > remaining:
                            output_truncated.set()
                except (OSError, ValueError):
                    self.command_cleanup_incomplete = True
                    output_read_failed.set()

            reader = Thread(target=drain_output, daemon=True)
            reader.start()
            try:
                returncode = process.wait(timeout=self.policy.command_timeout_seconds)
            except subprocess.TimeoutExpired as error:
                clean_up()
                raise AgentError(
                    f"command exceeded {self.policy.command_timeout_seconds:g} seconds"
                ) from error
            except KeyboardInterrupt:
                clean_up()
                raise
            finally:
                reader.join(timeout=0.05)
                if reader.is_alive():
                    clean_up()
                    reader.join(timeout=1)
                    if reader.is_alive():
                        output_abandoned = True
                        self.command_cleanup_incomplete = True
                        try:
                            process.stdout.close()
                        except (OSError, ValueError):
                            pass
                        reader.join(timeout=0.1)
        except AgentError:
            clean_up()
            raise
        except Exception as error:
            clean_up()
            if process is None:
                raise
            raise AgentError(
                f"command runner failed after starting: {error}"
            ) from error
        except BaseException:
            clean_up()
            raise
        finally:
            if process is not None and process.stdout is not None:
                try:
                    process.stdout.close()
                except (OSError, ValueError):
                    pass

        output = bytes(captured).decode("utf-8", errors="replace")
        markers = []
        trusted_warnings = []
        if output_truncated.is_set():
            markers.append("... command output truncated")
        if output_read_failed.is_set():
            self.command_cleanup_incomplete = True
            warning = "command output collection failed"
            markers.append(f"... {warning}")
            trusted_warnings.append(warning)
        if output_abandoned:
            warning = "command output abandoned; a descendant may retain the pipe"
            markers.append(f"... {warning}")
            trusted_warnings.append(warning)
        output = "\n".join(part for part in (output, *markers) if part)
        return f"exit code: {returncode}\n{output}".rstrip(), tuple(trusted_warnings)

    def _kill_and_reap(self, process) -> bool:
        """Attempt bounded process-group termination and foreground reaping."""

        try:
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            except (OSError, AttributeError):
                self.command_cleanup_incomplete = True
                try:
                    process.kill()
                except OSError:
                    pass
        except BaseException:
            self.command_cleanup_incomplete = True
            raise
        try:
            process.wait(timeout=1)
        except (OSError, subprocess.TimeoutExpired):
            self.command_cleanup_incomplete = True
            return False
        except BaseException:
            self.command_cleanup_incomplete = True
            raise
        return True

    def _require_confirmation(self, action: ToolAction) -> None:
        """Default-deny one model-requested side effect."""

        if self.confirm_tool is None or not self.confirm_tool(action):
            raise AgentError(f"operator denied {action.tool}")

    def execute(self, action: ToolAction) -> str:
        """Week 4, Day 3: dispatch a validated action and return recoverable errors."""

        preserve_command_warnings: tuple[str, ...] = ()
        try:
            if action.tool == "list_files":
                result = self.list_files(action.arguments.get("path", "."))
            elif action.tool == "read_file":
                result = self.read_file(action.arguments["path"])
            elif action.tool == "write_file":
                prepared = self._prepare_write(
                    action.arguments["path"], action.arguments["content"]
                )
                self._require_confirmation(action)
                result = self._commit_write(prepared)
            elif action.tool == "edit_file":
                prepared = self._prepare_edit(
                    action.arguments["path"],
                    action.arguments["old"],
                    action.arguments["new"],
                )
                self._require_confirmation(action)
                result = self._commit_write(prepared)
            elif action.tool == "run_command":
                command = self._prepare_command(action.arguments["argv"])
                self._require_confirmation(action)
                result, preserve_command_warnings = self._run_command(command)
            else:
                raise AgentError(f"unknown tool: {action.tool}")
        except (
            KeyError,
            OSError,
            subprocess.SubprocessError,
            ValueError,
        ) as error:
            result = f"error: {error}"
        return self._truncate_result(
            result,
            preserve_command_warnings=preserve_command_warnings,
        )

    def _truncate_result(
        self,
        result: str,
        *,
        preserve_command_warnings: tuple[str, ...] = (),
    ) -> str:
        """Bound a result while preserving trusted command-safety warnings."""

        limit = self.policy.max_tool_output_chars
        if len(result) <= limit:
            return result
        marker = "\n... tool output truncated"
        safety = "".join(
            f"\nwarning: {warning}" for warning in preserve_command_warnings
        )
        suffix = marker + safety
        if len(suffix) >= limit:
            if preserve_command_warnings:
                return safety.lstrip()[:limit]
            return result[:limit]
        return result[: limit - len(suffix)] + suffix

    def _read_bounded_file(self, path: Path, *, tool: str) -> bytes:
        """Read a regular file without accepting a changed type or unbounded size."""

        if path.is_symlink() or not path.is_file():
            raise AgentError(f"{tool} path must be a regular file")
        with path.open("rb") as file:
            data = file.read(self.policy.max_file_bytes + 1)
        if len(data) > self.policy.max_file_bytes:
            raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
        return data

    @staticmethod
    def _digest(content: bytes) -> bytes:
        """Fingerprint observed bytes for stale-write detection."""

        return hashlib.sha256(content).digest()

    def _atomic_write(self, path: Path, content: bytes, *, after_mode: int) -> None:
        """Week 4, Day 3: replace a file without exposing a partial write."""

        descriptor, temporary_name = tempfile.mkstemp(
            prefix=".tiny-llm-agent-", dir=path.parent
        )
        temporary = Path(temporary_name)
        try:
            os.fchmod(descriptor, after_mode)
            with os.fdopen(descriptor, "wb") as file:
                file.write(content)
                file.flush()
                os.fsync(file.fileno())
            os.replace(temporary, path)
        finally:
            if temporary.exists():
                temporary.unlink()
