# WARNING: Under review - generated by LLM.

import json
import os
import stat
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from types import SimpleNamespace

import pytest

from .tiny_llm_base import (
    AgentError,
    FinalAction,
    EffectReceipt,
    ReceiptStore,
    ToolPolicy,
    ToolAction,
    Workspace,
    build_system_prompt,
    parse_action,
    tool_catalog_hash,
)


def workspace(*, allow_writes=False, allowed_commands=()):
    """Day 1 prompt boundary without depending on the Day 2 workspace."""

    policy = SimpleNamespace(
        allow_writes=allow_writes,
        allowed_commands=allowed_commands,
    )
    tools = {"list_files", "read_file"}
    if allow_writes:
        tools.update({"write_file", "edit_file"})
    if allowed_commands:
        tools.add("run_command")
    return SimpleNamespace(policy=policy, available_tools=frozenset(tools))


def test_task_1_parse_final_action():
    assert parse_action('{"final":"done"}') == FinalAction("done")


@pytest.mark.parametrize(
    ("response", "expected"),
    [
        ('{"tool":"list_files"}', ToolAction("list_files", {})),
        (
            '{"tool":"list_files","path":"src"}',
            ToolAction("list_files", {"path": "src"}),
        ),
        (
            '{"tool":"read_file","path":"README.md"}',
            ToolAction("read_file", {"path": "README.md"}),
        ),
        (
            '{"tool":"write_file","path":"x","content":"y"}',
            ToolAction("write_file", {"path": "x", "content": "y"}),
        ),
        (
            '{"tool":"edit_file","path":"x","old":"a","new":"b"}',
            ToolAction("edit_file", {"path": "x", "old": "a", "new": "b"}),
        ),
        (
            '{"tool":"run_command","argv":["pdm","run","test"]}',
            ToolAction("run_command", {"argv": ["pdm", "run", "test"]}),
        ),
    ],
)
def test_task_1_parse_every_tool_schema(response, expected):
    assert parse_action(response) == expected


@pytest.mark.parametrize(
    "response",
    [
        "not json",
        '{"final":"done"} trailing text',
        '{"tool":"unknown"}',
        '{"tool":"read_file"}',
        '{"tool":"write_file","content":"y"}',
        '{"tool":"write_file","path":"x"}',
        '{"tool":"edit_file","old":"a","new":"b"}',
        '{"tool":"edit_file","path":"x","new":"b"}',
        '{"tool":"edit_file","path":"x","old":"a"}',
        '{"tool":"run_command"}',
        '{"tool":"read_file","path":7}',
        '{"final":"done","tool":"read_file"}',
        '{"final":"   "}',
        "[]",
        '{"tool":"list_files","path":".","extra":true}',
        '{"tool":"write_file","path":"x","content":7}',
        '{"tool":"edit_file","path":"x","old":[],"new":"b"}',
        '{"tool":"run_command","argv":[]}',
        '{"tool":"run_command","argv":["pdm",""]}',
    ],
)
def test_task_1_rejects_malformed_actions(response):
    with pytest.raises(AgentError):
        parse_action(response)


def test_task_2_prompt_contains_only_enabled_tools():
    read_only = workspace()
    prompt = build_system_prompt(read_only)
    assert '"tool":"read_file"' in prompt
    assert '"tool":"write_file"' not in prompt
    assert '"tool":"run_command"' not in prompt

    writable = workspace(allow_writes=True)
    prompt = build_system_prompt(writable)
    assert '"tool":"write_file"' in prompt
    assert '"tool":"edit_file"' in prompt


def test_task_2_prompt_contains_only_allowed_commands():
    enabled = workspace(allowed_commands=(("pdm", "run", "test"),))
    prompt = build_system_prompt(enabled)

    assert '["pdm", "run", "test"]' in prompt
    assert '"tool":"run_command"' in prompt


def test_task_2_rejects_a_known_but_disabled_tool():
    read_only = workspace()
    with pytest.raises(AgentError, match="not enabled"):
        parse_action(
            '{"tool":"write_file","path":"x","content":"y"}',
            read_only.available_tools,
        )


def test_task_3_tool_catalog_hash_is_stable_and_schema_bound():
    same = tool_catalog_hash(frozenset({"read_file", "list_files"}))
    assert same == tool_catalog_hash(frozenset({"read_file", "list_files"}))
    assert tool_catalog_hash(frozenset({"read_file"})) != same
    assert tool_catalog_hash(frozenset({"read_file", "write_file"})) != same


def test_task_3_enabled_tools_change_the_catalog_hash():
    read_only = tool_catalog_hash(frozenset({"read_file"}))
    writable = tool_catalog_hash(frozenset({"read_file", "write_file"}))
    assert read_only != writable


def test_task_3_catalog_hash_covers_field_contracts():
    from .tiny_llm_base import TOOL_CATALOG_HASH

    all_tools = frozenset(
        {"list_files", "read_file", "write_file", "edit_file", "run_command"}
    )
    assert TOOL_CATALOG_HASH == tool_catalog_hash(all_tools)
    assert len(TOOL_CATALOG_HASH) == 64


def bounded_workspace(
    root: Path,
    *,
    allow_writes: bool = False,
    allowed_commands: tuple[tuple[str, ...], ...] = (),
    confirm_tool=None,
    command_timeout_seconds: float = 1.0,
) -> Workspace:
    """Build the real Day 2 workspace used by the cumulative checkpoint."""

    return Workspace(
        ToolPolicy(
            root,
            allow_writes=allow_writes,
            allowed_commands=allowed_commands,
            command_timeout_seconds=command_timeout_seconds,
        ),
        confirm_tool=confirm_tool,
    )


def test_task_4_paths_fail_closed_for_escapes_symlinks_and_secrets(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    outside = tmp_path / "outside.txt"
    outside.write_text("outside", encoding="utf-8")
    (root / "visible.txt").write_text("visible", encoding="utf-8")
    (root / ".env").write_text("TOKEN=secret", encoding="utf-8")
    (root / "private.key").write_text("secret", encoding="utf-8")
    (root / ".git").mkdir()
    (root / ".git" / "config").write_text("secret", encoding="utf-8")
    (root / "link.txt").symlink_to(outside)
    (root / "internal-link.txt").symlink_to(root / "visible.txt")
    ws = bounded_workspace(root)

    assert ws.read_file("visible.txt") == "visible"
    for path in (
        "../outside.txt",
        ".env",
        "private.key",
        ".git/config",
        "link.txt",
        "internal-link.txt",
    ):
        with pytest.raises(AgentError):
            ws.read_file(path)
    listing = ws.list_files()
    assert "visible.txt" in listing
    assert ".env" not in listing
    assert ".git" not in listing
    assert "link.txt" not in listing
    assert "internal-link.txt" not in listing


def test_task_4_root_identity_swap_never_reads_the_replacement(tmp_path, monkeypatch):
    root = tmp_path / "workspace"
    root.mkdir()
    (root / "answer.txt").write_text("authorized", encoding="utf-8")
    replacement = tmp_path / "replacement"
    replacement.mkdir()
    (replacement / "answer.txt").write_text("replacement", encoding="utf-8")
    authorized = tmp_path / "authorized"
    ws = bounded_workspace(root)
    validate = ws._validate_root
    swapped = False

    def validate_then_swap():
        nonlocal swapped
        validate()
        if not swapped:
            root.rename(authorized)
            replacement.rename(root)
            swapped = True

    monkeypatch.setattr(ws, "_validate_root", validate_then_swap)
    with pytest.raises(AgentError, match="root changed"):
        ws.read_file("answer.txt")
    assert (root / "answer.txt").read_text(encoding="utf-8") == "replacement"


def test_task_4_root_swap_during_approval_never_writes_replacement(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    (root / "answer.txt").write_text("authorized", encoding="utf-8")
    replacement = tmp_path / "replacement"
    replacement.mkdir()
    (replacement / "answer.txt").write_text("replacement", encoding="utf-8")
    authorized = tmp_path / "authorized"

    def swap_root(_action):
        root.rename(authorized)
        replacement.rename(root)
        return True

    ws = bounded_workspace(root, allow_writes=True, confirm_tool=swap_root)
    assert ws.read_file("answer.txt") == "authorized"
    result = ws.execute(
        ToolAction("write_file", {"path": "answer.txt", "content": "changed"}),
        tool_call_id="root-write-race",
    )
    assert "root changed" in result
    assert (root / "answer.txt").read_text(encoding="utf-8") == "replacement"
    assert (authorized / "answer.txt").read_text(encoding="utf-8") == "authorized"


def test_task_5_overwrite_requires_a_fresh_inspection(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    target = root / "answer.txt"
    target.write_text("one", encoding="utf-8")
    ws = bounded_workspace(root, allow_writes=True)

    with pytest.raises(AgentError, match="read before overwrite"):
        ws.write_file("answer.txt", "two")
    assert ws.read_file("answer.txt") == "one"
    target.write_text("changed elsewhere", encoding="utf-8")
    with pytest.raises(AgentError, match="changed since it was read"):
        ws.write_file("answer.txt", "two")
    assert target.read_text(encoding="utf-8") == "changed elsewhere"


def test_task_6_preflight_precedes_approval_and_commit_revalidates(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    target = root / "answer.txt"
    target.write_text("one", encoding="utf-8")
    approvals = []

    def mutate_during_approval(action):
        approvals.append(action.tool)
        target.write_text("changed during approval", encoding="utf-8")
        return True

    ws = bounded_workspace(root, allow_writes=True, confirm_tool=mutate_during_approval)
    result = ws.execute(
        ToolAction("write_file", {"path": "answer.txt", "content": "two"}),
        tool_call_id="invalid-before-approval",
    )
    assert result.startswith("error:")
    assert approvals == []

    ws.read_file("answer.txt")
    result = ws.execute(
        ToolAction("write_file", {"path": "answer.txt", "content": "two"}),
        tool_call_id="race-after-approval",
    )
    assert result.startswith("error:")
    assert approvals == ["write_file"]
    assert target.read_text(encoding="utf-8") == "changed during approval"


def test_task_6_post_read_mode_change_invalidates_prepared_write(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    target = root / "answer.txt"
    target.write_text("one", encoding="utf-8")

    approvals = []
    ws = bounded_workspace(
        root,
        allow_writes=True,
        confirm_tool=lambda action: approvals.append(action) or True,
    )
    assert ws.read_file("answer.txt") == "one"
    target.chmod(0o400)
    result = ws.execute(
        ToolAction("write_file", {"path": "answer.txt", "content": "two"}),
        tool_call_id="mode-race",
    )
    assert "file mode changed" in result
    assert approvals == []
    assert target.read_text(encoding="utf-8") == "one"


def test_task_6_mode_is_revalidated_after_approval(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    target = root / "answer.txt"
    target.write_text("one", encoding="utf-8")

    def chmod_during_approval(_action):
        target.chmod(0o400)
        return True

    ws = bounded_workspace(root, allow_writes=True, confirm_tool=chmod_during_approval)
    assert ws.read_file("answer.txt") == "one"
    result = ws.execute(
        ToolAction("write_file", {"path": "answer.txt", "content": "two"}),
        tool_call_id="mode-approval-race",
    )
    assert "file mode changed" in result
    assert target.read_text(encoding="utf-8") == "one"


def test_task_6_model_dispatched_effects_are_default_deny(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    ws = bounded_workspace(root, allow_writes=True)

    result = ws.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "no"}),
        tool_call_id="denied-write",
    )
    assert "operator denied" in result
    assert not (root / "new.txt").exists()
    assert ws.last_receipt is not None
    assert ws.last_receipt.exit_state == "error"
    assert ws.last_receipt.changed_artifacts == ()


def test_task_7_command_allowlist_is_exact_and_approval_is_required(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    allowed = (sys.executable, "-c", "print('allowed')")
    failing = (
        sys.executable,
        "-c",
        "import sys; print('failed'); sys.exit(3)",
    )
    approvals = []
    ws = bounded_workspace(
        root,
        allowed_commands=(allowed, failing),
        confirm_tool=lambda action: approvals.append(action) or True,
    )

    rejected = ws.execute(
        ToolAction("run_command", {"argv": [*allowed, "extra"]}),
        tool_call_id="not-exact",
    )
    assert "not explicitly allowed" in rejected
    assert approvals == []

    result = ws.execute(
        ToolAction("run_command", {"argv": list(allowed)}),
        tool_call_id="exact-command",
    )
    assert "allowed" in result
    assert "[exit code: 0]" in result
    assert len(approvals) == 1

    result = ws.execute(
        ToolAction("run_command", {"argv": list(failing)}),
        tool_call_id="failed-command",
    )
    assert "failed" in result
    assert "command exited with code 3" in result
    assert ws.last_receipt is not None
    assert ws.last_receipt.exit_state == "error"
    assert len(approvals) == 2


def test_task_7_command_timeout_is_bounded_and_receipted(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    command = (sys.executable, "-c", "import time; time.sleep(5)")
    ws = bounded_workspace(
        root,
        allowed_commands=(command,),
        confirm_tool=lambda _action: True,
        command_timeout_seconds=0.1,
    )

    result = ws.execute(
        ToolAction("run_command", {"argv": list(command)}),
        tool_call_id="timed-command",
    )
    assert "timed out after" in result
    assert ws.last_receipt is not None
    assert ws.last_receipt.exit_state == "uncertain"


def test_task_7_closed_pipes_cannot_escape_the_process_deadline(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    command = (
        sys.executable,
        "-c",
        "import os,time,pathlib; os.close(1); os.close(2); time.sleep(0.6); "
        "pathlib.Path('late.txt').write_text('late')",
    )
    ws = bounded_workspace(
        root,
        allowed_commands=(command,),
        confirm_tool=lambda _action: True,
        command_timeout_seconds=0.1,
    )

    started = time.monotonic()
    result = ws.execute(
        ToolAction("run_command", {"argv": list(command)}),
        tool_call_id="closed-pipes-timeout",
    )
    elapsed = time.monotonic() - started
    assert elapsed < 1.0
    assert "timed out after" in result
    assert ws.last_receipt is not None
    assert ws.last_receipt.exit_state == "uncertain"
    time.sleep(0.7)
    assert not (root / "late.txt").exists()


def test_task_8_receipts_are_detached_immutable_and_content_addressed():
    arguments = {"path": "answer.txt", "metadata": ["one"]}
    receipt = EffectReceipt(
        tool_call_id="call-1",
        tool="write_file",
        arguments=arguments,
        exit_state="ok",
        result="wrote answer.txt",
        changed_artifacts=("answer.txt",),
    )
    receipt_id = receipt.receipt_id
    arguments["metadata"].append("mutated")

    assert receipt.receipt_id == receipt_id
    assert receipt.to_dict()["arguments"]["metadata"] == ["one"]
    with pytest.raises(TypeError):
        receipt.arguments["path"] = "other.txt"
    with pytest.raises(AttributeError):
        receipt.arguments["metadata"].append("other")
    durable = receipt.to_dict()
    durable["result"] = "tampered"
    with pytest.raises(ValueError, match="digest"):
        EffectReceipt.from_dict(durable)


def test_task_8_receipt_store_is_durable_and_rejects_tampering(tmp_path):
    path = tmp_path / "receipts.jsonl"
    receipt = EffectReceipt(
        tool_call_id="call-2",
        tool="read_file",
        arguments={"path": "answer.txt"},
        exit_state="ok",
        result="answer",
        changed_artifacts=(),
    )
    store = ReceiptStore(path)
    receipt_id = store.put(receipt)
    assert store.put(receipt) == receipt_id
    assert len(store) == 1

    reopened = ReceiptStore(path)
    assert reopened.require(receipt_id).to_dict() == receipt.to_dict()
    assert reopened.by_tool_call("call-2") == receipt
    conflicting = EffectReceipt(
        tool_call_id="call-2",
        tool="read_file",
        arguments={"path": "other.txt"},
        exit_state="ok",
        result="other",
        changed_artifacts=(),
    )
    with pytest.raises(ValueError, match="already belongs"):
        reopened.put(conflicting)

    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["result"] = "tampered"
    path.write_text(json.dumps(payload) + "\n", encoding="utf-8")
    with pytest.raises(ValueError, match="invalid receipt"):
        ReceiptStore(path)


def test_task_8_two_live_stores_serialize_call_ids_and_reopen_cleanly(tmp_path):
    path = tmp_path / "receipts.jsonl"
    first = ReceiptStore(path)
    stale = ReceiptStore(path)
    receipt = EffectReceipt(
        tool_call_id="shared-call",
        tool="read_file",
        arguments={"path": "answer.txt"},
        exit_state="ok",
        result="answer",
        changed_artifacts=(),
    )
    conflict = EffectReceipt(
        tool_call_id="shared-call",
        tool="read_file",
        arguments={"path": "other.txt"},
        exit_state="ok",
        result="other",
        changed_artifacts=(),
    )

    receipt_id = first.put(receipt)
    assert stale.put(receipt) == receipt_id
    with pytest.raises(ValueError, match="already belongs"):
        stale.put(conflict)
    reopened = ReceiptStore(path)
    assert len(reopened) == 1
    assert reopened.by_tool_call("shared-call") == receipt


def test_task_9_workspace_persists_exact_changed_artifact_receipt(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    path = tmp_path / "receipts.jsonl"
    ws = bounded_workspace(root, allow_writes=True, confirm_tool=lambda _action: True)
    ws.bind_receipt_store(ReceiptStore(path))

    result = ws.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "hello"}),
        tool_call_id="write-new",
    )
    assert result == "wrote new.txt"
    receipt = ReceiptStore(path).by_tool_call("write-new")
    assert receipt is not None
    assert receipt.exit_state == "ok"
    assert receipt.changed_artifacts == ("new.txt",)
    assert receipt.arguments == {"path": "new.txt", "content": "hello"}
    with pytest.raises(AgentError, match="already has a receipt"):
        ws.execute(
            ToolAction("write_file", {"path": "other.txt", "content": "no"}),
            tool_call_id="write-new",
        )
    assert not (root / "other.txt").exists()


def test_task_9_two_workspaces_cannot_repeat_one_durable_call_id(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    path = tmp_path / "receipts.jsonl"
    command = (
        sys.executable,
        "-c",
        "from pathlib import Path; p=Path('count.txt'); "
        "p.write_text(p.read_text() + 'x' if p.exists() else 'x')",
    )
    first = bounded_workspace(
        root,
        allowed_commands=(command,),
        confirm_tool=lambda _action: True,
    )
    stale = bounded_workspace(
        root,
        allowed_commands=(command,),
        confirm_tool=lambda _action: True,
    )
    first.bind_receipt_store(ReceiptStore(path))
    stale.bind_receipt_store(ReceiptStore(path))
    action = ToolAction("run_command", {"argv": list(command)})

    def dispatch(ws):
        try:
            return ws.execute(action, tool_call_id="one-effect")
        except AgentError as error:
            return str(error)

    with ThreadPoolExecutor(max_workers=2) as pool:
        results = list(pool.map(dispatch, (first, stale)))
    assert sum("exit code: 0" in result for result in results) == 1
    assert sum("already has a receipt" in result for result in results) == 1
    assert (root / "count.txt").read_text(encoding="utf-8") == "x"
    assert len(ReceiptStore(path)) == 1


def test_task_9_post_rename_fsync_failure_records_uncertain_change(
    tmp_path, monkeypatch
):
    root = tmp_path / "workspace"
    root.mkdir()
    ws = bounded_workspace(root, allow_writes=True, confirm_tool=lambda _action: True)
    real_fsync = os.fsync

    def fail_directory_fsync(descriptor):
        if stat.S_ISDIR(os.fstat(descriptor).st_mode):
            raise OSError("simulated parent fsync failure")
        return real_fsync(descriptor)

    monkeypatch.setattr(os, "fsync", fail_directory_fsync)
    result = ws.execute(
        ToolAction("write_file", {"path": "changed.txt", "content": "changed"}),
        tool_call_id="uncertain-write",
    )
    assert "durability could not be confirmed" in result
    assert (root / "changed.txt").read_text(encoding="utf-8") == "changed"
    assert ws.last_receipt is not None
    assert ws.last_receipt.exit_state == "uncertain"
    assert ws.last_receipt.changed_artifacts == ("changed.txt",)
    assert root / "changed.txt" in ws.uncertain_modified_files


@pytest.mark.parametrize("allow_writes", [1, "yes"])
def test_task_9_policy_rejects_truthy_non_boolean_write_flags(tmp_path, allow_writes):
    root = tmp_path / "workspace"
    root.mkdir()
    with pytest.raises(ValueError, match="allow_writes must be a boolean"):
        ToolPolicy(root, allow_writes=allow_writes)


@pytest.mark.parametrize(
    "timeout", [float("nan"), float("inf"), float("-inf"), 10**1_000]
)
def test_task_9_policy_rejects_non_finite_timeouts(tmp_path, timeout):
    root = tmp_path / "workspace"
    root.mkdir()
    with pytest.raises(ValueError, match="positive number"):
        ToolPolicy(root, command_timeout_seconds=timeout)
