# WARNING: Under review - generated by LLM.

"""Week 4 Day 3 edit, validation, and receipt tests."""

import json
import sys
from types import SimpleNamespace

import pytest

from .tiny_llm_base import (
    AgentError,
    EffectReceipt,
    ReceiptStore,
    ToolAction,
    ToolPolicy,
    Workspace,
    run_agent,
)


def test_task_1_policy_enables_only_explicit_effects(tmp_path):
    read_only = Workspace(ToolPolicy(tmp_path))
    command = (sys.executable, "-c", "print('ok')")
    enabled = Workspace(
        ToolPolicy(tmp_path, allow_writes=True, allowed_commands=(command,))
    )

    assert read_only.available_tools == frozenset({"list_files", "read_file"})
    assert enabled.available_tools == frozenset(
        {"list_files", "read_file", "write_file", "edit_file", "run_command"}
    )
    with pytest.raises(ValueError, match="positive"):
        ToolPolicy(tmp_path, max_write_bytes=0)
    with pytest.raises(ValueError, match="commands"):
        ToolPolicy(tmp_path, allowed_commands=(("",),))


def test_task_2_mutations_require_read_preflight_and_approval(tmp_path):
    source = tmp_path / "app.py"
    source.write_text("answer = 1\n", encoding="utf-8")
    approvals = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        lambda action: approvals.append(action) or False,
    )
    edit = ToolAction("edit_file", {"path": "app.py", "old": "1", "new": "2"})

    assert "read the existing file" in workspace.execute(edit)
    assert approvals == []
    assert workspace.read_file("app.py") == "answer = 1\n"
    assert "operator denied" in workspace.execute(edit)
    assert len(approvals) == 1
    assert source.read_text(encoding="utf-8") == "answer = 1\n"
    assert workspace.receipt_store.get("call-1") is None


def test_task_3_rechecks_stale_bytes_after_approval(tmp_path):
    source = tmp_path / "app.py"
    source.write_text("answer = 1\n", encoding="utf-8")

    def change_during_approval(_action):
        source.write_text("answer = 9\n", encoding="utf-8")
        return True

    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True), change_during_approval
    )
    workspace.read_file("app.py")
    result = workspace.execute(
        ToolAction("edit_file", {"path": "app.py", "old": "1", "new": "2"})
    )

    assert result == "error: file changed since it was read"
    assert source.read_text(encoding="utf-8") == "answer = 9\n"
    assert workspace.modified_files == ()


def test_task_4_exact_edit_uses_same_directory_replace_and_receipt(
    tmp_path, monkeypatch
):
    source = tmp_path / "app.py"
    source.write_text("answer = 1\n", encoding="utf-8")
    store = ReceiptStore(tmp_path / "receipts.jsonl")
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True), lambda _action: True, store
    )
    workspace.read_file("app.py")
    workspace_module = sys.modules[Workspace.__module__]
    real_replace = workspace_module.os.replace
    replacements = []

    def observe_replace(source_path, destination_path):
        replacements.append((source_path, destination_path))
        real_replace(source_path, destination_path)

    monkeypatch.setattr(workspace_module.os, "replace", observe_replace)
    result = workspace.execute(
        ToolAction("edit_file", {"path": "./app.py", "old": "1", "new": "2"}),
        "edit-1",
    )

    assert result == "edited app.py"
    assert source.read_text(encoding="utf-8") == "answer = 2\n"
    assert replacements[0][0].parent == replacements[0][1].parent == tmp_path
    assert workspace.modified_files == ("app.py",)
    assert store.get("edit-1").changed_artifacts == ("app.py",)


def test_task_5_write_creates_new_files_but_observes_existing_files(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True), lambda _action: True)
    create = ToolAction("write_file", {"path": "new.txt", "content": "new\n"})

    assert workspace.execute(create, "write-new") == "wrote new.txt"
    assert (tmp_path / "new.txt").read_text(encoding="utf-8") == "new\n"
    overwrite = ToolAction(
        "write_file", {"path": "new.txt", "content": "replacement\n"}
    )
    other = Workspace(ToolPolicy(tmp_path, allow_writes=True), lambda _action: True)
    assert "read the existing file" in other.execute(overwrite)
    other.read_file("new.txt")
    assert other.execute(overwrite) == "wrote new.txt"


def test_task_6_validation_uses_exact_argv_and_records_output(tmp_path):
    allowed = (
        sys.executable,
        "-c",
        "import sys; print('focused fail'); sys.exit(3)",
    )
    approvals = []
    store = ReceiptStore()
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(allowed,)),
        lambda action: approvals.append(action) or True,
        store,
    )

    denied = workspace.execute(ToolAction("run_command", {"argv": ["echo", "no"]}))
    result = workspace.execute(
        ToolAction("run_command", {"argv": list(allowed)}), "validate-1"
    )
    receipt = store.get("validate-1")

    assert denied == "error: command is not allowed"
    assert len(approvals) == 1
    assert result == "status: 3\noutput:\nfocused fail\n"
    assert receipt.arguments == {"argv": list(allowed)}
    assert receipt.exit_state == "error"
    assert receipt.result == result
    assert receipt.changed_artifacts == ()


def test_task_7_duplicate_call_ids_do_not_repeat_an_effect(tmp_path, monkeypatch):
    allowed = ("validator", "--focused")
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(allowed,)), lambda _action: True
    )
    workspace_module = sys.modules[Workspace.__module__]
    calls = []

    def fake_run(*args, **kwargs):
        calls.append((args, kwargs))
        return SimpleNamespace(returncode=0, stdout="pass\n", stderr="")

    monkeypatch.setattr(workspace_module.subprocess, "run", fake_run)
    action = ToolAction("run_command", {"argv": list(allowed)})

    first = workspace.execute(action, "same-call")
    second = workspace.execute(action, "same-call")

    assert first == second == "status: 0\noutput:\npass\n"
    assert len(calls) == 1
    conflict = workspace.execute(
        ToolAction("run_command", {"argv": ["different"]}), "same-call"
    )
    assert "already used" in conflict


def test_task_8_jsonl_receipts_reopen_and_detect_tampering(tmp_path):
    path = tmp_path / "receipts.jsonl"
    receipt = EffectReceipt(
        "edit-1",
        "edit_file",
        {"path": "app.py", "old": "1", "new": "2"},
        "ok",
        "edited app.py",
        ("app.py",),
    )
    ReceiptStore(path).put(receipt)

    assert ReceiptStore(path).get("edit-1") == receipt
    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["result"] = "edited another.py"
    path.write_text(json.dumps(payload) + "\n", encoding="utf-8")
    with pytest.raises(AgentError, match="digest"):
        ReceiptStore(path)


def test_task_9_agent_reads_edits_validates_and_finishes(tmp_path):
    source = tmp_path / "app.py"
    source.write_text("answer = 1\n", encoding="utf-8")
    validation = (
        sys.executable,
        "-c",
        "from pathlib import Path; assert Path('app.py').read_text() == 'answer = 2\\n'",
    )
    approved = []
    store = ReceiptStore(tmp_path / "receipts.jsonl")
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True, allowed_commands=(validation,)),
        lambda action: approved.append(action.tool) or True,
        store,
    )
    responses = iter(
        [
            '{"tool":"read_file","path":"app.py"}',
            '{"tool":"edit_file","path":"app.py","old":"1","new":"2"}',
            json.dumps({"tool": "run_command", "argv": list(validation)}),
            '{"final":"changed and validated app.py"}',
        ]
    )

    result = run_agent("fix app.py", lambda _messages: next(responses), workspace)

    assert result.completed
    assert result.final == "changed and validated app.py"
    assert workspace.modified_files == ("app.py",)
    assert approved == ["edit_file", "run_command"]
    assert store.get("call-1").changed_artifacts == ("app.py",)
    assert store.get("call-2").arguments == {"argv": list(validation)}
    assert store.get("call-2").changed_artifacts == ()
