# WARNING: Under review - generated by LLM.

import importlib
import json
import os
import subprocess
import sys
import threading
from dataclasses import asdict
from types import ModuleType

import pytest

from agent import build_parser, confirm_tool_call, validate_budget_arguments

from .tiny_llm_base import (
    AgentError,
    AgentLimits,
    ContextLimitError,
    ContextManager,
    ContextPolicy,
    GenerationSession,
    SessionStore,
    ToolAction,
    ToolPolicy,
    WorkingSummary,
    Workspace,
    memory_session,
    run_agent,
)


def patch_workspace_popen(monkeypatch, replacement):
    """Patch common qualified and directly imported Popen lookup styles."""

    workspace_module = importlib.import_module(Workspace.__module__)
    monkeypatch.setattr(subprocess, "Popen", replacement)
    monkeypatch.setattr(workspace_module, "Popen", replacement, raising=False)


def patch_workspace_thread(monkeypatch, replacement):
    """Patch common qualified and directly imported Thread lookup styles."""

    workspace_module = importlib.import_module(Workspace.__module__)
    monkeypatch.setattr(threading, "Thread", replacement)
    monkeypatch.setattr(workspace_module, "Thread", replacement, raising=False)


def patch_workspace_killpg(monkeypatch, replacement):
    """Patch common qualified and directly imported killpg lookup styles."""

    workspace_module = importlib.import_module(Workspace.__module__)
    monkeypatch.setattr(os, "killpg", replacement)
    monkeypatch.setattr(workspace_module, "killpg", replacement, raising=False)


def test_task_1_creates_and_atomically_replaces_files(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))

    assert workspace.write_file("new.txt", "one") == "wrote new.txt"
    assert (tmp_path / "new.txt").read_text(encoding="utf-8") == "one"
    assert workspace.write_file("new.txt", "two") == "wrote new.txt"
    assert (tmp_path / "new.txt").read_text(encoding="utf-8") == "two"


def test_task_1_requires_inspection_before_overwriting(tmp_path):
    (tmp_path / "existing.txt").write_text("old", encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))

    try:
        workspace.write_file("existing.txt", "new")
    except AgentError as error:
        assert "must be read" in str(error)
    else:
        assert False, "expected an uninspected overwrite to be rejected"
    assert (tmp_path / "existing.txt").read_text(encoding="utf-8") == "old"


def test_task_2_edit_requires_one_exact_match(tmp_path):
    path = tmp_path / "example.py"
    path.write_text("answer = 41\n", encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))
    workspace.read_file("example.py")

    workspace.edit_file("example.py", "41", "42")

    assert path.read_text(encoding="utf-8") == "answer = 42\n"
    assert workspace.modified_files == {path}


def test_task_3_commands_require_an_exact_operator_allowlist(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path))

    try:
        workspace.run_command(["some-command"])
    except AgentError as error:
        assert "not explicitly allowed" in str(error)
    else:
        assert False, "expected an unapproved command to be rejected"


def test_task_3_model_dispatched_writes_are_denied_without_confirmation(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))

    result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "data"})
    )

    assert result == "error: operator denied write_file"
    assert not (tmp_path / "new.txt").exists()


def test_task_3_model_dispatched_mutations_prompt_exactly_once(tmp_path):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action.tool) or True,
    )
    workspace.read_file("answer.py")

    edit_result = workspace.execute(
        ToolAction(
            "edit_file",
            {"path": "answer.py", "old": "41", "new": "42"},
        )
    )
    write_result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "data"})
    )

    assert edit_result == "wrote answer.py"
    assert write_result == "wrote new.txt"
    assert confirmations == ["edit_file", "write_file"]
    assert path.read_text(encoding="utf-8") == "ANSWER = 42\n"


def test_task_3_reads_never_request_confirmation(tmp_path):
    (tmp_path / "README.md").write_text("hello", encoding="utf-8")

    def unexpected_confirmation(action):
        raise AssertionError(f"unexpected confirmation for {action.tool}")

    workspace = Workspace(ToolPolicy(tmp_path), confirm_tool=unexpected_confirmation)

    assert workspace.execute(ToolAction("list_files", {})) == "file README.md"
    assert workspace.execute(ToolAction("read_file", {"path": "README.md"})) == "hello"


def test_task_3_denied_command_never_starts_a_process(tmp_path, monkeypatch):
    command = ("safe-tool", "--check")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(command,)),
        confirm_tool=lambda action: confirmations.append(action) and True,
    )

    def unexpected_popen(*args, **kwargs):
        raise AssertionError("a denied command must not start a process")

    patch_workspace_popen(monkeypatch, unexpected_popen)
    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == "error: operator denied run_command"
    assert len(confirmations) == 1
    assert not workspace.command_side_effects_untracked


def test_task_3_commands_default_to_denied_without_a_confirmer(tmp_path, monkeypatch):
    command = ("safe-tool", "--check")
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(command,)))

    def unexpected_popen(*args, **kwargs):
        raise AssertionError("a default-denied command must not start a process")

    patch_workspace_popen(monkeypatch, unexpected_popen)
    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == "error: operator denied run_command"
    assert not workspace.command_side_effects_untracked


def test_task_3_unallowlisted_command_is_rejected_before_confirmation(tmp_path):
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(("safe-tool",),)),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": ["different-tool"]}))

    assert result == "error: command was not explicitly allowed by the operator"
    assert confirmations == []
    assert not workspace.command_side_effects_untracked


@pytest.mark.parametrize("tool", ["write_file", "edit_file"])
def test_task_2_rejects_a_stale_observation_before_confirmation(tmp_path, tool):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )
    workspace.read_file("answer.py")
    path.write_text("ANSWER = 99\n", encoding="utf-8")
    action = (
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
        if tool == "write_file"
        else ToolAction(
            "edit_file",
            {"path": "answer.py", "old": "41", "new": "42"},
        )
    )

    result = workspace.execute(action)

    assert result == "error: file changed since it was read; read it again"
    assert path.read_text(encoding="utf-8") == "ANSWER = 99\n"
    assert confirmations == []


def test_task_2_rejects_a_deleted_observed_file_before_confirmation(tmp_path):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )
    workspace.read_file("answer.py")
    path.unlink()

    result = workspace.execute(
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
    )

    assert result == "error: file changed since it was read; read it again"
    assert not path.exists()
    assert confirmations == []


@pytest.mark.parametrize("tool", ["write_file", "edit_file"])
@pytest.mark.parametrize("external_change", ["replace", "delete"])
def test_task_2_revalidates_an_existing_file_after_confirmation(
    tmp_path, tool, external_change
):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")

    def change_during_confirmation(action):
        if external_change == "replace":
            path.write_text("ANSWER = 99\n", encoding="utf-8")
        else:
            path.unlink()
        return True

    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=change_during_confirmation,
    )
    workspace.read_file("answer.py")

    action = (
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
        if tool == "write_file"
        else ToolAction(
            "edit_file",
            {"path": "answer.py", "old": "41", "new": "42"},
        )
    )

    result = workspace.execute(action)

    assert result == "error: file changed since it was read; read it again"
    if external_change == "replace":
        assert path.read_text(encoding="utf-8") == "ANSWER = 99\n"
    else:
        assert not path.exists()


def test_task_2_rejects_a_new_target_that_appears_during_confirmation(tmp_path):
    path = tmp_path / "new.txt"

    def create_during_confirmation(action):
        path.write_text("external", encoding="utf-8")
        return True

    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=create_during_confirmation,
    )

    result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "agent"})
    )

    assert result == "error: write target appeared after approval; read it first"
    assert path.read_text(encoding="utf-8") == "external"


def test_task_2_tracks_a_file_when_commit_outcome_is_uncertain(tmp_path, monkeypatch):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: True,
    )
    workspace.read_file("answer.py")

    def replace_then_interrupt(target, content, **_write_state):
        target.write_bytes(content)
        raise KeyboardInterrupt

    monkeypatch.setattr(workspace, "_atomic_write", replace_then_interrupt)

    with pytest.raises(KeyboardInterrupt):
        workspace.execute(
            ToolAction(
                "edit_file",
                {"path": "answer.py", "old": "41", "new": "42"},
            )
        )

    assert path.read_text(encoding="utf-8") == "ANSWER = 42\n"
    assert workspace.modified_files == set()
    assert workspace.uncertain_modified_files == {path}


class _TtyInput:
    def isatty(self):
        return True


class _NonTtyInput:
    def isatty(self):
        return False


@pytest.mark.parametrize(
    ("response", "approved"),
    [("", False), ("n", False), ("anything", False), ("y", True), ("YES", True)],
)
def test_cli_confirmation_accepts_only_an_explicit_yes(
    tmp_path, monkeypatch, response, approved
):
    monkeypatch.setattr(sys, "stdin", _TtyInput())
    monkeypatch.setattr("builtins.input", lambda prompt: response)
    action = ToolAction("write_file", {"path": "new.txt", "content": "data"})

    assert confirm_tool_call(action, tmp_path) is approved


def test_cli_confirmation_denies_non_tty_and_eof(tmp_path, monkeypatch):
    action = ToolAction("write_file", {"path": "new.txt", "content": "data"})

    monkeypatch.setattr(sys, "stdin", _NonTtyInput())
    monkeypatch.setattr(
        "builtins.input",
        lambda prompt: (_ for _ in ()).throw(
            AssertionError("non-TTY confirmation must not read input")
        ),
    )
    assert not confirm_tool_call(action, tmp_path)

    monkeypatch.setattr(sys, "stdin", _TtyInput())
    monkeypatch.setattr(
        "builtins.input", lambda prompt: (_ for _ in ()).throw(EOFError())
    )
    assert not confirm_tool_call(action, tmp_path)


def test_cli_confirmation_escapes_terminal_control_characters(
    tmp_path, monkeypatch, capsys
):
    monkeypatch.setattr(sys, "stdin", _TtyInput())
    monkeypatch.setattr("builtins.input", lambda prompt: "n")
    action = ToolAction(
        "write_file",
        {"path": "\x1b[2J\u202eevil.txt", "content": "data"},
    )

    assert not confirm_tool_call(action, tmp_path)
    output = capsys.readouterr().out
    assert "\x1b" not in output
    assert "\u202e" not in output
    assert "\\u001b" in output
    assert "\\u202e" in output


class _EmptyStdout:
    def read(self, size):
        return b""

    def close(self):
        pass


class _PartiallyFailingStdout:
    def __init__(self):
        self.read_calls = 0

    def read(self, size):
        self.read_calls += 1
        if self.read_calls == 1:
            return b"x" * 128
        raise OSError("output pipe failed")

    def close(self):
        pass


class _FailingStdout:
    def read(self, size):
        raise OSError("output pipe failed")

    def close(self):
        pass


class _SynchronousThread:
    def __init__(self, *, target, daemon):
        self.target = target

    def start(self):
        self.target()

    def join(self, timeout=None):
        pass

    def is_alive(self):
        return False


class _InterruptedProcess:
    pid = 12345

    def __init__(self, error):
        self.stdout = _EmptyStdout()
        self.error = error
        self.wait_calls = 0
        self.killed = False

    def wait(self, timeout=None):
        self.wait_calls += 1
        if self.wait_calls == 1:
            raise self.error
        return -9

    def kill(self):
        self.killed = True


def test_task_3_keyboard_interrupt_kills_and_reaps_the_process_group(
    tmp_path, monkeypatch
):
    command = ["safe-tool"]
    process = _InterruptedProcess(KeyboardInterrupt())
    killed_groups = []
    popen_calls = []

    def start_process(*args, **kwargs):
        popen_calls.append((args, kwargs))
        return process

    patch_workspace_popen(monkeypatch, start_process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    with pytest.raises(KeyboardInterrupt):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert len(popen_calls) == 1
    _, popen_kwargs = popen_calls[0]
    assert popen_kwargs["start_new_session"] is True
    assert popen_kwargs["shell"] is False
    assert popen_kwargs["stdin"] is subprocess.DEVNULL


def test_task_3_timeout_kills_and_reaps_the_process_group(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _InterruptedProcess(subprocess.TimeoutExpired(command, 1))
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked


def test_task_3_timeout_retains_a_concurrent_output_failure(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _InterruptedProcess(subprocess.TimeoutExpired(command, 1))
    process.stdout = _FailingStdout()
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _SynchronousThread)
    patch_workspace_killpg(monkeypatch, lambda pid, sig: None)
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


class _NeverReapedProcess(_InterruptedProcess):
    def wait(self, timeout=None):
        self.wait_calls += 1
        raise subprocess.TimeoutExpired(("safe-tool",), timeout)


def test_task_3_reports_when_killed_foreground_process_cannot_be_reaped(
    tmp_path, monkeypatch
):
    command = ["safe-tool"]
    process = _NeverReapedProcess(None)
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


def test_task_3_reports_when_process_group_termination_fails(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _InterruptedProcess(subprocess.TimeoutExpired(command, 1))
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch,
        lambda pid, sig: (_ for _ in ()).throw(PermissionError("denied")),
    )
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert process.killed
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


def test_task_3_popen_failure_is_reported_as_launch_uncertainty(tmp_path, monkeypatch):
    command = ("safe-tool",)
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(command,)),
        confirm_tool=lambda action: True,
    )
    patch_workspace_popen(
        monkeypatch,
        lambda *args, **kwargs: (_ for _ in ()).throw(OSError("cannot start")),
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == "error: cannot start"
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


class _CompletedProcess:
    pid = 54321

    def __init__(self, returncode=0):
        self.stdout = _EmptyStdout()
        self.returncode = returncode
        self.wait_calls = 0

    def wait(self, timeout=None):
        self.wait_calls += 1
        return self.returncode

    def kill(self):
        pass


def test_task_3_started_nonzero_command_sets_side_effect_flag(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _CompletedProcess(returncode=7)
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    result = workspace.run_command(command)

    assert result == "exit code: 7"
    assert workspace.command_side_effects_untracked


class _LingeringReader:
    def __init__(self, *args, **kwargs):
        self.join_calls = 0

    def start(self):
        pass

    def join(self, timeout=None):
        self.join_calls += 1

    def is_alive(self):
        return True


def test_task_3_attempts_same_group_cleanup_when_the_output_pipe_lingers(
    tmp_path, monkeypatch
):
    command = ["safe-tool"]
    process = _CompletedProcess()
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _LingeringReader)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    result = workspace.run_command(command)

    assert result.startswith("exit code: 0")
    assert "command output abandoned" in result
    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_cleanup_incomplete


def test_task_3_dispatch_preserves_the_output_abandonment_warning(
    tmp_path, monkeypatch
):
    command = ("safe-tool",)
    process = _CompletedProcess()
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _LingeringReader)
    patch_workspace_killpg(monkeypatch, lambda pid, sig: None)
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(command,),
            max_tool_output_chars=64,
        ),
        confirm_tool=lambda action: True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert len(result) <= 64
    assert "command output abandoned" in result
    assert workspace.command_cleanup_incomplete


def test_task_3_dispatch_preserves_an_output_collection_failure(tmp_path, monkeypatch):
    command = ("safe-tool",)
    process = _CompletedProcess()
    process.stdout = _PartiallyFailingStdout()
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(command,),
            max_tool_output_chars=64,
        ),
        confirm_tool=lambda action: True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert len(result) <= 64
    assert "command output collection failed" in result
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


def test_task_3_untrusted_tool_text_cannot_fabricate_a_safety_warning(tmp_path):
    content = "command output abandoned\n" + "x" * 100
    (tmp_path / "output.txt").write_text(content, encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, max_tool_output_chars=64))

    result = workspace.execute(ToolAction("read_file", {"path": "output.txt"}))

    assert len(result) <= 64
    assert "warning: command output abandoned" not in result
    assert result.endswith("... tool output truncated")


class _InterruptingThread:
    def __init__(self, *args, **kwargs):
        pass

    def start(self):
        raise KeyboardInterrupt


class _FailingThread:
    def __init__(self, *args, **kwargs):
        pass

    def start(self):
        raise RuntimeError("cannot start output reader")


def test_task_3_interrupt_during_reader_setup_kills_and_reaps(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _CompletedProcess()
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _InterruptingThread)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    with pytest.raises(KeyboardInterrupt):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 1
    assert workspace.command_side_effects_untracked


def test_task_3_reader_setup_failure_becomes_a_reportable_tool_error(
    tmp_path, monkeypatch
):
    command = ("safe-tool",)
    process = _CompletedProcess()
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _FailingThread)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(command,)),
        confirm_tool=lambda action: True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == (
        "error: command runner failed after starting: cannot start output reader"
    )
    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 1
    assert workspace.command_side_effects_untracked


def _encode_context_messages(messages):
    """A deterministic encoder whose token count is not a character count."""

    rendered = json.dumps(
        messages,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return tuple(
        (sum(rendered[index : index + 8]) % 251) + 1
        for index in range(0, len(rendered), 8)
    )


def _context_policy(**changes):
    values = {
        "max_tokens": 800,
        "reserve_tokens": 630,
        "summary_max_tokens": 64,
        "max_tool_result_tokens": 48,
        "min_recent_turns": 1,
    }
    values.update(changes)
    return ContextPolicy(**values)


def _append_context_turn(session, number, *, result_words=80):
    response = json.dumps({"tool": "list_files", "path": f"part-{number}"})
    session.append("assistant_message", content=response)
    call = session.append(
        "tool_call",
        tool="list_files",
        arguments={"path": f"part-{number}"},
    )
    session.append(
        "tool_result",
        tool_call_id=call.id,
        tool="list_files",
        is_error=False,
        content=(f"result-{number} " * result_words).strip(),
    )


def _summary_payload(**changes):
    values = {
        "goal": "fix empty configuration parsing",
        "constraints": ["keep the public schema"],
        "facts": ["parse_value is in src/config.py"],
        "changed_files": ["src/config.py"],
        "validation": ["test_empty_value still fails"],
        "failed_approaches": ["changing the default broke another test"],
        "next_step": "inspect normalization",
    }
    values.update(changes)
    return json.loads(json.dumps(asdict(WorkingSummary(**values))))


def _events_of_type(session, event_type):
    return [event for event in session.events if event.type == event_type]


@pytest.mark.parametrize(
    "changes",
    [
        {"max_tokens": 0},
        {"reserve_tokens": 0},
        {"max_tokens": 50, "reserve_tokens": 50},
        {"summary_max_tokens": 0},
        {"max_tool_result_tokens": 0},
        {"min_recent_turns": -1},
    ],
)
def test_task_4_context_policy_rejects_impossible_budgets(changes):
    with pytest.raises(ValueError):
        _context_policy(**changes)


@pytest.mark.parametrize(
    "arguments",
    [
        ["task", "--max-tokens", "9000", "--reserve-tokens", "8192"],
        [
            "task",
            "--max-context-tokens",
            "100",
            "--summary-max-tokens",
            "100",
        ],
    ],
)
def test_task_4_cli_rejects_generation_budgets_outside_the_context_limit(
    arguments,
):
    parser = build_parser()
    parsed = parser.parse_args(arguments)

    with pytest.raises(SystemExit):
        validate_budget_arguments(parser, parsed)


def test_task_4_working_summary_has_an_explicit_stable_schema():
    summary = _summary_payload()
    value = WorkingSummary(
        goal="goal",
        constraints=["constraint"],
        facts=[],
        changed_files=[],
        validation=[],
        failed_approaches=[],
        next_step="continue",
    )

    assert list(summary) == [
        "goal",
        "constraints",
        "facts",
        "changed_files",
        "validation",
        "failed_approaches",
        "next_step",
    ]
    assert isinstance(summary["goal"], str)
    assert isinstance(summary["next_step"], str)
    assert all(
        isinstance(summary[field], list)
        for field in (
            "constraints",
            "facts",
            "changed_files",
            "validation",
            "failed_approaches",
        )
    )
    assert value.constraints == ("constraint",)
    with pytest.raises(AttributeError):
        value.constraints.append("mutable")


def test_task_4_under_threshold_uses_the_exact_encoder_without_summarizing(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect one small file", kind="task")
    encoded_messages = []

    def encode(messages):
        encoded_messages.append([dict(message) for message in messages])
        return _encode_context_messages(messages)

    def unexpected_summary(_messages):
        raise AssertionError("an under-budget context must not be summarized")

    original_events = session.events
    manager = ContextManager(
        encode,
        policy=_context_policy(max_tokens=512, reserve_tokens=64),
    )

    window = manager.prepare(session, "system", summarize=unexpected_summary)

    assert encoded_messages[-1] == list(window.messages)
    assert tuple(window.token_ids) == _encode_context_messages(window.messages)
    assert len(window.token_ids) < 512 - 64
    assert window.followed_compaction is False
    assert window.compaction_event_id is None
    assert window.visible_tool_result_bytes == 0
    assert session.events == original_events


def test_task_4_bounds_visible_tool_results_without_mutating_the_trace(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect generated output", kind="task")
    original_result = "private-output " * 400
    response = '{"tool":"read_file","path":"output.txt"}'
    session.append("assistant_message", content=response)
    call = session.append(
        "tool_call",
        tool="read_file",
        arguments={"path": "output.txt"},
    )
    result = session.append(
        "tool_result",
        tool_call_id=call.id,
        tool="read_file",
        is_error=False,
        content=original_result,
    )
    original_events = session.events
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(
            max_tokens=512,
            reserve_tokens=64,
            max_tool_result_tokens=12,
        ),
    )

    window = manager.prepare(session, "system")

    visible_results = [
        message["content"].removeprefix("Tool result:\n")
        for message in window.messages
        if message["content"].startswith("Tool result:\n")
    ]
    assert len(visible_results) == 1
    assert "omitted" in visible_results[0].lower()
    assert len(visible_results[0]) < len(original_result)
    assert window.visible_tool_result_bytes == len(visible_results[0].encode("utf-8"))
    assert window.followed_compaction is False
    assert session.events == original_events
    assert session.events[-1].id == result.id
    assert session.events[-1].data["content"] == original_result


def test_task_4_impossible_tool_result_budget_fails_closed(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect output", kind="task")
    session.append("assistant_message", content='{"tool":"read_file"}')
    call = session.append("tool_call", tool="read_file", arguments={})
    session.append(
        "tool_result",
        tool_call_id=call.id,
        tool="read_file",
        is_error=False,
        content="private output " * 40,
    )
    original_events = session.events
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(
            max_tokens=512,
            reserve_tokens=64,
            max_tool_result_tokens=1,
        ),
    )

    with pytest.raises(ContextLimitError):
        manager.prepare(session, "system")

    assert session.events == original_events


def test_task_4_successful_compaction_is_durable_and_model_visible(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="fix the parser", kind="task")
    for number in range(6):
        _append_context_turn(session, number)
    original_events = session.events
    expected_summary = _summary_payload(changed_files=[], validation=[])
    summary_inputs = []

    def summarize(messages):
        summary_inputs.append([dict(message) for message in messages])
        return json.dumps(expected_summary)

    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    window = manager.prepare(session, "system", summarize=summarize)

    attempts = _events_of_type(session, "summary_attempt")
    compactions = _events_of_type(session, "compaction")
    assert len(summary_inputs) == len(attempts) == len(compactions) == 1
    assert "exactly this schema" in summary_inputs[0][0]["content"]
    assert summary_inputs[0][-1]["content"].startswith("Return the bounded")
    assert attempts[0].data == {
        "status": "accepted",
        "response": json.dumps(expected_summary),
        "error": None,
    }
    event = compactions[0]
    assert event.data["summary"] == expected_summary
    assert event.data["strategy"] == "model"
    assert event.data["fallback_reason"] is None
    assert event.data["covered_through_event_id"] in {
        item.id for item in original_events
    }
    assert event.data["input_tokens_before"] > event.data["input_tokens_after"]
    assert window.followed_compaction is True
    assert window.compaction_event_id == event.id
    assert tuple(session.events[: len(original_events)]) == original_events
    rendered = "\n".join(message["content"] for message in window.messages)
    assert expected_summary["facts"][0] in rendered
    assert expected_summary["next_step"] in rendered


@pytest.mark.parametrize(
    ("failure", "attempt_status"),
    [
        ("malformed", "invalid"),
        ("missing-field", "invalid"),
        ("extra-field", "invalid"),
        ("wrong-type", "invalid"),
        ("exception", "error"),
    ],
)
def test_task_4_invalid_summaries_get_one_attempt_then_fall_back(
    tmp_path, failure, attempt_status
):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="fix the parser", kind="task")
    for number in range(6):
        _append_context_turn(session, number)
    calls = 0

    def summarize(_messages):
        nonlocal calls
        calls += 1
        if failure == "exception":
            raise RuntimeError("summary backend unavailable")
        if failure == "malformed":
            return "not JSON"
        candidate = _summary_payload()
        if failure == "missing-field":
            candidate.pop("facts")
        elif failure == "extra-field":
            candidate["confidence"] = 1
        else:
            candidate["constraints"] = "not a list"
        return json.dumps(candidate)

    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    window = manager.prepare(session, "system", summarize=summarize)

    attempts = _events_of_type(session, "summary_attempt")
    compactions = _events_of_type(session, "compaction")
    assert calls == len(attempts) == len(compactions) == 1
    assert attempts[0].data["status"] == attempt_status
    event = compactions[0]
    assert event.data["strategy"] == "deterministic"
    assert isinstance(event.data["fallback_reason"], str)
    assert event.data["fallback_reason"]
    assert set(event.data["summary"]) == set(_summary_payload())
    assert isinstance(event.data["summary"]["goal"], str)
    assert isinstance(event.data["summary"]["next_step"], str)
    assert all(
        isinstance(event.data["summary"][field], list)
        for field in (
            "constraints",
            "facts",
            "changed_files",
            "validation",
            "failed_approaches",
        )
    )
    assert window.followed_compaction is True
    assert len(window.token_ids) <= manager.policy.working_tokens


def test_task_4_oversized_summary_request_falls_back_without_calling_model(
    tmp_path,
):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="fix the parser", kind="task")
    for number in range(6):
        _append_context_turn(session, number)
    calls = 0

    def summarize(_messages):
        nonlocal calls
        calls += 1
        return json.dumps(_summary_payload())

    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(max_tokens=220, reserve_tokens=50),
    )

    window = manager.prepare(session, "system", summarize=summarize)

    assert calls == 0
    attempt = _events_of_type(session, "summary_attempt")[-1]
    assert attempt.data["status"] == "invalid"
    assert "exceeds max_tokens" in attempt.data["error"]
    assert _events_of_type(session, "compaction")[-1].data["strategy"] == (
        "deterministic"
    )
    assert len(window.token_ids) <= manager.policy.working_tokens


def test_task_4_repeated_compaction_advances_without_resummarizing_same_events(
    tmp_path,
):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="finish the migration", kind="task")
    for number in range(6):
        _append_context_turn(session, number)
    calls = 0

    def summarize(_messages):
        nonlocal calls
        calls += 1
        return json.dumps(
            _summary_payload(
                facts=[f"completed compaction {calls}"],
                next_step=f"continue after compaction {calls}",
            )
        )

    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    first = manager.prepare(session, "system", summarize=summarize)
    manager.prepare(session, "system", summarize=summarize)
    assert calls == 1
    assert len(_events_of_type(session, "compaction")) == 1
    for number in range(6, 12):
        _append_context_turn(session, number)
    second = manager.prepare(session, "system", summarize=summarize)

    compactions = _events_of_type(session, "compaction")
    assert calls == len(compactions) == 2
    assert first.compaction_event_id == compactions[0].id
    assert second.compaction_event_id == compactions[1].id
    assert (
        compactions[0].data["covered_through_event_id"]
        != compactions[1].data["covered_through_event_id"]
    )
    assert "completed compaction 2" in "\n".join(
        message["content"] for message in second.messages
    )


def test_task_4_anchor_overflow_fails_before_calling_the_summarizer(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="essential-task " * 300, kind="task")
    calls = 0

    def summarize(_messages):
        nonlocal calls
        calls += 1
        return json.dumps(_summary_payload())

    original_events = session.events
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(max_tokens=80, reserve_tokens=20),
    )

    with pytest.raises(ContextLimitError):
        manager.prepare(session, "system", summarize=summarize)

    assert calls == 0
    assert session.events == original_events


def test_task_4_deterministic_summary_keeps_structured_change_facts(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="repair configuration parsing", kind="task")
    edit_response = json.dumps(
        {
            "tool": "edit_file",
            "path": "src/config.py",
            "old": "return raw",
            "new": "return normalize(raw)",
        }
    )
    session.append("assistant_message", content=edit_response)
    edit_call = session.append(
        "tool_call",
        tool="edit_file",
        arguments={
            "path": "src/config.py",
            "old": "return raw",
            "new": "return normalize(raw)",
        },
    )
    session.append(
        "tool_result",
        tool_call_id=edit_call.id,
        tool="edit_file",
        is_error=False,
        content="wrote src/config.py",
    )
    command_response = json.dumps(
        {"tool": "run_command", "argv": ["safe-test", "config"]}
    )
    session.append("assistant_message", content=command_response)
    command_call = session.append(
        "tool_call",
        tool="run_command",
        arguments={"argv": ["safe-test", "config"]},
    )
    session.append(
        "tool_result",
        tool_call_id=command_call.id,
        tool="run_command",
        is_error=False,
        content="exit code: 7\ntest_empty_value failed",
    )
    for number in range(6):
        _append_context_turn(session, number)
    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    manager.prepare(session, "system", summarize=lambda _messages: "invalid")

    summary = _events_of_type(session, "compaction")[-1].data["summary"]
    assert "src/config.py" in summary["changed_files"]
    assert any("edit_file" in fact for fact in summary["facts"])
    assert any("exit code: 7" in result for result in summary["validation"])


def test_task_4_model_summary_cannot_claim_a_failed_change_or_fake_validation(
    tmp_path,
):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="repair the parser", kind="task")
    session.append(
        "assistant_message",
        content='{"tool":"edit_file","path":"src/config.py"}',
    )
    call = session.append(
        "tool_call",
        tool="edit_file",
        arguments={"path": "src/config.py", "old": "x", "new": "y"},
    )
    session.append(
        "tool_result",
        tool_call_id=call.id,
        tool="edit_file",
        is_error=True,
        content="error: operator denied edit_file",
    )
    for number in range(6):
        _append_context_turn(session, number)
    claimed = _summary_payload(
        changed_files=["src/config.py", "outside.txt"],
        validation=["all tests passed"],
    )
    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    manager.prepare(
        session,
        "system",
        summarize=lambda _messages: json.dumps(claimed),
    )

    summary = _events_of_type(session, "compaction")[-1].data["summary"]
    assert summary["changed_files"] == []
    assert summary["validation"] == []


def test_task_4_compacts_tool_free_follow_up_sessions(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="initial goal", kind="task")
    for number in range(6):
        if number:
            session.append(
                "user_message", content=f"follow up {number}", kind="follow_up"
            )
        session.append(
            "assistant_message",
            content=(f"completed conversational turn {number} " * 10).strip(),
        )
        session.append("run_finished", completed=True, reason="completed", final="ok")
    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    window = manager.prepare(
        session,
        "system",
        summarize=lambda _messages: json.dumps(
            _summary_payload(changed_files=[], validation=[])
        ),
    )

    assert window.followed_compaction is True
    assert "follow up 5" in "\n".join(message["content"] for message in window.messages)


def test_task_4_min_recent_turns_ignores_an_empty_run_finished_event(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect files", kind="task")
    result_events = []
    for number in range(5):
        _append_context_turn(session, number)
        result_events.append(session.events[-1])
    session.append("run_finished", completed=False, reason="step_limit", final=None)
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(
            max_tokens=1_000,
            reserve_tokens=780,
            min_recent_turns=2,
        ),
    )

    window = manager.prepare(
        session,
        "system",
        summarize=lambda _messages: json.dumps(
            _summary_payload(changed_files=[], validation=[])
        ),
    )

    compaction = _events_of_type(session, "compaction")[-1]
    assert compaction.data["covered_through_event_id"] == result_events[2].id
    rendered = "\n".join(message["content"] for message in window.messages)
    assert "result-3" in rendered
    assert "result-4" in rendered


def test_task_4_dangling_assistant_is_not_a_compaction_boundary(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect files", kind="task")
    session.append("assistant_message", content="unfinished " * 300)
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(max_tokens=100, reserve_tokens=20),
    )

    with pytest.raises(ContextLimitError):
        manager.prepare(session, "system")

    assert _events_of_type(session, "compaction") == []


def test_task_4_rejects_non_monotonic_durable_compaction_boundaries(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect files", kind="task")
    for number in range(4):
        _append_context_turn(session, number)
    manager = ContextManager(_encode_context_messages, policy=_context_policy())
    manager.prepare(session, "system")
    first = _events_of_type(session, "compaction")[-1]
    session.append(
        "compaction",
        covered_through_event_id=first.data["covered_through_event_id"],
        strategy="deterministic",
        fallback_reason="synthetic corruption",
        summary=first.data["summary"],
        input_tokens_before=10,
        input_tokens_after=5,
    )
    original_events = session.events

    with pytest.raises(ContextLimitError):
        manager.prepare(session, "system")

    assert session.events == original_events


def test_task_4_rejects_compaction_with_unstructured_protected_facts(tmp_path):
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="inspect files", kind="task")
    for number in range(3):
        _append_context_turn(session, number)
    boundary = _events_of_type(session, "tool_result")[0]
    session.append(
        "compaction",
        covered_through_event_id=boundary.id,
        strategy="deterministic",
        fallback_reason="synthetic marker",
        summary=_summary_payload(
            changed_files=["unverified.txt"], validation=["tests passed"]
        ),
        input_tokens_before=300,
        input_tokens_after=100,
    )
    manager = ContextManager(_encode_context_messages, policy=_context_policy())

    with pytest.raises(ContextLimitError, match="protected facts"):
        manager.prepare(session, "system")


def test_task_4_compaction_round_trips_through_the_disk_session_store(tmp_path):
    store = SessionStore(tmp_path, "test-model")
    session = store.create()
    session.append("user_message", content="inspect files", kind="task")
    for number in range(6):
        _append_context_turn(session, number)
    manager = ContextManager(_encode_context_messages, policy=_context_policy())
    first = manager.prepare(session, "system")

    reloaded = store.load(session.session_id)
    before = reloaded.events
    replayed = manager.prepare(reloaded, "system")

    assert first.followed_compaction is True
    assert replayed.followed_compaction is False
    assert reloaded.events == before
    assert "Working summary:" in "\n".join(
        message["content"] for message in replayed.messages
    )


def test_task_4_loop_uses_exact_window_and_records_context_metrics(tmp_path):
    session = memory_session(tmp_path, "test-model")
    workspace = Workspace(ToolPolicy(tmp_path))
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(max_tokens=512, reserve_tokens=64),
    )
    requests = []

    def generate(messages):
        requests.append([dict(message) for message in messages])
        return '{"final":"done"}'

    result = run_agent(
        "inspect the workspace",
        generate,
        workspace,
        AgentLimits(max_steps=1),
        session=session,
        context_manager=manager,
    )

    assert result.completed is True
    assistant = _events_of_type(session, "assistant_message")[-1]
    assert assistant.data["context"]["input_tokens"] == len(
        _encode_context_messages(requests[0])
    )
    assert assistant.data["context"]["followed_compaction"] is False
    assert assistant.data["generation"] is None


def test_task_4_loop_stops_before_generation_when_anchors_cannot_fit(tmp_path):
    session = memory_session(tmp_path, "test-model")
    workspace = Workspace(ToolPolicy(tmp_path))
    manager = ContextManager(
        _encode_context_messages,
        policy=_context_policy(max_tokens=80, reserve_tokens=20),
    )
    calls = 0

    def generate(_messages):
        nonlocal calls
        calls += 1
        return '{"final":"unsafe"}'

    result = run_agent(
        "essential task " * 300,
        generate,
        workspace,
        AgentLimits(max_steps=1),
        session=session,
        context_manager=manager,
    )

    assert result.reason == "context_limit"
    assert calls == 0


class _ContextCache:
    def __init__(self):
        self.offset = 0

    def rewind(self, count):
        if count < 0 or count > self.offset:
            raise ValueError("invalid rewind")
        self.offset -= count

    def release(self):
        pass


class _ContextArray:
    def __init__(self, values):
        self.values = list(values)

    def __getitem__(self, _key):
        return self


class _ContextLogits:
    def __init__(self, token):
        self.token = token

    def __getitem__(self, _key):
        return self


class _ContextScalar:
    def __init__(self, value):
        self.value = value

    def item(self):
        return self.value


class _ContextTokenizer:
    eos_token_id = 0

    def apply_chat_template(self, messages, **_kwargs):
        return "|".join(
            f"{message['role']}:{message['content']}" for message in messages
        )

    def encode(self, prompt, **_kwargs):
        return [(ord(character) % 251) + 1 for character in prompt]

    def decode(self, tokens):
        return ",".join(map(str, tokens))


class _ContextModel:
    def __call__(self, tokens, _offset, caches):
        for cache in caches:
            cache.offset += len(tokens.values)
        return _ContextLogits(7)


def _install_context_mlx(monkeypatch):
    mlx = ModuleType("mlx")
    core = ModuleType("mlx.core")
    core.array = _ContextArray
    core.argmax = lambda logits, axis: _ContextScalar(logits.token)
    mlx.core = core
    monkeypatch.setitem(sys.modules, "mlx", mlx)
    monkeypatch.setitem(sys.modules, "mlx.core", core)


def test_task_5_compaction_reconciles_the_warm_cache_and_records_metrics(
    tmp_path, monkeypatch
):
    _install_context_mlx(monkeypatch)
    session = memory_session(tmp_path, "test-model")
    session.append("user_message", content="fix parser", kind="task")
    for number in range(6):
        _append_context_turn(session, number)
    caches = [_ContextCache(), _ContextCache()]
    generation = GenerationSession(
        _ContextModel(),
        _ContextTokenizer(),
        lambda: caches,
        max_tokens=1,
    )
    generation(session.messages("system"))
    manager = ContextManager(
        generation.encode_messages,
        policy=_context_policy(
            max_tokens=800,
            reserve_tokens=120,
            summary_max_tokens=320,
            max_tool_result_tokens=180,
        ),
    )
    window = manager.prepare(
        session,
        "system",
        summarize=lambda _messages: json.dumps(
            _summary_payload(
                constraints=[],
                validation=[],
                failed_approaches=[],
            )
        ),
    )

    warm_response = generation(list(window.messages))
    cold_caches = [_ContextCache(), _ContextCache()]
    cold_generation = GenerationSession(
        _ContextModel(),
        _ContextTokenizer(),
        lambda: cold_caches,
        max_tokens=1,
    )
    cold_response = cold_generation(list(window.messages))

    stats = generation.last_stats
    assert warm_response == cold_response
    assert stats.input_tokens == len(window.token_ids)
    assert stats.reused_tokens > 0
    assert stats.rewound_tokens > 0
    assert stats.prefilled_tokens > 0
    assert stats.cold_start is False
    assert stats.latency_seconds is not None
    assert stats.latency_seconds >= 0
