# WARNING: Under review - generated by LLM.

"""Course-code guards for the cumulative Week 4 Day 1--5 starter."""

import ast
import importlib.util
import io
import re
import sys
from contextlib import redirect_stdout
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

STARTER = ROOT / "src" / "tiny_llm" / "agent"
REFSOL = ROOT / "src" / "tiny_llm_ref" / "agent"
REAL_MODEL_CLI = ROOT / "agent.py"
MODULES = (
    "checkpoint",
    "compaction",
    "generation",
    "loop",
    "protocol",
    "receipts",
    "workspace",
)


def _tree(root: Path, module: str) -> ast.Module:
    return ast.parse((root / f"{module}.py").read_text(encoding="utf-8"))


def _public_surface(root: Path, module: str) -> dict[str, tuple]:
    """Return public classes/functions and their exact signatures."""

    surface = {}
    for node in _tree(root, module).body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            methods = tuple(
                (item.name, ast.unparse(item.args), ast.unparse(item.returns))
                for item in node.body
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
                and not item.name.startswith("_")
            )
            surface[node.name] = methods
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not (
            node.name.startswith("_")
        ):
            surface[node.name] = (ast.unparse(node.args), ast.unparse(node.returns))
    return surface


def _dataclass_fields(root: Path, module: str) -> dict[str, tuple]:
    fields = {}
    for node in _tree(root, module).body:
        if not isinstance(node, ast.ClassDef):
            continue
        if not any(
            isinstance(decorator, ast.Name)
            and decorator.id == "dataclass"
            or isinstance(decorator, ast.Call)
            and isinstance(decorator.func, ast.Name)
            and decorator.func.id == "dataclass"
            for decorator in node.decorator_list
        ):
            continue
        fields[node.name] = tuple(
            (
                item.target.id,
                ast.unparse(item.annotation),
                ast.unparse(item.value) if item.value is not None else "<required>",
            )
            for item in node.body
            if isinstance(item, ast.AnnAssign)
            and isinstance(item.target, ast.Name)
            and not item.target.id.startswith("_")
        )
    return fields


def _public_bodies(root: Path, module: str):
    for node in _tree(root, module).body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and not (
                    item.name.startswith("_")
                ):
                    yield f"{node.name}.{item.name}", item.body
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not (
            node.name.startswith("_")
        ):
            yield node.name, node.body


def _is_stub(body) -> bool:
    return not [
        statement
        for statement in body
        if not isinstance(statement, ast.Pass)
        and not (
            isinstance(statement, ast.Expr)
            and isinstance(statement.value, ast.Constant)
            and isinstance(statement.value.value, str)
        )
    ]


@pytest.mark.parametrize("module", MODULES)
def test_starter_public_contract_matches_reference(module):
    assert _public_surface(STARTER, module) == _public_surface(REFSOL, module)
    assert _dataclass_fields(STARTER, module) == _dataclass_fields(REFSOL, module)


@pytest.mark.parametrize("module", MODULES)
def test_starter_is_solution_free_and_reference_is_implemented(module):
    reference = dict(_public_bodies(REFSOL, module))
    for name, body in _public_bodies(STARTER, module):
        assert _is_stub(body), f"starter {module}.{name} contains solution logic"
        assert name in reference and not _is_stub(reference[name]), (
            f"reference {module}.{name} must implement the starter declaration"
        )


def test_package_exports_match_the_published_day_5_surface():
    import tiny_llm.agent as starter
    import tiny_llm_ref.agent as refsol

    expected = {
        "AgentError",
        "AgentCheckpoint",
        "AgentEvent",
        "AgentLimits",
        "AgentRun",
        "CompactionResult",
        "EffectReceipt",
        "FinalAction",
        "ModelCheckpoint",
        "ReceiptStore",
        "ToolAction",
        "ToolPolicy",
        "Workspace",
        "build_system_prompt",
        "compact_completed_interactions",
        "create_checkpoint",
        "generate_response",
        "initial_messages",
        "parse_action",
        "resume_agent",
        "run_agent",
        "run_to_checkpoint",
    }
    assert set(starter.__all__) == set(refsol.__all__) == expected


def test_only_day_1_through_day_5_modules_exist_in_the_starter():
    allowed = {
        "__init__.py",
        "checkpoint.py",
        "compaction.py",
        "generation.py",
        "loop.py",
        "protocol.py",
        "receipts.py",
        "workspace.py",
    }
    assert {path.name for path in STARTER.glob("*.py")} == allowed


def test_day_3_workspace_surface_remains_complete():
    surface = _public_surface(STARTER, "workspace")
    assert set(surface) == {"ToolPolicy", "Workspace"}
    assert {name for name, *_ in surface["Workspace"]} == {
        "available_tools",
        "modified_files",
        "resolve_path",
        "list_files",
        "read_file",
        "write_file",
        "edit_file",
        "run_command",
        "execute",
    }
    receipts = _public_surface(STARTER, "receipts")
    assert set(receipts) == {"EffectReceipt", "ReceiptStore"}


def test_day_4_checkpoint_surface_is_complete_and_has_no_day_6_api():
    checkpoint = _public_surface(STARTER, "checkpoint")
    assert set(checkpoint) == {
        "AgentCheckpoint",
        "ModelCheckpoint",
        "create_checkpoint",
    }
    assert {name for name, *_ in checkpoint["AgentCheckpoint"]} == {"validate"}
    loop = _public_surface(STARTER, "loop")
    assert {"run_to_checkpoint", "resume_agent"} <= set(loop)
    source = "\n".join(
        path.read_text(encoding="utf-8") for path in STARTER.glob("*.py")
    )
    for future_name in ("Session", "rewind", "steering"):
        assert future_name not in source


def test_day_5_compaction_surface_is_complete():
    compaction = _public_surface(STARTER, "compaction")
    assert set(compaction) == {
        "CompactionResult",
        "compact_completed_interactions",
    }
    assert {name for name, *_ in compaction["CompactionResult"]} == {"saved_tokens"}


def test_removed_catalog_hash_is_not_exported_or_declared():
    for root in (STARTER, REFSOL):
        source = (root / "protocol.py").read_text(encoding="utf-8")
        assert "TOOL_CATALOG_HASH" not in source
        assert "tool_catalog_hash" not in source


def test_starter_does_not_import_the_reference_solution():
    for path in STARTER.glob("*.py"):
        source = path.read_text(encoding="utf-8")
        assert "tiny_llm_ref" not in source


def test_real_model_cli_exposes_only_the_learner_package():
    source = REAL_MODEL_CLI.read_text(encoding="utf-8")
    tree = ast.parse(source)
    assert "tiny_llm_ref" not in source
    assert "importlib" not in source
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "tiny_llm"
        and any(alias.name == "agent" for alias in node.names)
        for node in tree.body
    )

    spec = importlib.util.spec_from_file_location(
        "week4_real_model_cli", REAL_MODEL_CLI
    )
    assert spec is not None and spec.loader is not None
    cli = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cli)
    parser = cli.build_parser()
    help_text = parser.format_help()
    assert "--solution" not in help_text
    assert "tiny_llm_ref" not in help_text
    assert re.search(r"\bref\b", help_text) is None
    assert all(action.dest != "solution" for action in parser._actions)
    args = parser.parse_args(["--root", str(ROOT), "inspect", "this", "workspace"])
    assert not hasattr(args, "solution")


def test_real_model_cli_discloses_command_side_effect_scope(tmp_path, monkeypatch):
    import tiny_llm_ref.agent as ref_agent

    spec = importlib.util.spec_from_file_location(
        "week4_real_model_cli", REAL_MODEL_CLI
    )
    assert spec is not None and spec.loader is not None
    cli = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cli)

    command = (sys.executable, "-c", "from pathlib import Path; Path('extra').touch()")
    monkeypatch.setattr(sys, "stdin", io.StringIO("y\n"))
    monkeypatch.setattr(sys.stdin, "isatty", lambda: True)
    output = io.StringIO()
    with redirect_stdout(output):
        workspace = ref_agent.Workspace(
            ref_agent.ToolPolicy(tmp_path, allowed_commands=(command,)),
            cli.confirm_tool,
        )
        result = workspace.execute(
            ref_agent.ToolAction("run_command", {"argv": list(command)})
        )
        cli.show_file_tool_changes(workspace.modified_files)

    assert (tmp_path / "extra").is_file()
    assert result.startswith("status: 0")
    text = output.getvalue()
    assert "file-tool changes> []" in text
    assert "approved commands may create or change additional filesystem paths" in text
    assert (
        "command receipts record the command and result, not a complete filesystem diff"
        in text
    )
