# WARNING: Under review - generated by LLM.

"""Week 4 Day 8 cached fork, steering, and selection course-code tests."""

import json
import shutil
import sys
from dataclasses import replace

import mlx.core as mx
import pytest

from .tiny_llm_base import (
    AgentError,
    ApprovalDecision,
    EvaluationCase,
    FileExpectation,
    KvPrefixGenerator,
    ModelCheckpoint,
    PrefixReuse,
    ReceiptExpectation,
    ReceiptStore,
    ResultExpectation,
    ToolAction,
    ToolPolicy,
    Workspace,
    run_branch,
    run_to_checkpoint,
    select_branch,
)


class CharacterTokenizer:
    eos_token_id = 0

    def apply_chat_template(
        self,
        messages,
        *,
        tokenize,
        add_generation_prompt,
        enable_thinking,
    ):
        assert tokenize is False
        assert enable_thinking is False
        rendered = "".join(
            f"<{message['role']}>{message['content']}\n" for message in messages
        )
        if add_generation_prompt:
            rendered += "<assistant>"
        return rendered

    @staticmethod
    def encode(text, *, add_special_tokens):
        assert add_special_tokens is False
        return [ord(character) for character in text]

    @staticmethod
    def decode(tokens):
        return "".join(chr(token) for token in tokens)


class DenseEosModel:
    """Populate real dense caches, then emit EOS immediately."""

    num_hidden_layers = 2

    def __init__(self):
        self.calls = []

    def __call__(self, tokens, offset, caches, logits_to_keep=None):
        assert logits_to_keep == 1
        size = int(tokens.shape[1])
        before = tuple(
            None if cache.key_values is None else id(cache.key_values[0])
            for cache in caches
        )
        keys = mx.reshape(tokens.astype(mx.float32), (1, 1, size, 1))
        for layer, cache in enumerate(caches):
            cache.update_and_fetch(keys + layer, keys + layer)
        after = tuple(id(cache.key_values[0]) for cache in caches)
        self.calls.append((offset, size, tuple(caches), before, after))
        return mx.concatenate(
            [mx.ones((1, size, 1)), mx.zeros((1, size, 127))], axis=-1
        )


class ScriptedCheckpointModel:
    """Resume deterministic responses while exposing the recorded reuse facts."""

    def __init__(self, responses):
        self.responses = tuple(responses)
        self.response_index = 0
        self.calls = []
        self.reuse = PrefixReuse(0, (), 0)

    @staticmethod
    def _tokens(messages):
        return tuple(len(message["content"]) for message in messages)

    def __call__(self, messages):
        self.calls.append([dict(message) for message in messages])
        response = self.responses[self.response_index]
        self.response_index += 1
        return response

    def save_checkpoint(self, messages):
        tokens = self._tokens(messages)
        return ModelCheckpoint(
            len(messages), self.response_index, tokens, (len(tokens), len(tokens))
        )

    def restore_checkpoint(self, checkpoint):
        self.response_index = checkpoint.response_index
        self.reuse = PrefixReuse(
            len(checkpoint.cached_token_ids),
            checkpoint.layer_offsets,
            len(checkpoint.cached_token_ids),
        )


def test_task_1_structured_denial_requires_and_exposes_one_operator_reason(tmp_path):
    (tmp_path / "app.py").write_text("answer = 2\n", encoding="utf-8")
    receipts = ReceiptStore(tmp_path / "receipts.jsonl")
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        lambda _action: ApprovalDecision(False, "keep the requested answer at 2"),
        receipts,
    )
    workspace.read_file("app.py")
    action = ToolAction("edit_file", {"path": "app.py", "old": "2", "new": "3"})

    result = workspace.execute(action)

    assert result == (
        "error: operator denied the tool action: keep the requested answer at 2"
    )
    assert result.count("keep the requested answer at 2") == 1
    assert (tmp_path / "app.py").read_text(encoding="utf-8") == "answer = 2\n"
    assert receipts.get("call-1") is None
    with pytest.raises(ValueError, match="nonblank operator reason"):
        ApprovalDecision(False, "  ")


def test_task_1_legacy_boolean_approval_remains_compatible(tmp_path):
    (tmp_path / "app.py").write_text("answer = 1\n", encoding="utf-8")
    allowed = Workspace(ToolPolicy(tmp_path, allow_writes=True), lambda _action: True)
    allowed.read_file("app.py")
    assert (
        allowed.execute(
            ToolAction("edit_file", {"path": "app.py", "old": "1", "new": "2"})
        )
        == "edited app.py"
    )
    denied = Workspace(ToolPolicy(tmp_path, allow_writes=True), lambda _action: False)
    denied.read_file("app.py")
    assert (
        denied.execute(
            ToolAction("edit_file", {"path": "app.py", "old": "2", "new": "3"})
        )
        == "error: operator denied the tool action"
    )


def test_task_2_cached_prefix_is_prefilled_once_and_reused_by_both_forks():
    model = DenseEosModel()
    generator = KvPrefixGenerator(model, CharacterTokenizer(), max_tokens=4)
    messages = [
        {"role": "system", "content": "system"},
        {"role": "user", "content": "task"},
        {"role": "assistant", "content": '{"tool":"read_file","path":"app.py"}'},
        {"role": "user", "content": "Tool result:\nanswer = 2\n"},
    ]
    checkpoint = generator.save_checkpoint(messages)
    first = generator.fork()
    second = generator.fork()
    first.restore_checkpoint(checkpoint)
    second.restore_checkpoint(checkpoint)

    assert (
        first([*messages, {"role": "user", "content": "Operator steering:\nvalidate"}])
        == ""
    )
    assert (
        second([*messages, {"role": "user", "content": "Operator steering:\ninspect"}])
        == ""
    )

    prefix_call, first_call, second_call = model.calls
    assert prefix_call[0] == 0
    assert prefix_call[1] == len(checkpoint.cached_token_ids)
    assert first_call[0] == second_call[0] == len(checkpoint.cached_token_ids)
    assert all(
        first_cache is not second_cache
        for first_cache, second_cache in zip(first_call[2], second_call[2], strict=True)
    )
    assert first_call[3] == second_call[3] == prefix_call[4]
    assert first_call[4] != first_call[3]
    assert second_call[4] != second_call[3]
    assert (
        first.reuse
        == second.reuse
        == PrefixReuse(
            len(checkpoint.cached_token_ids),
            checkpoint.layer_offsets,
            len(checkpoint.cached_token_ids),
        )
    )
    assert checkpoint.layer_offsets == (
        len(checkpoint.cached_token_ids),
        len(checkpoint.cached_token_ids),
    )


def test_task_3_steered_prompt_must_extend_the_exact_saved_token_prefix():
    generator = KvPrefixGenerator(DenseEosModel(), CharacterTokenizer(), 2)
    messages = [
        {"role": "system", "content": "system"},
        {"role": "user", "content": "task"},
    ]
    checkpoint = generator.save_checkpoint(messages)
    branch = generator.fork()
    foreign_generator = KvPrefixGenerator(DenseEosModel(), CharacterTokenizer(), 2)
    foreign_checkpoint = foreign_generator.save_checkpoint(
        [
            {"role": "system", "content": "foreign system"},
            {"role": "user", "content": "foreign task"},
        ]
    )

    with pytest.raises(AgentError, match="does not match the saved KV prefix"):
        branch.restore_checkpoint(foreign_checkpoint)
    branch.restore_checkpoint(checkpoint)
    changed = [
        {"role": "system", "content": "changed"},
        {"role": "user", "content": "task"},
        {"role": "user", "content": "Operator steering:\ncontinue"},
    ]

    with pytest.raises(AgentError, match="does not extend the saved token prefix"):
        branch(changed)


def _forkable_effect(tmp_path):
    base = tmp_path / "base"
    base.mkdir()
    (base / "app.py").write_text("answer = 1\n", encoding="utf-8")
    receipts = ReceiptStore(base / "receipts.jsonl")
    workspace = Workspace(
        ToolPolicy(base, allow_writes=True), lambda _action: True, receipts
    )
    responses = (
        '{"tool":"read_file","path":"app.py"}',
        '{"tool":"edit_file","path":"app.py","old":"1","new":"2"}',
    )
    checkpoint = run_to_checkpoint(
        "set answer = 2 and validate",
        ScriptedCheckpointModel(responses),
        workspace,
        after_tool_calls=2,
    )
    return base, checkpoint


def _copy_branch(base, destination, command, approval):
    shutil.copytree(base, destination)
    receipts = ReceiptStore(destination / "receipts.jsonl")
    workspace = Workspace(
        ToolPolicy(
            destination,
            allow_writes=True,
            allowed_commands=(command,),
        ),
        approval,
        receipts,
    )
    return workspace, receipts


def test_task_4_forks_effects_and_receipts_then_isolates_later_branch_evidence(
    tmp_path,
):
    base, checkpoint = _forkable_effect(tmp_path)
    initial_receipts = (base / "receipts.jsonl").read_bytes()
    command = (
        sys.executable,
        "-c",
        "from pathlib import Path; assert Path('app.py').read_text() == 'answer = 2\\n'; print('validation passed')",
    )
    validate_workspace, validate_receipts = _copy_branch(
        base, tmp_path / "validate-only", command, lambda _action: True
    )
    denied_workspace, denied_receipts = _copy_branch(
        base,
        tmp_path / "try-extra-edit",
        command,
        lambda _action: ApprovalDecision(False, "keep the requested answer at 2"),
    )
    assert (validate_receipts.path.read_bytes(), denied_receipts.path.read_bytes()) == (
        initial_receipts,
        initial_receipts,
    )

    case = EvaluationCase(
        final_contains="validated",
        files=(FileExpectation("app.py", "answer = 2\n"),),
        results=(ResultExpectation("run_command", "validation passed"),),
        receipts=(
            ReceiptExpectation(
                "call-1", "edit_file", "ok", "edited app.py", ("app.py",)
            ),
            ReceiptExpectation("call-2", "run_command", "ok", "validation passed"),
        ),
    )
    validate_responses = (
        "unused read",
        "unused edit",
        json.dumps({"tool": "run_command", "argv": list(command)}),
        '{"final":"validated answer = 2"}',
    )
    denied_responses = (
        "unused read",
        "unused edit",
        '{"tool":"read_file","path":"app.py"}',
        '{"tool":"edit_file","path":"app.py","old":"2","new":"3"}',
        '{"final":"the extra edit was denied"}',
    )
    validate_model = ScriptedCheckpointModel(validate_responses)
    denied_model = ScriptedCheckpointModel(denied_responses)

    passing = run_branch(
        "validate-only",
        "validate without another edit",
        checkpoint,
        validate_model,
        validate_workspace,
        validate_receipts,
        case,
    )
    failing = run_branch(
        "try-extra-edit",
        "try changing the answer again",
        checkpoint,
        denied_model,
        denied_workspace,
        denied_receipts,
        case,
    )

    validate_steering = "validate without another edit"
    denied_steering = "try changing the answer again"
    assert passing.steering == validate_steering
    assert failing.steering == denied_steering
    assert validate_model.calls[0][-1] == {
        "role": "user",
        "content": f"Operator steering:\n{validate_steering}",
    }
    assert denied_model.calls[0][-1] == {
        "role": "user",
        "content": f"Operator steering:\n{denied_steering}",
    }
    assert passing.reuse == validate_model.reuse
    assert failing.reuse == denied_model.reuse
    assert passing.reuse.reused_tokens > 0
    assert failing.reuse.reused_tokens > 0
    assert passing.report.passed
    assert not failing.report.passed
    assert select_branch((passing, failing), "validate-only") is passing
    assert (tmp_path / "validate-only" / "app.py").read_text() == "answer = 2\n"
    assert (tmp_path / "try-extra-edit" / "app.py").read_text() == "answer = 2\n"
    assert validate_receipts.get("call-1").tool == "edit_file"
    assert validate_receipts.get("call-2").tool == "run_command"
    assert denied_receipts.get("call-1").tool == "edit_file"
    assert denied_receipts.get("call-2") is None
    assert denied_receipts.path.read_bytes() == initial_receipts
    assert validate_receipts.path.read_bytes().startswith(initial_receipts)
    visible = "\n".join(
        message["content"] for call in denied_model.calls for message in call
    )
    assert visible.count("keep the requested answer at 2") == 1


def test_task_5_selection_requires_one_named_passing_outcome(tmp_path):
    base, checkpoint = _forkable_effect(tmp_path)
    workspace, receipts = _copy_branch(
        base, tmp_path / "branch", (sys.executable, "-V"), lambda _action: True
    )
    model = ScriptedCheckpointModel(("unused", "unused", '{"final":"done"}'))
    case = EvaluationCase(final_contains="missing")
    failing = run_branch(
        "candidate", "finish", checkpoint, model, workspace, receipts, case
    )

    with pytest.raises(AgentError, match="exactly one"):
        select_branch((failing,), "absent")
    with pytest.raises(AgentError, match="exactly one"):
        select_branch((failing, replace(failing)), "candidate")
    with pytest.raises(AgentError, match="must pass"):
        select_branch((failing,), "candidate")
