# WARNING: Under review - generated by LLM.

"""Week 4 Day 9 bounded tool-evidence course-code tests."""

import hashlib
import json

import pytest

from .tiny_llm_base import (
    AgentLimits,
    ArtifactRef,
    ArtifactStore,
    BoundedEvidenceWorkspace,
    ToolAction,
    ToolPolicy,
    Workspace,
    run_agent,
)


def _payload(observation: str, prefix: str) -> dict:
    assert observation.startswith(prefix)
    return json.loads(observation.removeprefix(prefix))


def _workspace(tmp_path, content: str, **limits):
    workspace_root = tmp_path / "workspace"
    artifact_root = tmp_path / "artifacts"
    workspace_root.mkdir()
    artifact_root.mkdir()
    (workspace_root / "build.log").write_text(content, encoding="utf-8")
    workspace = Workspace(ToolPolicy(workspace_root, max_file_bytes=32_000))
    artifacts = ArtifactStore(artifact_root)
    return BoundedEvidenceWorkspace(workspace, artifacts, **limits), artifacts


def test_task_1_artifact_store_preserves_exact_bytes_and_identity(tmp_path):
    artifact_root = tmp_path / "artifacts"
    artifact_root.mkdir()
    store = ArtifactStore(artifact_root)
    result = "α\n" + "build output\n" * 40
    data = result.encode("utf-8")

    record = store.put(result)

    digest = hashlib.sha256(data).hexdigest()
    assert record == ArtifactRef(f"artifact-{digest}", len(data), digest)
    assert (artifact_root / record.artifact_id).read_bytes() == data
    assert store.read_range(record.artifact_id, 2, 17) == data[2:17]
    assert store.put(result) == record
    with pytest.raises(ValueError, match="artifact id"):
        ArtifactRef("artifact-UPPER", len(data), digest)
    with pytest.raises(ValueError, match="byte count"):
        ArtifactRef(record.artifact_id, -1, digest)
    with pytest.raises(ValueError, match="digest"):
        ArtifactRef(record.artifact_id, len(data), "not-a-digest")
    other_digest = hashlib.sha256(b"other").hexdigest()
    with pytest.raises(ValueError, match="must match"):
        ArtifactRef(record.artifact_id, len(data), other_digest)


def test_task_2_oversized_result_becomes_bounded_verifiable_observation(tmp_path):
    content = "HEAD----" + "x" * 3_000 + "----TAIL"
    bounded, artifacts = _workspace(
        tmp_path,
        content,
        max_inline_bytes=512,
        preview_bytes=8,
        max_range_bytes=24,
    )

    observation = bounded.execute(ToolAction("read_file", {"path": "build.log"}))
    payload = _payload(observation, "Tool result externalized:\n")

    data = content.encode()
    digest = hashlib.sha256(data).hexdigest()
    artifact_id = f"artifact-{digest}"
    assert payload == {
        "artifact_id": artifact_id,
        "byte_count": len(data),
        "head_preview": "HEAD----",
        "head_range": [0, 8],
        "omitted_range": [8, len(data) - 8],
        "range_request": {
            "path": artifacts.range_path(artifact_id, 0, 24),
            "tool": "read_file",
        },
        "sha256": digest,
        "tail_preview": "----TAIL",
        "tail_range": [len(data) - 8, len(data)],
    }
    assert len(observation.encode()) <= bounded.max_inline_bytes
    assert len(observation) < len(content)
    assert (artifacts.root / artifact_id).read_bytes() == data

    unicode_content = "αβγ" + "x" * 1_000 + "δεζ"
    unicode_root = tmp_path / "unicode"
    unicode_root.mkdir()
    unicode_artifacts = tmp_path / "unicode-artifacts"
    unicode_artifacts.mkdir()
    (unicode_root / "build.log").write_text(unicode_content, encoding="utf-8")
    unicode = BoundedEvidenceWorkspace(
        Workspace(ToolPolicy(unicode_root, max_file_bytes=32_000)),
        ArtifactStore(unicode_artifacts),
        max_inline_bytes=512,
        preview_bytes=5,
        max_range_bytes=24,
    )
    rendered = unicode.execute(ToolAction("read_file", {"path": "build.log"}))
    unicode_payload = _payload(rendered, "Tool result externalized:\n")
    assert "�" not in unicode_payload["head_preview"]
    assert "�" not in unicode_payload["tail_preview"]
    assert len(rendered.encode()) <= unicode.max_inline_bytes


def test_task_2_externalization_uses_utf8_bytes_at_the_exact_inline_boundary(
    tmp_path,
):
    inline, _ = _workspace(tmp_path, "a" * 512)
    assert inline.execute(ToolAction("read_file", {"path": "build.log"})) == "a" * 512

    multibyte_root = tmp_path / "multibyte"
    multibyte_root.mkdir()
    multibyte_artifacts = tmp_path / "multibyte-artifacts"
    multibyte_artifacts.mkdir()
    content = "é" * 512
    (multibyte_root / "build.log").write_text(content, encoding="utf-8")
    multibyte = BoundedEvidenceWorkspace(
        Workspace(ToolPolicy(multibyte_root, max_file_bytes=32_000)),
        ArtifactStore(multibyte_artifacts),
    )

    result = multibyte.execute(ToolAction("read_file", {"path": "build.log"}))
    payload = _payload(result, "Tool result externalized:\n")
    assert payload["byte_count"] == len(content.encode("utf-8")) == 1_024


def test_task_2_inline_cap_plus_one_byte_is_externalized(tmp_path):
    bounded, _ = _workspace(tmp_path, "a" * 513)

    result = bounded.execute(ToolAction("read_file", {"path": "build.log"}))

    assert result.startswith("Tool result externalized:\n")


def test_task_2_four_byte_unicode_bounds_the_whole_encoded_observation(tmp_path):
    bounded, _ = _workspace(
        tmp_path,
        "🙂" * 300,
        max_inline_bytes=512,
        preview_bytes=80,
        max_range_bytes=512,
    )

    result = bounded.execute(ToolAction("read_file", {"path": "build.log"}))

    assert len(result.encode("utf-8")) <= 512


def test_task_2_four_byte_unicode_preview_ranges_are_byte_accurate(tmp_path):
    content = "🙂" * 300
    bounded, _ = _workspace(
        tmp_path,
        content,
        max_inline_bytes=512,
        preview_bytes=80,
        max_range_bytes=512,
    )

    result = bounded.execute(ToolAction("read_file", {"path": "build.log"}))
    payload = _payload(result, "Tool result externalized:\n")

    data = content.encode("utf-8")
    head_end = payload["head_range"][1]
    tail_start = payload["tail_range"][0]
    assert head_end == len(payload["head_preview"].encode("utf-8"))
    assert tail_start == len(data) - len(payload["tail_preview"].encode("utf-8"))
    assert payload["omitted_range"] == [head_end, tail_start]


def test_task_3_explicit_virtual_read_returns_only_the_bound_range(tmp_path):
    content = "0123456789" * 100
    bounded, artifacts = _workspace(
        tmp_path,
        content,
        max_inline_bytes=512,
        preview_bytes=5,
        max_range_bytes=32,
    )
    first = bounded.execute(ToolAction("read_file", {"path": "build.log"}))
    identity = _payload(first, "Tool result externalized:\n")
    path = artifacts.range_path(identity["artifact_id"], 117, 139)

    result = bounded.execute(ToolAction("read_file", {"path": path}))
    payload = _payload(result, "Artifact range:\n")

    assert payload == {
        "artifact_id": identity["artifact_id"],
        "byte_count": 22,
        "data": content.encode()[117:139].decode(),
        "end": 139,
        "sha256": identity["sha256"],
        "start": 117,
        "total_byte_count": len(content.encode()),
    }
    assert content[:117] not in result
    assert content[139:] not in result


def test_task_3_selected_unicode_byte_count_is_not_a_character_count(tmp_path):
    content = "€" * 300
    bounded, artifacts = _workspace(tmp_path, content)
    first = bounded.execute(ToolAction("read_file", {"path": "build.log"}))
    identity = _payload(first, "Tool result externalized:\n")
    path = artifacts.range_path(identity["artifact_id"], 0, 510)

    result = bounded.execute(ToolAction("read_file", {"path": path}))
    payload = _payload(result, "Artifact range:\n")

    assert payload["byte_count"] == 510
    assert len(payload["data"]) == 170


def test_task_3_advertised_unicode_range_is_aligned_and_runnable(tmp_path):
    content = "€" * 300
    bounded, _ = _workspace(tmp_path, content)
    first = bounded.execute(ToolAction("read_file", {"path": "build.log"}))
    identity = _payload(first, "Tool result externalized:\n")

    advertised = identity["range_request"]["path"]
    assert advertised.endswith("/bytes/0-510")
    result = bounded.execute(ToolAction("read_file", {"path": advertised}))
    payload = _payload(result, "Artifact range:\n")
    assert payload["start"] == 0 and payload["end"] == 510
    assert payload["data"] == "€" * 170


@pytest.mark.parametrize(
    ("path", "message"),
    [
        (".tool-artifacts/not-an-id/bytes/0-4", "path is malformed"),
        ("{artifact}/bytes/-1-2", "path is malformed"),
        ("{artifact}/bytes/9-2", "0 <= start < end"),
        ("{artifact}/bytes/0-99", "exceeds 16 bytes"),
        ("{artifact}/bytes/0-16", "stored byte count"),
    ],
)
def test_task_4_range_failures_are_ordinary_and_do_not_fall_through(
    tmp_path, path, message
):
    bounded, artifacts = _workspace(
        tmp_path,
        "short",
        max_inline_bytes=512,
        preview_bytes=4,
        max_range_bytes=16,
    )
    record = artifacts.put("short")
    path = path.format(artifact=f".tool-artifacts/{record.artifact_id}")
    learner_path = bounded.workspace.policy.root / path
    learner_path.parent.mkdir(parents=True, exist_ok=True)
    learner_path.write_text("learner-secret", encoding="utf-8")

    result = bounded.execute(ToolAction("read_file", {"path": path}))

    assert result.startswith("error: ")
    assert message in result
    assert "short" not in result
    assert "learner-secret" not in result


def test_task_4_unknown_store_and_tampering_do_not_leak_artifacts(tmp_path):
    bounded, artifacts = _workspace(
        tmp_path,
        "classified diagnostic",
        max_inline_bytes=512,
        preview_bytes=4,
        max_range_bytes=16,
    )
    record = artifacts.put("classified diagnostic")
    path = artifacts.range_path(record.artifact_id, 0, 10)

    unrelated_root = tmp_path / "unrelated"
    unrelated_root.mkdir()
    unrelated = BoundedEvidenceWorkspace(
        bounded.workspace,
        ArtifactStore(unrelated_root),
        max_inline_bytes=512,
        preview_bytes=4,
        max_range_bytes=16,
    )
    missing = unrelated.execute(ToolAction("read_file", {"path": path}))
    assert missing == "error: artifact is not available in this store"
    assert record.artifact_id not in missing
    assert "classified" not in missing

    unicode_record = artifacts.put("αβγ")
    split_path = artifacts.range_path(unicode_record.artifact_id, 1, 3)
    split = bounded.execute(ToolAction("read_file", {"path": split_path}))
    assert split == "error: artifact range does not align to UTF-8 text"

    (artifacts.root / record.artifact_id).write_text("tampered", encoding="utf-8")
    tampered = bounded.execute(ToolAction("read_file", {"path": path}))
    assert tampered == "error: artifact digest does not match its recorded identity"
    assert "classified" not in tampered


def test_task_4_range_cap_plus_one_is_rejected(tmp_path):
    bounded, artifacts = _workspace(
        tmp_path,
        "a" * 100,
        max_inline_bytes=512,
        preview_bytes=4,
        max_range_bytes=16,
    )
    record = artifacts.put("a" * 100)
    path = artifacts.range_path(record.artifact_id, 0, 17)

    result = bounded.execute(ToolAction("read_file", {"path": path}))

    assert result == "error: artifact range exceeds 16 bytes"


def test_task_5_existing_agent_loop_retrieves_evidence_then_continues(tmp_path):
    diagnostic = "ERROR code=E42 dependency mismatch"
    content = "head\n" + "x" * 500 + diagnostic + "\n" + "y" * 500 + "\ntail"
    bounded, artifacts = _workspace(
        tmp_path,
        content,
        max_inline_bytes=512,
        preview_bytes=8,
        max_range_bytes=64,
    )
    digest = hashlib.sha256(content.encode()).hexdigest()
    artifact_id = f"artifact-{digest}"
    start = content.encode().index(diagnostic.encode())
    end = start + len(diagnostic.encode())
    responses = iter(
        (
            '{"tool":"read_file","path":"build.log"}',
            json.dumps(
                {
                    "tool": "read_file",
                    "path": artifacts.range_path(artifact_id, start, end),
                },
                separators=(",", ":"),
            ),
            '{"final":"The requested range contains diagnostic E42."}',
        )
    )

    run = run_agent(
        "Inspect the large build log and retrieve the diagnostic range.",
        lambda _messages: next(responses),
        bounded,
        AgentLimits(max_steps=3),
    )

    assert run.completed and run.final == "The requested range contains diagnostic E42."
    assert len(run.events) == 3
    assert diagnostic not in run.events[0].result
    range_payload = _payload(run.events[1].result, "Artifact range:\n")
    assert range_payload["artifact_id"] == artifact_id
    assert range_payload["start"] == start and range_payload["end"] == end
    assert range_payload["data"] == diagnostic
    assert (artifacts.root / artifact_id).read_bytes() == content.encode()


def test_task_6_small_and_error_results_remain_inline_and_state_is_delegated(
    tmp_path, monkeypatch
):
    bounded, artifacts = _workspace(
        tmp_path,
        "small result\n",
        max_inline_bytes=512,
        preview_bytes=8,
        max_range_bytes=16,
    )

    result = bounded.execute(ToolAction("read_file", {"path": "build.log"}))

    assert result == "small result\n"
    assert bounded.policy is bounded.workspace.policy
    assert bounded.available_tools == bounded.workspace.available_tools
    assert bounded.modified_files == ()
    assert list(artifacts.root.iterdir()) == []

    long_error = "error: " + "x" * 1_000
    monkeypatch.setattr(bounded.workspace, "execute", lambda *_args: long_error)
    assert bounded.execute(ToolAction("read_file", {"path": "missing"})) == long_error
    assert list(artifacts.root.iterdir()) == []

    with pytest.raises(ValueError, match="at least 512"):
        BoundedEvidenceWorkspace(bounded.workspace, artifacts, max_inline_bytes=511)
    with pytest.raises(ValueError, match="must not exceed"):
        BoundedEvidenceWorkspace(
            bounded.workspace,
            artifacts,
            max_inline_bytes=512,
            preview_bytes=513,
        )
