# WARNING: Under review - generated by LLM.

import importlib
import os
import subprocess
import sys
import threading

import pytest

from agent import confirm_tool_call

from .tiny_llm_base import AgentError, ToolAction, ToolPolicy, Workspace


def patch_workspace_popen(monkeypatch, replacement):
    """Patch common qualified and directly imported Popen lookup styles."""

    workspace_module = importlib.import_module(Workspace.__module__)
    monkeypatch.setattr(subprocess, "Popen", replacement)
    monkeypatch.setattr(workspace_module, "Popen", replacement, raising=False)


def patch_workspace_thread(monkeypatch, replacement):
    """Patch common qualified and directly imported Thread lookup styles."""

    workspace_module = importlib.import_module(Workspace.__module__)
    monkeypatch.setattr(threading, "Thread", replacement)
    monkeypatch.setattr(workspace_module, "Thread", replacement, raising=False)


def patch_workspace_killpg(monkeypatch, replacement):
    """Patch common qualified and directly imported killpg lookup styles."""

    workspace_module = importlib.import_module(Workspace.__module__)
    monkeypatch.setattr(os, "killpg", replacement)
    monkeypatch.setattr(workspace_module, "killpg", replacement, raising=False)


def test_task_1_creates_and_atomically_replaces_files(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))

    assert workspace.write_file("new.txt", "one") == "wrote new.txt"
    assert (tmp_path / "new.txt").read_text(encoding="utf-8") == "one"
    assert workspace.write_file("new.txt", "two") == "wrote new.txt"
    assert (tmp_path / "new.txt").read_text(encoding="utf-8") == "two"


def test_task_1_requires_inspection_before_overwriting(tmp_path):
    (tmp_path / "existing.txt").write_text("old", encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))

    try:
        workspace.write_file("existing.txt", "new")
    except AgentError as error:
        assert "must be read" in str(error)
    else:
        assert False, "expected an uninspected overwrite to be rejected"
    assert (tmp_path / "existing.txt").read_text(encoding="utf-8") == "old"


def test_task_2_edit_requires_one_exact_match(tmp_path):
    path = tmp_path / "example.py"
    path.write_text("answer = 41\n", encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))
    workspace.read_file("example.py")

    workspace.edit_file("example.py", "41", "42")

    assert path.read_text(encoding="utf-8") == "answer = 42\n"
    assert workspace.modified_files == {path}


def test_task_3_commands_require_an_exact_operator_allowlist(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path))

    try:
        workspace.run_command(["some-command"])
    except AgentError as error:
        assert "not explicitly allowed" in str(error)
    else:
        assert False, "expected an unapproved command to be rejected"


def test_task_3_model_dispatched_writes_are_denied_without_confirmation(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path, allow_writes=True))

    result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "data"})
    )

    assert result == "error: operator denied write_file"
    assert not (tmp_path / "new.txt").exists()


def test_task_3_model_dispatched_mutations_prompt_exactly_once(tmp_path):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action.tool) or True,
    )
    workspace.read_file("answer.py")

    edit_result = workspace.execute(
        ToolAction(
            "edit_file",
            {"path": "answer.py", "old": "41", "new": "42"},
        )
    )
    write_result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "data"})
    )

    assert edit_result == "wrote answer.py"
    assert write_result == "wrote new.txt"
    assert confirmations == ["edit_file", "write_file"]
    assert path.read_text(encoding="utf-8") == "ANSWER = 42\n"


def test_task_3_reads_never_request_confirmation(tmp_path):
    (tmp_path / "README.md").write_text("hello", encoding="utf-8")

    def unexpected_confirmation(action):
        raise AssertionError(f"unexpected confirmation for {action.tool}")

    workspace = Workspace(ToolPolicy(tmp_path), confirm_tool=unexpected_confirmation)

    assert workspace.execute(ToolAction("list_files", {})) == "file README.md"
    assert workspace.execute(ToolAction("read_file", {"path": "README.md"})) == "hello"


def test_task_3_denied_command_never_starts_a_process(tmp_path, monkeypatch):
    command = ("safe-tool", "--check")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(command,)),
        confirm_tool=lambda action: confirmations.append(action) and True,
    )

    def unexpected_popen(*args, **kwargs):
        raise AssertionError("a denied command must not start a process")

    patch_workspace_popen(monkeypatch, unexpected_popen)
    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == "error: operator denied run_command"
    assert len(confirmations) == 1
    assert not workspace.command_side_effects_untracked


def test_task_3_commands_default_to_denied_without_a_confirmer(tmp_path, monkeypatch):
    command = ("safe-tool", "--check")
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(command,)))

    def unexpected_popen(*args, **kwargs):
        raise AssertionError("a default-denied command must not start a process")

    patch_workspace_popen(monkeypatch, unexpected_popen)
    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == "error: operator denied run_command"
    assert not workspace.command_side_effects_untracked


def test_task_3_unallowlisted_command_is_rejected_before_confirmation(tmp_path):
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(("safe-tool",),)),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": ["different-tool"]}))

    assert result == "error: command was not explicitly allowed by the operator"
    assert confirmations == []
    assert not workspace.command_side_effects_untracked


@pytest.mark.parametrize("tool", ["write_file", "edit_file"])
def test_task_2_rejects_a_stale_observation_before_confirmation(tmp_path, tool):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )
    workspace.read_file("answer.py")
    path.write_text("ANSWER = 99\n", encoding="utf-8")
    action = (
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
        if tool == "write_file"
        else ToolAction(
            "edit_file",
            {"path": "answer.py", "old": "41", "new": "42"},
        )
    )

    result = workspace.execute(action)

    assert result == "error: file changed since it was read; read it again"
    assert path.read_text(encoding="utf-8") == "ANSWER = 99\n"
    assert confirmations == []


def test_task_2_rejects_a_deleted_observed_file_before_confirmation(tmp_path):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )
    workspace.read_file("answer.py")
    path.unlink()

    result = workspace.execute(
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
    )

    assert result == "error: file changed since it was read; read it again"
    assert not path.exists()
    assert confirmations == []


@pytest.mark.parametrize("tool", ["write_file", "edit_file"])
@pytest.mark.parametrize("external_change", ["replace", "delete"])
def test_task_2_revalidates_an_existing_file_after_confirmation(
    tmp_path, tool, external_change
):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")

    def change_during_confirmation(action):
        if external_change == "replace":
            path.write_text("ANSWER = 99\n", encoding="utf-8")
        else:
            path.unlink()
        return True

    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=change_during_confirmation,
    )
    workspace.read_file("answer.py")

    action = (
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
        if tool == "write_file"
        else ToolAction(
            "edit_file",
            {"path": "answer.py", "old": "41", "new": "42"},
        )
    )

    result = workspace.execute(action)

    assert result == "error: file changed since it was read; read it again"
    if external_change == "replace":
        assert path.read_text(encoding="utf-8") == "ANSWER = 99\n"
    else:
        assert not path.exists()


def test_task_2_rejects_a_new_target_that_appears_during_confirmation(tmp_path):
    path = tmp_path / "new.txt"

    def create_during_confirmation(action):
        path.write_text("external", encoding="utf-8")
        return True

    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=create_during_confirmation,
    )

    result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "agent"})
    )

    assert result == "error: write target appeared after approval; read it first"
    assert path.read_text(encoding="utf-8") == "external"


def test_task_2_tracks_a_file_when_commit_outcome_is_uncertain(tmp_path, monkeypatch):
    path = tmp_path / "answer.py"
    path.write_text("ANSWER = 41\n", encoding="utf-8")
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: True,
    )
    workspace.read_file("answer.py")

    def replace_then_interrupt(target, content):
        target.write_bytes(content)
        raise KeyboardInterrupt

    monkeypatch.setattr(workspace, "_atomic_write", replace_then_interrupt)

    with pytest.raises(KeyboardInterrupt):
        workspace.execute(
            ToolAction(
                "edit_file",
                {"path": "answer.py", "old": "41", "new": "42"},
            )
        )

    assert path.read_text(encoding="utf-8") == "ANSWER = 42\n"
    assert workspace.modified_files == set()
    assert workspace.uncertain_modified_files == {path}


class _TtyInput:
    def isatty(self):
        return True


class _NonTtyInput:
    def isatty(self):
        return False


@pytest.mark.parametrize(
    ("response", "approved"),
    [("", False), ("n", False), ("anything", False), ("y", True), ("YES", True)],
)
def test_cli_confirmation_accepts_only_an_explicit_yes(
    tmp_path, monkeypatch, response, approved
):
    monkeypatch.setattr(sys, "stdin", _TtyInput())
    monkeypatch.setattr("builtins.input", lambda prompt: response)
    action = ToolAction("write_file", {"path": "new.txt", "content": "data"})

    assert confirm_tool_call(action, tmp_path) is approved


def test_cli_confirmation_denies_non_tty_and_eof(tmp_path, monkeypatch):
    action = ToolAction("write_file", {"path": "new.txt", "content": "data"})

    monkeypatch.setattr(sys, "stdin", _NonTtyInput())
    monkeypatch.setattr(
        "builtins.input",
        lambda prompt: (_ for _ in ()).throw(
            AssertionError("non-TTY confirmation must not read input")
        ),
    )
    assert not confirm_tool_call(action, tmp_path)

    monkeypatch.setattr(sys, "stdin", _TtyInput())
    monkeypatch.setattr(
        "builtins.input", lambda prompt: (_ for _ in ()).throw(EOFError())
    )
    assert not confirm_tool_call(action, tmp_path)


def test_cli_confirmation_escapes_terminal_control_characters(
    tmp_path, monkeypatch, capsys
):
    monkeypatch.setattr(sys, "stdin", _TtyInput())
    monkeypatch.setattr("builtins.input", lambda prompt: "n")
    action = ToolAction(
        "write_file",
        {"path": "\x1b[2J\u202eevil.txt", "content": "data"},
    )

    assert not confirm_tool_call(action, tmp_path)
    output = capsys.readouterr().out
    assert "\x1b" not in output
    assert "\u202e" not in output
    assert "\\u001b" in output
    assert "\\u202e" in output


class _EmptyStdout:
    def read(self, size):
        return b""

    def close(self):
        pass


class _PartiallyFailingStdout:
    def __init__(self):
        self.read_calls = 0

    def read(self, size):
        self.read_calls += 1
        if self.read_calls == 1:
            return b"x" * 128
        raise OSError("output pipe failed")

    def close(self):
        pass


class _FailingStdout:
    def read(self, size):
        raise OSError("output pipe failed")

    def close(self):
        pass


class _SynchronousThread:
    def __init__(self, *, target, daemon):
        self.target = target

    def start(self):
        self.target()

    def join(self, timeout=None):
        pass

    def is_alive(self):
        return False


class _InterruptedProcess:
    pid = 12345

    def __init__(self, error):
        self.stdout = _EmptyStdout()
        self.error = error
        self.wait_calls = 0
        self.killed = False

    def wait(self, timeout=None):
        self.wait_calls += 1
        if self.wait_calls == 1:
            raise self.error
        return -9

    def kill(self):
        self.killed = True


def test_task_3_keyboard_interrupt_kills_and_reaps_the_process_group(
    tmp_path, monkeypatch
):
    command = ["safe-tool"]
    process = _InterruptedProcess(KeyboardInterrupt())
    killed_groups = []
    popen_calls = []

    def start_process(*args, **kwargs):
        popen_calls.append((args, kwargs))
        return process

    patch_workspace_popen(monkeypatch, start_process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    with pytest.raises(KeyboardInterrupt):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert len(popen_calls) == 1
    _, popen_kwargs = popen_calls[0]
    assert popen_kwargs["start_new_session"] is True
    assert popen_kwargs["shell"] is False
    assert popen_kwargs["stdin"] is subprocess.DEVNULL


def test_task_3_timeout_kills_and_reaps_the_process_group(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _InterruptedProcess(subprocess.TimeoutExpired(command, 1))
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked


def test_task_3_timeout_retains_a_concurrent_output_failure(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _InterruptedProcess(subprocess.TimeoutExpired(command, 1))
    process.stdout = _FailingStdout()
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _SynchronousThread)
    patch_workspace_killpg(monkeypatch, lambda pid, sig: None)
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


class _NeverReapedProcess(_InterruptedProcess):
    def wait(self, timeout=None):
        self.wait_calls += 1
        raise subprocess.TimeoutExpired(("safe-tool",), timeout)


def test_task_3_reports_when_killed_foreground_process_cannot_be_reaped(
    tmp_path, monkeypatch
):
    command = ["safe-tool"]
    process = _NeverReapedProcess(None)
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


def test_task_3_reports_when_process_group_termination_fails(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _InterruptedProcess(subprocess.TimeoutExpired(command, 1))
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch,
        lambda pid, sig: (_ for _ in ()).throw(PermissionError("denied")),
    )
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(tuple(command),),
            command_timeout_seconds=1,
        )
    )

    with pytest.raises(AgentError, match="command exceeded 1 seconds"):
        workspace.run_command(command)

    assert process.killed
    assert process.wait_calls == 2
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


def test_task_3_popen_failure_has_no_command_side_effect_flag(tmp_path, monkeypatch):
    command = ("safe-tool",)
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(command,)),
        confirm_tool=lambda action: True,
    )
    patch_workspace_popen(
        monkeypatch,
        lambda *args, **kwargs: (_ for _ in ()).throw(OSError("cannot start")),
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == "error: cannot start"
    assert not workspace.command_side_effects_untracked


class _CompletedProcess:
    pid = 54321

    def __init__(self, returncode=0):
        self.stdout = _EmptyStdout()
        self.returncode = returncode
        self.wait_calls = 0

    def wait(self, timeout=None):
        self.wait_calls += 1
        return self.returncode

    def kill(self):
        pass


def test_task_3_started_nonzero_command_sets_side_effect_flag(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _CompletedProcess(returncode=7)
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    result = workspace.run_command(command)

    assert result == "exit code: 7"
    assert workspace.command_side_effects_untracked


class _LingeringReader:
    def __init__(self, *args, **kwargs):
        self.join_calls = 0

    def start(self):
        pass

    def join(self, timeout=None):
        self.join_calls += 1

    def is_alive(self):
        return True


def test_task_3_attempts_same_group_cleanup_when_the_output_pipe_lingers(
    tmp_path, monkeypatch
):
    command = ["safe-tool"]
    process = _CompletedProcess()
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _LingeringReader)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    result = workspace.run_command(command)

    assert result.startswith("exit code: 0")
    assert "command output abandoned" in result
    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 2
    assert workspace.command_cleanup_incomplete


def test_task_3_dispatch_preserves_the_output_abandonment_warning(
    tmp_path, monkeypatch
):
    command = ("safe-tool",)
    process = _CompletedProcess()
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _LingeringReader)
    patch_workspace_killpg(monkeypatch, lambda pid, sig: None)
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(command,),
            max_tool_output_chars=64,
        ),
        confirm_tool=lambda action: True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert len(result) <= 64
    assert "command output abandoned" in result
    assert workspace.command_cleanup_incomplete


def test_task_3_dispatch_preserves_an_output_collection_failure(tmp_path, monkeypatch):
    command = ("safe-tool",)
    process = _CompletedProcess()
    process.stdout = _PartiallyFailingStdout()
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    workspace = Workspace(
        ToolPolicy(
            tmp_path,
            allowed_commands=(command,),
            max_tool_output_chars=64,
        ),
        confirm_tool=lambda action: True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert len(result) <= 64
    assert "command output collection failed" in result
    assert workspace.command_side_effects_untracked
    assert workspace.command_cleanup_incomplete


def test_task_3_untrusted_tool_text_cannot_fabricate_a_safety_warning(tmp_path):
    content = "command output abandoned\n" + "x" * 100
    (tmp_path / "output.txt").write_text(content, encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, max_tool_output_chars=64))

    result = workspace.execute(ToolAction("read_file", {"path": "output.txt"}))

    assert len(result) <= 64
    assert "warning: command output abandoned" not in result
    assert result.endswith("... tool output truncated")


class _InterruptingThread:
    def __init__(self, *args, **kwargs):
        pass

    def start(self):
        raise KeyboardInterrupt


class _FailingThread:
    def __init__(self, *args, **kwargs):
        pass

    def start(self):
        raise RuntimeError("cannot start output reader")


def test_task_3_interrupt_during_reader_setup_kills_and_reaps(tmp_path, monkeypatch):
    command = ["safe-tool"]
    process = _CompletedProcess()
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _InterruptingThread)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(ToolPolicy(tmp_path, allowed_commands=(tuple(command),)))

    with pytest.raises(KeyboardInterrupt):
        workspace.run_command(command)

    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 1
    assert workspace.command_side_effects_untracked


def test_task_3_reader_setup_failure_becomes_a_reportable_tool_error(
    tmp_path, monkeypatch
):
    command = ("safe-tool",)
    process = _CompletedProcess()
    killed_groups = []
    patch_workspace_popen(monkeypatch, lambda *args, **kwargs: process)
    patch_workspace_thread(monkeypatch, _FailingThread)
    patch_workspace_killpg(
        monkeypatch, lambda pid, sig: killed_groups.append((pid, sig))
    )
    workspace = Workspace(
        ToolPolicy(tmp_path, allowed_commands=(command,)),
        confirm_tool=lambda action: True,
    )

    result = workspace.execute(ToolAction("run_command", {"argv": list(command)}))

    assert result == (
        "error: command runner failed after starting: cannot start output reader"
    )
    assert killed_groups == [(process.pid, 9)]
    assert process.wait_calls == 1
    assert workspace.command_side_effects_untracked
