# WARNING: Under review - generated by LLM.

import stat
from pathlib import Path

import pytest

from .tiny_llm_base import AgentError, ToolAction, ToolPolicy, Workspace


def test_task_1_lists_and_reads_bounded_workspace_files(tmp_path):
    (tmp_path / "README.md").write_text("hello", encoding="utf-8")
    (tmp_path / ".env").write_text("SECRET=value", encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path))

    listing = workspace.list_files()
    assert "file README.md" in listing
    assert ".env" not in listing
    assert workspace.read_file("README.md") == "hello"


def test_task_1_list_is_sorted_and_bounded(tmp_path):
    for name in ("c.txt", "a.txt", "b.txt"):
        (tmp_path / name).write_text(name, encoding="utf-8")
    workspace = Workspace(ToolPolicy(tmp_path, max_list_entries=2))

    assert workspace.list_files().splitlines() == ["file a.txt", "file b.txt"]


def test_task_1_rejects_oversized_non_utf8_and_non_file_reads(tmp_path):
    (tmp_path / "large.txt").write_text("12345", encoding="utf-8")
    (tmp_path / "binary.dat").write_bytes(b"\xff")
    (tmp_path / "directory").mkdir()
    workspace = Workspace(ToolPolicy(tmp_path, max_file_bytes=4))

    with pytest.raises(AgentError, match="exceeds 4 bytes"):
        workspace.read_file("large.txt")
    assert workspace.execute(
        ToolAction("read_file", {"path": "binary.dat"})
    ).startswith("error:")
    with pytest.raises(AgentError, match="regular file"):
        workspace.read_file("directory")


@pytest.mark.parametrize(
    "path",
    [
        "../outside",
        "/tmp/outside",
        "",
        "bad\x00path",
        ".git/config",
        ".env",
        "key.pem",
    ],
)
def test_task_2_rejects_unsafe_paths(tmp_path, path):
    workspace = Workspace(ToolPolicy(tmp_path))
    with pytest.raises(AgentError):
        workspace.resolve_path(path, must_exist=False)


def test_task_2_rejects_symlinks(tmp_path):
    target = tmp_path / "target.txt"
    target.write_text("target", encoding="utf-8")
    (tmp_path / "link.txt").symlink_to(target)
    workspace = Workspace(ToolPolicy(tmp_path))

    with pytest.raises(AgentError, match="symlinks"):
        workspace.read_file("link.txt")


@pytest.mark.parametrize(
    "overrides",
    [
        {"max_file_bytes": 0},
        {"max_write_bytes": 0},
        {"max_list_entries": 0},
        {"max_tool_output_chars": 0},
        {"command_timeout_seconds": 0},
    ],
)
def test_task_2_rejects_non_positive_policy_limits(tmp_path, overrides):
    with pytest.raises(ValueError, match="limits must be positive"):
        ToolPolicy(tmp_path, **overrides)


def test_task_3_writes_are_disabled_by_default(tmp_path):
    workspace = Workspace(ToolPolicy(tmp_path))
    result = workspace.execute(
        ToolAction("write_file", {"path": "new.txt", "content": "data"})
    )

    assert result.startswith("error: writes are disabled")
    assert not (tmp_path / "new.txt").exists()


def test_task_3_rejects_an_unsafe_path_before_requesting_confirmation(tmp_path):
    confirmations = []
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda action: confirmations.append(action) or True,
    )

    result = workspace.execute(
        ToolAction("write_file", {"path": "../outside", "content": "data"})
    )

    assert result.startswith("error: parent path components are not allowed")
    assert confirmations == []


def test_task_3_rejects_chmod_during_write_confirmation(tmp_path):
    target = tmp_path / "answer.py"
    target.write_text("ANSWER = 41\n", encoding="utf-8")
    target.chmod(0o600)

    def change_mode_during_confirmation(_action):
        target.chmod(0o755)
        return True

    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=change_mode_during_confirmation,
    )
    workspace.read_file("answer.py")

    result = workspace.execute(
        ToolAction(
            "write_file",
            {"path": "answer.py", "content": "ANSWER = 42\n"},
        )
    )

    assert result == "error: file changed since it was read; read it again"
    assert target.read_text(encoding="utf-8") == "ANSWER = 41\n"
    assert stat.S_IMODE(target.stat().st_mode) == 0o755


def test_task_3_write_preserves_the_inspected_file_mode(tmp_path):
    target = tmp_path / "answer.py"
    target.write_text("ANSWER = 41\n", encoding="utf-8")
    target.chmod(0o640)
    workspace = Workspace(
        ToolPolicy(tmp_path, allow_writes=True),
        confirm_tool=lambda _action: True,
    )
    workspace.read_file("answer.py")

    assert (
        workspace.execute(
            ToolAction(
                "write_file",
                {"path": "answer.py", "content": "ANSWER = 42\n"},
            )
        )
        == "wrote answer.py"
    )
    assert stat.S_IMODE(target.stat().st_mode) == 0o640


@pytest.mark.parametrize(
    "root",
    [Path.home(), Path.home().parent, Path(Path.home().anchor)],
)
def test_task_2_rejects_workspace_roots_that_are_too_broad(root):
    with pytest.raises(ValueError, match="too broad"):
        ToolPolicy(root)


@pytest.mark.parametrize("protected", [".git", ".ssh", ".env"])
def test_task_2_rejects_workspace_roots_inside_protected_paths(tmp_path, protected):
    root = tmp_path / protected / "nested"
    root.mkdir(parents=True)

    with pytest.raises(ValueError, match="workspace root is protected"):
        ToolPolicy(root)
