# WARNING: Under review - generated by LLM.

from pathlib import Path

import pytest

from .tiny_llm_base import (
    AgentError,
    ToolAction,
    ToolPolicy,
    Workspace,
    build_system_prompt,
    parse_action,
    run_agent,
)


def make_workspace(root: Path, **limits) -> Workspace:
    return Workspace(ToolPolicy(root, **limits))


def test_task_1_policy_requires_a_directory_and_positive_limits(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()

    assert ToolPolicy(root).root == root.resolve()
    with pytest.raises(ValueError, match="exist"):
        ToolPolicy(tmp_path / "missing")
    with pytest.raises(ValueError, match="positive"):
        ToolPolicy(root, max_file_bytes=0)
    with pytest.raises(ValueError, match="integers"):
        ToolPolicy(root, max_list_entries=True)


def test_task_2_lists_and_reads_workspace_files(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    (root / "README.md").write_text("hello agent\n", encoding="utf-8")
    (root / "src").mkdir()
    (root / "src" / "main.py").write_text("print('hi')\n", encoding="utf-8")
    workspace = make_workspace(root)

    assert workspace.available_tools == frozenset({"list_files", "read_file"})
    assert workspace.list_files() == "file README.md\ndir src"
    assert workspace.list_files("src") == "file src/main.py"
    assert workspace.read_file("README.md") == "hello agent\n"


def test_task_3_rejects_escapes_secrets_and_symlinks(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    outside = tmp_path / "outside.txt"
    outside.write_text("outside", encoding="utf-8")
    (root / "visible.txt").write_text("visible", encoding="utf-8")
    (root / ".env").write_text("TOKEN=secret", encoding="utf-8")
    (root / ".git").mkdir()
    (root / "outside-link").symlink_to(outside)
    workspace = make_workspace(root)

    for raw in ("../outside.txt", str(outside), ".env", ".git", "outside-link"):
        with pytest.raises(AgentError):
            workspace.resolve_path(raw)
    assert workspace.list_files() == "file visible.txt"


def test_task_4_bounds_directory_and_file_observations(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    for name in ("a.txt", "b.txt", "c.txt"):
        (root / name).write_text(name, encoding="utf-8")
    (root / "large.txt").write_text("too large", encoding="utf-8")
    workspace = make_workspace(root, max_list_entries=2, max_file_bytes=5)

    assert workspace.list_files().splitlines() == ["file a.txt", "file b.txt"]
    with pytest.raises(AgentError, match="exceeds 5 bytes"):
        workspace.read_file("large.txt")


def test_task_5_rejects_directories_and_non_utf8_files(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    (root / "folder").mkdir()
    (root / "binary.bin").write_bytes(b"\xff")
    workspace = make_workspace(root)

    with pytest.raises(AgentError, match="regular file"):
        workspace.read_file("folder")
    with pytest.raises(AgentError, match="UTF-8"):
        workspace.read_file("binary.bin")


def test_task_6_dispatch_returns_recoverable_observations(tmp_path):
    root = tmp_path / "workspace"
    root.mkdir()
    (root / "README.md").write_text("hello", encoding="utf-8")
    workspace = make_workspace(root)

    assert workspace.execute(ToolAction("read_file", {"path": "README.md"})) == "hello"
    missing = workspace.execute(ToolAction("read_file", {"path": "missing.md"}))
    disabled = workspace.execute(
        ToolAction("write_file", {"path": "x", "content": "y"})
    )
    assert missing.startswith("error:")
    assert disabled == "error: tool is not enabled: write_file"


def test_task_7_prompt_and_parser_expose_only_read_tools(tmp_path):
    workspace = make_workspace(tmp_path)
    prompt = build_system_prompt(workspace)

    assert '"tool":"list_files"' in prompt
    assert '"tool":"read_file"' in prompt
    assert '"tool":"write_file"' not in prompt
    assert parse_action(
        '{"tool":"list_files"}', workspace.available_tools
    ) == ToolAction("list_files", {})
    with pytest.raises(AgentError, match="not enabled"):
        parse_action(
            '{"tool":"write_file","path":"x","content":"y"}',
            workspace.available_tools,
        )


def test_task_8_agent_lists_reads_observes_and_finishes(tmp_path):
    (tmp_path / "README.md").write_text("hello from README", encoding="utf-8")
    workspace = make_workspace(tmp_path)
    responses = iter(
        [
            '{"tool":"list_files"}',
            '{"tool":"read_file","path":"README.md"}',
            '{"final":"README says hello"}',
        ]
    )
    seen_messages = []

    def generate(messages):
        seen_messages.append([dict(message) for message in messages])
        return next(responses)

    result = run_agent("inspect the project", generate, workspace)

    assert result.completed
    assert result.final == "README says hello"
    assert [event.action.tool for event in result.events[:2]] == [
        "list_files",
        "read_file",
    ]
    assert result.events[0].result == "file README.md"
    assert result.events[1].result == "hello from README"
    assert seen_messages[2][-1] == {
        "role": "user",
        "content": "Tool result:\nhello from README",
    }
