# WARNING: Under review - generated by LLM.

"""True narrow-viewport render gate for the Week 4 course pages.

Reproduces Scholar's exact learner path: ``mdbook serve`` on a fixed port,
then headless Chrome with ``--window-size=390,1200`` in dark mode.  Asserts:

- every rendered heading, paragraph, list item, and table cell has
  ``left >= content_left - 2`` and ``right <= content_right + 2`` (or is
  inside a genuinely scrollable container whose own box fits the page);
- the body/document scrollWidth does not exceed the window width;
- the content box itself fits within the window.

This is a publication gate: it FAILS CLOSED when Chrome, websocket-client, or
the serve step is unavailable — no skip, xfail, or soft pass.
"""

import json
import shutil
import socket
import subprocess
import time
import urllib.request
from pathlib import Path

import pytest
import websocket  # noqa: F401  (fail closed if the dependency is missing)

ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / "book"

PAGES = (
    "week4-01-agent-loop.html",
    "week4-overview.html",
    "week2-02-benchmark-profile.html",
    "week3-02-chunked-prefill.html",
)

CHROME_CANDIDATES = (
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
)

SERVE_PORT = 3104


def _find_chrome():
    for candidate in CHROME_CANDIDATES:
        if Path(candidate).exists():
            return candidate
    found = shutil.which("google-chrome") or shutil.which("chromium")
    return found


def _wait_for_serve(port, timeout=15):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=1):
                return True
        except OSError:
            time.sleep(0.3)
    return False


@pytest.fixture(scope="module")
def serve():
    chrome = _find_chrome()
    assert chrome, "Chrome is required for the render gate"
    proc = subprocess.Popen(
        [
            "mdbook",
            "serve",
            str(BOOK),
            "--hostname",
            "127.0.0.1",
            "--port",
            str(SERVE_PORT),
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    assert _wait_for_serve(SERVE_PORT), "mdbook serve did not start in time"
    try:
        yield f"http://127.0.0.1:{SERVE_PORT}"
    finally:
        proc.terminate()
        proc.wait(timeout=5)


@pytest.mark.parametrize("page", PAGES)
def test_narrow_dark_render_is_fully_visible(serve, page):
    chrome = _find_chrome()
    assert chrome, "Chrome is required for the render gate"

    url = f"{serve}/{page}"
    proc = subprocess.Popen(
        [
            chrome,
            "--headless=new",
            "--disable-gpu",
            "--remote-debugging-port=9247",
            "--remote-allow-origins=*",
            "--force-dark-mode",
            "--window-size=390,1200",
            url,
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        deadline = time.monotonic() + 15
        targets = None
        while time.monotonic() < deadline:
            try:
                targets = json.loads(
                    urllib.request.urlopen(
                        "http://127.0.0.1:9247/json", timeout=1
                    ).read()
                )
                break
            except Exception:
                time.sleep(0.3)
        assert targets, "Chrome debugging endpoint did not come up"
        page_target = next(t for t in targets if t["type"] == "page")
        ws = websocket.create_connection(
            page_target["webSocketDebuggerUrl"], timeout=10
        )

        def cmd(method, params=None):
            ws.send(json.dumps({"id": 1, "method": method, "params": params or {}}))
            while True:
                msg = json.loads(ws.recv())
                if msg.get("id") == 1:
                    return msg

        time.sleep(1.0)
        expr = """(() => {
            const vw = innerWidth;
            const content = document.querySelector('.content');
            const contentRect = content ? content.getBoundingClientRect() : null;
            const clipped = [];
            const containers = new Set();
            // Intentional scroll containers: table-wrapper, pre, code with
            // overflow-x auto.
            for (const el of document.querySelectorAll('main *')) {
                const cs = getComputedStyle(el);
                const isScrollContainer =
                    (el.classList && el.classList.contains('table-wrapper')) ||
                    (el.tagName === 'PRE' && cs.overflowX === 'auto') ||
                    (el.tagName === 'CODE' && cs.overflowX === 'auto');
                if (isScrollContainer && cs.overflowX === 'auto') containers.add(el);
            }
            // Scroll containers' own boxes must fit within the page.
            const containerProblems = [];
            for (const el of containers) {
                const r = el.getBoundingClientRect();
                if (r.left < -2 || r.right > vw + 2) {
                    containerProblems.push({tag: el.tagName,
                        cls: (el.className||'').toString().slice(0,25),
                        left: Math.round(r.left), right: Math.round(r.right)});
                }
            }
            const nearestContainer = (el) => {
                let p = el.parentElement;
                while (p) {
                    if (containers.has(p)) return p;
                    p = p.parentElement;
                }
                return null;
            };
            // Headings, paragraphs, list items, and table cells must be
            // visible within the page or their nearest scroll container.
            for (const el of document.querySelectorAll(
                'main h1, main h2, main h3, main p, main li, main td, main th'
            )) {
                if (containers.has(el)) continue;
                const r = el.getBoundingClientRect();
                const cs = getComputedStyle(el);
                if (r.width <= 0 || r.height <= 0 || cs.visibility === 'hidden') continue;
                const container = nearestContainer(el);
                let leftBound = 0, rightBound = vw;
                if (container) {
                    const cr = container.getBoundingClientRect();
                    leftBound = cr.left;
                    rightBound = cr.right;
                }
                if (r.left < leftBound - 2 || r.right > rightBound + 2) {
                    if (!container || container.scrollWidth <= container.clientWidth) {
                        clipped.push({tag: el.tagName, left: Math.round(r.left),
                                      right: Math.round(r.right),
                                      text: (el.textContent||'').slice(0,40).replace(/\\s+/g,' ')});
                        if (clipped.length >= 8) break;
                    }
                }
            }
            return {
                viewport: vw,
                bodyScroll: document.body.scrollWidth,
                docScroll: document.documentElement.scrollWidth,
                contentLeft: contentRect ? Math.round(contentRect.left) : null,
                contentRight: contentRect ? Math.round(contentRect.right) : null,
                clippedCount: clipped.length,
                clipped,
                containerProblems,
            };
        })()"""
        r = cmd("Runtime.evaluate", {"expression": expr, "returnByValue": True})
        value = r["result"]["result"].get("value", {})
        ws.close()

        assert value["bodyScroll"] <= value["viewport"] + 2, (
            f"{page}: page overflow (body {value['bodyScroll']} vs viewport "
            f"{value['viewport']})"
        )
        assert value["docScroll"] <= value["viewport"] + 2, (
            f"{page}: document overflow (doc {value['docScroll']} vs viewport "
            f"{value['viewport']})"
        )
        if value["contentLeft"] is not None:
            assert value["contentLeft"] >= -2, (
                f"{page}: content starts off-screen left ({value['contentLeft']})"
            )
            assert value["contentRight"] <= value["viewport"] + 2, (
                f"{page}: content extends past the viewport right edge "
                f"({value['contentRight']} vs {value['viewport']})"
            )
        assert value["clippedCount"] == 0, (
            f"{page}: {value['clippedCount']} visible headings/paragraphs/cells "
            f"clipped: {value['clipped']}"
        )
        assert value["containerProblems"] == [], (
            f"{page}: scroll containers overflow the page: {value['containerProblems']}"
        )
    finally:
        proc.terminate()
        proc.wait(timeout=5)


@pytest.mark.parametrize("page", ["week4-01-agent-loop.html"])
def test_render_gate_catches_bare_overflowing_table(serve, page):
    """A table without contained scroll must be flagged by the gate logic."""

    chrome = _find_chrome()
    assert chrome, "Chrome is required for the render gate"
    proc = subprocess.Popen(
        [
            chrome,
            "--headless=new",
            "--disable-gpu",
            "--remote-debugging-port=9249",
            "--remote-allow-origins=*",
            "--force-dark-mode",
            "--window-size=390,1200",
            f"{serve}/{page}",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        deadline = time.monotonic() + 15
        targets = None
        while time.monotonic() < deadline:
            try:
                targets = json.loads(
                    urllib.request.urlopen(
                        "http://127.0.0.1:9249/json", timeout=1
                    ).read()
                )
                break
            except Exception:
                time.sleep(0.3)
        assert targets, "Chrome debugging endpoint did not come up"
        page_target = next(t for t in targets if t["type"] == "page")
        ws = websocket.create_connection(
            page_target["webSocketDebuggerUrl"], timeout=10
        )

        def cmd(method, params=None):
            ws.send(json.dumps({"id": 1, "method": method, "params": params or {}}))
            while True:
                msg = json.loads(ws.recv())
                if msg.get("id") == 1:
                    return msg

        time.sleep(0.8)
        # Inject a bare 600px table (no .table-wrapper, overflow visible).
        cmd(
            "Runtime.evaluate",
            {
                "expression": (
                    "(() => {"
                    "const t=document.createElement('table');"
                    "t.style.tableLayout='fixed';t.style.width='600px';"
                    "const tr=document.createElement('tr');"
                    "for (const txt of ['File','Function or type','Your responsibility']){"
                    "const th=document.createElement('th');th.textContent=txt;tr.appendChild(th);}"
                    "t.appendChild(tr);document.querySelector('main').appendChild(t);"
                    "return true;})()"
                )
            },
        )
        time.sleep(0.3)
        expr = """(() => {
            const vw = innerWidth;
            const content = document.querySelector('.content');
            const cr = content.getBoundingClientRect();
            const bad = [];
            for (const el of document.querySelectorAll('main td, main th')) {
                const r = el.getBoundingClientRect();
                if (r.width <= 0) continue;
                if (r.left < cr.left - 2 || r.right > cr.right + 2) {
                    bad.push({tag: el.tagName, left: Math.round(r.left),
                              right: Math.round(r.right),
                              text: (el.textContent||'').slice(0,25)});
                }
            }
            return {contentRight: Math.round(cr.right), badCount: bad.length};
        })()"""
        r = cmd("Runtime.evaluate", {"expression": expr, "returnByValue": True})
        value = r["result"]["result"].get("value", {})
        ws.close()

        # The gate must detect the injected overflow (killing control).
        assert value.get("badCount", 0) > 0, (
            "render gate failed to catch a bare overflowing table"
        )
    finally:
        proc.terminate()
        proc.wait(timeout=5)
