# WARNING: Under review - generated by LLM.

from types import SimpleNamespace

import pytest

from .tiny_llm_base import (
    AgentError,
    FinalAction,
    ToolAction,
    build_system_prompt,
    parse_action,
)


def workspace(*, allow_writes=False, allowed_commands=()):
    """Day 2 prompt boundary without depending on the Day 3 workspace."""

    policy = SimpleNamespace(
        allow_writes=allow_writes,
        allowed_commands=allowed_commands,
    )
    tools = {"list_files", "read_file"}
    if allow_writes:
        tools.update({"write_file", "edit_file"})
    if allowed_commands:
        tools.add("run_command")
    return SimpleNamespace(policy=policy, available_tools=frozenset(tools))


def test_task_1_parse_final_action():
    assert parse_action('{"final":"done"}') == FinalAction("done")


@pytest.mark.parametrize(
    ("response", "expected"),
    [
        (
            '{"tool":"list_files"}',
            ToolAction("list_files", {}),
        ),
        (
            '{"tool":"list_files","path":"src"}',
            ToolAction("list_files", {"path": "src"}),
        ),
        (
            '{"tool":"read_file","path":"README.md"}',
            ToolAction("read_file", {"path": "README.md"}),
        ),
        (
            '{"tool":"write_file","path":"x","content":"y"}',
            ToolAction("write_file", {"path": "x", "content": "y"}),
        ),
        (
            '{"tool":"edit_file","path":"x","old":"a","new":"b"}',
            ToolAction(
                "edit_file",
                {"path": "x", "old": "a", "new": "b"},
            ),
        ),
        (
            '{"tool":"run_command","argv":["pdm","run","test"]}',
            ToolAction("run_command", {"argv": ["pdm", "run", "test"]}),
        ),
    ],
)
def test_task_1_parse_every_tool_schema(response, expected):
    assert parse_action(response) == expected


@pytest.mark.parametrize(
    "response",
    [
        "not json",
        '{"final":"done"} trailing text',
        '{"tool":"unknown"}',
        '{"tool":"read_file"}',
        '{"tool":"write_file","content":"y"}',
        '{"tool":"write_file","path":"x"}',
        '{"tool":"edit_file","old":"a","new":"b"}',
        '{"tool":"edit_file","path":"x","new":"b"}',
        '{"tool":"edit_file","path":"x","old":"a"}',
        '{"tool":"run_command"}',
        '{"tool":"read_file","path":7}',
        '{"final":"done","tool":"read_file"}',
        '{"final":"   "}',
        "[]",
        '{"tool":"list_files","path":".","extra":true}',
        '{"tool":"write_file","path":"x","content":7}',
        '{"tool":"edit_file","path":"x","old":[],"new":"b"}',
        '{"tool":"run_command","argv":[]}',
        '{"tool":"run_command","argv":["pdm",""]}',
    ],
)
def test_task_1_rejects_malformed_actions(response):
    with pytest.raises(AgentError):
        parse_action(response)


def test_task_2_prompt_contains_only_enabled_tools():
    read_only = workspace()
    prompt = build_system_prompt(read_only)
    assert '"tool":"read_file"' in prompt
    assert '"tool":"write_file"' not in prompt
    assert '"tool":"run_command"' not in prompt

    writable = workspace(allow_writes=True)
    prompt = build_system_prompt(writable)
    assert '"tool":"write_file"' in prompt
    assert '"tool":"edit_file"' in prompt


def test_task_2_prompt_contains_only_allowed_commands():
    enabled = workspace(allowed_commands=(("pdm", "run", "test"),))
    prompt = build_system_prompt(enabled)

    assert '["pdm", "run", "test"]' in prompt
    assert '"tool":"run_command"' in prompt


def test_task_2_rejects_a_known_but_disabled_tool():
    read_only = workspace()
    with pytest.raises(AgentError, match="not enabled"):
        parse_action(
            '{"tool":"write_file","path":"x","content":"y"}',
            read_only.available_tools,
        )
