# WARNING: Under review - generated by LLM.

"""Fail-closed starter/reference sync and anti-leakage guards for Week 4.

The starter (``tiny_llm.agent``) is the learner surface; the reference
(``tiny_llm_ref.agent``) is the solution.  These tests keep them from
silently drifting:

- every public class/method/function in the reference must exist in the
  starter (and vice versa) — a missing or extra member fails;
- the starter must not contain solution logic: public method bodies must be
  ``pass`` (or only TODO comments), so learners cannot be shown answers;
- every public member is mapped to a feature/day so the 7-day map stays
  enforceable.
"""

import ast
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

STARTER = ROOT / "src" / "tiny_llm" / "agent"
REFSOL = ROOT / "src" / "tiny_llm_ref" / "agent"

# Module -> (feature, day) map per docs/week4-day-split.md.
FEATURE_MAP = {
    "protocol": ("loop + tool protocol", "Day 1"),
    "loop": ("loop + tool protocol", "Day 1"),
    "generation": (
        "loop + tool protocol (minimal) / KV checkpoint (session)",
        "Day 1 / Day 4",
    ),
    "receipts": ("effect receipts", "Day 2"),
    "workspace": ("effect receipts (authorization)", "Day 2"),
    "session": ("session tree", "Day 3"),
    "checkpoint": ("KV checkpoint", "Day 4"),
    "branch": ("sequential rewind", "Day 4"),
    "compaction": ("receipt-backed compaction", "Day 5"),
    "control": ("steering/status", "Day 6"),
    "status": ("steering/status", "Day 6"),
    "reconcile": ("exactly-once reconcile", "Day 6"),
    "harness": ("equivalence harness", "Day 7"),
}

MODULES = sorted(FEATURE_MAP)


def _public_api(path: Path):
    """Return (classes -> public method names, top-level public functions)."""

    tree = ast.parse(path.read_text(encoding="utf-8"))
    classes: dict[str, set[str]] = {}
    funcs: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            methods = {
                item.name
                for item in node.body
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
                and not item.name.startswith("_")
            }
            classes[node.name] = methods
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and not node.name.startswith("_"):
            funcs.add(node.name)
    return classes, funcs


def _public_bodies(path: Path):
    """Return public (class, method) and function names with their bodies."""

    tree = ast.parse(path.read_text(encoding="utf-8"))
    bodies: list[tuple[str, ast.AST | None]] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            for item in node.body:
                if isinstance(
                    item, (ast.FunctionDef, ast.AsyncFunctionDef)
                ) and not item.name.startswith("_"):
                    bodies.append((f"{node.name}.{item.name}", item.body))
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and not node.name.startswith("_"):
            bodies.append((node.name, node.body))
    return bodies


def _is_solution_free(body) -> bool:
    """True when the body is a stub (pass / docstring-only / TODO only).

    A real implementation has at least one non-docstring statement (an
    assignment, call, return, raise, control flow, etc.).
    """

    if body in (None, []):
        return True
    real = [
        stmt
        for stmt in body
        if not isinstance(stmt, ast.Pass)
        and not (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
        )
        and not (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and stmt.value.value is Ellipsis
        )
    ]
    return not real


@pytest.mark.parametrize("module", MODULES)
def test_starter_api_matches_reference(module):
    starter = _public_api(STARTER / f"{module}.py")
    refsol = _public_api(REFSOL / f"{module}.py")

    assert starter == refsol, (
        f"starter/refsol API drift in {module}: "
        f"classes missing={sorted(set(refsol[0]) - set(starter[0]))} "
        f"extra={sorted(set(starter[0]) - set(refsol[0]))}"
    )


@pytest.mark.parametrize("module", MODULES)
def test_starter_has_no_solution_logic(module):
    for name, body in _public_bodies(STARTER / f"{module}.py"):
        assert _is_solution_free(body), (
            f"starter {module}.{name} contains solution logic; "
            "learner bodies must be pass/TODO-only"
        )


@pytest.mark.parametrize("module", MODULES)
def test_reference_implements_every_starter_member(module):
    """The reference must implement (non-pass) every starter-declared member."""

    starter = _public_bodies(STARTER / f"{module}.py")
    refsol = dict(_public_bodies(REFSOL / f"{module}.py"))
    for name, _body in starter:
        assert name in refsol, f"reference missing starter member {module}.{name}"
        assert not _is_solution_free(refsol[name]), (
            f"reference {module}.{name} is a stub; it must implement the feature"
        )


@pytest.mark.parametrize("module", MODULES)
def test_starter_members_are_mapped_to_features(module):
    feature, day = FEATURE_MAP[module]
    classes, funcs = _public_api(STARTER / f"{module}.py")
    assert classes or funcs, f"{module} has no public surface"
    # The map itself is the guard: module exists and is non-empty, and its
    # feature/day annotation is recorded for reviewers.
    assert feature and day


def test_starter_package_exports_match_reference():
    import tiny_llm.agent as starter
    import tiny_llm_ref.agent as refsol

    assert set(starter.__all__) == set(refsol.__all__), (
        f"starter/refsol __all__ drift: "
        f"missing={sorted(set(refsol.__all__) - set(starter.__all__))} "
        f"extra={sorted(set(starter.__all__) - set(refsol.__all__))}"
    )


def test_no_stale_old_course_modules_in_starter():
    """The old 7-day modules (context/evaluation/recovery) must be gone."""

    for stale in ("context.py", "evaluation.py", "recovery.py"):
        assert not (STARTER / stale).exists(), (
            f"stale old-course module {stale} must not exist in the starter"
        )
