# WARNING: Under review - generated by LLM.

from collections.abc import Callable, Iterable
from dataclasses import dataclass

from .generation import Message
from .protocol import AgentError
from .session import SessionLog


@dataclass(frozen=True)
class ContextPolicy:
    """Exact token budgets used to derive one model-visible request."""

    max_tokens: int = 32_768
    reserve_tokens: int = 8_192
    summary_max_tokens: int = 1_024
    max_tool_result_tokens: int = 4_096
    min_recent_turns: int = 2


@dataclass(frozen=True)
class WorkingSummary:
    """Stable semantic state retained when older complete turns are hidden."""

    goal: str
    constraints: tuple[str, ...]
    facts: tuple[str, ...]
    changed_files: tuple[str, ...]
    validation: tuple[str, ...]
    failed_approaches: tuple[str, ...]
    next_step: str

    def __post_init__(self) -> None:
        """Normalize and validate immutable summary fields."""

        pass


@dataclass(frozen=True)
class ContextWindow:
    """One immutable, exactly encoded request prepared for generation."""

    messages: tuple[Message, ...]
    token_ids: tuple[int, ...]
    visible_tool_result_bytes: int
    followed_compaction: bool
    compaction_event_id: str | None


class ContextLimitError(AgentError):
    """The required anchors and recent complete turns cannot fit safely."""


class ContextManager:
    """Build bounded semantic context without modifying canonical events."""

    def __init__(
        self,
        encode_messages: Callable[[list[Message]], Iterable[int]],
        policy: ContextPolicy | None = None,
    ):
        pass

    def prepare(
        self,
        session: SessionLog,
        system_prompt: str,
        summarize: Callable[[list[Message]], str] | None = None,
    ) -> ContextWindow:
        """Prepare one bounded request and durably record any new compaction."""

        pass


def compact_messages(messages: list[Message], max_chars: int) -> list[Message]:
    """Retain anchors, standalone messages, and complete recent tool turns."""

    pass


def append_tool_result(
    messages: list[Message], response: str, result: str
) -> list[Message]:
    """Record an action and its observation as one complete semantic turn."""

    pass
