# WARNING: Under review - generated by LLM.

"""Week 4, Day 1: the minimal generation surface (starter).

Day 1 needs only the message types, generation statistics, the initial
conversation messages, and a single-shot ``generate_response`` helper.

Implement the bodies yourself; the reference solution lives in
``tiny_llm_ref``.
"""

from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Any


Message = dict[str, str]
Generate = Callable[[list[Message]], str]


@dataclass(frozen=True)
class GenerationStats:
    """Token work performed by the most recent generation turn."""

    input_tokens: int = 0
    reused_tokens: int = 0
    rewound_tokens: int = 0
    prefilled_tokens: int = 0
    output_tokens: int = 0
    cold_start: bool = True
    latency_seconds: float | None = None


def initial_messages(task: str, system_prompt: str) -> list[Message]:
    """Create the durable beginning of an agent conversation."""

    # TODO: reject an empty task; return system + user messages.
    pass


def generate_response(
    model,
    tokenizer,
    messages: list[Message],
    cache_factory: Callable[[], Sequence[Any]],
    max_tokens: int,
    enable_thinking: bool = False,
) -> str:
    """Decode one action with the course model and a fresh cache."""

    # TODO: apply the chat template, decode up to max_tokens with the model,
    # stop at eos, release every cache, and return the decoded text.
    pass
