# WARNING: Under review - generated by LLM.

from collections.abc import Callable
from dataclasses import dataclass

from .control import CancellationToken
from .context import ContextManager
from .generation import Generate
from .generation import Message
from .protocol import AgentAction
from .session import SessionLog
from .workspace import Workspace


@dataclass(frozen=True)
class AgentLimits:
    """Week 4, Day 6: budgets that guarantee the loop eventually stops."""

    max_steps: int = 8
    max_context_chars: int = 48_000
    max_invalid_actions: int = 3
    max_identical_actions: int = 2

    def __post_init__(self) -> None:
        """Week 4, Day 6: reject budgets that could disable a stop condition."""

        pass


@dataclass(frozen=True)
class AgentEvent:
    """Week 4, Day 7: one auditable model/action/tool interaction."""

    step: int
    response: str
    action: AgentAction | None
    result: str | None


@dataclass(frozen=True)
class AgentRun:
    """One bounded run; ``completed`` means the model returned a valid final."""

    completed: bool
    reason: str
    final: str | None
    events: tuple[AgentEvent, ...]
    modified_files: tuple[str, ...]
    task_success: bool | None = None
    command_side_effects_untracked: bool = False
    uncertain_modified_files: tuple[str, ...] = ()
    retained_recovery_files: tuple[str, ...] = ()
    command_cleanup_incomplete: bool = False
    session_id: str | None = None


def run_agent(
    task: str | None,
    generate: Generate,
    workspace: Workspace,
    limits: AgentLimits | None = None,
    on_event: Callable[[AgentEvent], None] | None = None,
    *,
    session: SessionLog | None = None,
    context_manager: ContextManager | None = None,
    summarize: Callable[[list[Message]], str] | None = None,
    cancellation: CancellationToken | None = None,
) -> AgentRun:
    """Run a bounded loop, optionally recording its canonical durable events."""

    pass
