# WARNING: Under review - generated by LLM.

"""Week 4, Day 2 learner surface for effect receipts."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class EffectReceipt:
    """Immutable, content-addressed evidence for one dispatched tool action."""

    tool_call_id: str
    tool: str
    arguments: dict[str, Any]
    exit_state: str
    result: str
    changed_artifacts: tuple[str, ...]

    def __post_init__(self) -> None:
        # TODO: validate, detach, and freeze the canonical receipt fields.
        pass

    @property
    def receipt_id(self) -> str:
        """Return the SHA-256 content address of the canonical receipt payload."""

        pass

    def to_dict(self) -> dict[str, Any]:
        """Return a detached JSON-compatible durable representation."""

        pass

    @classmethod
    def from_dict(cls, value: Any) -> "EffectReceipt":
        """Reconstruct a receipt and reject malformed or tampered payloads."""

        pass


class ReceiptStore:
    """Append-only receipt store with verification on write and reload."""

    def __init__(self, path: Path | None = None):
        # TODO: initialize the optional durable path and verified indexes.
        pass

    def put(self, receipt: EffectReceipt) -> str:
        """Durably append one receipt, idempotently by content address."""

        pass

    def get(self, receipt_id: str) -> EffectReceipt | None:
        """Return a verified receipt, or None when the ID is absent."""

        pass

    def require(self, receipt_id: str) -> EffectReceipt:
        """Return a verified receipt or raise KeyError when it is absent."""

        pass

    def by_tool_call(self, tool_call_id: str) -> EffectReceipt | None:
        """Return the receipt for one tool-call ID, when recorded."""

        pass

    def __iter__(self):
        pass

    def __len__(self) -> int:
        pass

    def close(self) -> None:
        """Clear the in-memory index; durable receipt bytes remain on disk."""

        pass
