# WARNING: Under review - generated by LLM.

"""Exactly-once crash/effect reconciliation (Week 4, Day 6).

A process can crash after a modifying tool commits but before its observation
is appended.  On restart the harness reconciles the effect receipt, appends
exactly one observation, and resumes from the largest safe checkpoint — never
guessing, never blindly re-running the effect just to reconstruct model state.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from .checkpoint import CacheManifest
from .receipts import ReceiptStore

if TYPE_CHECKING:
    from .session import SessionLog


@dataclass(frozen=True)
class ReconciliationResult:
    """Outcome of reconciling one interrupted tool call."""

    tool_call_id: str
    status: str  # "observation_appended" | "no_receipt" | "already_closed"
    receipt_id: str | None = None
    content: str = ""

    def to_dict(self) -> dict[str, Any]:
        pass


def reconcile_effect(
    session: "SessionLog",
    store: ReceiptStore,
    tool_call_id: str,
) -> ReconciliationResult:
    """Close one interrupted effect exactly once."""

    pass


def reconcile_interrupted_effects(
    session: "SessionLog",
    store: ReceiptStore,
) -> tuple[ReconciliationResult, ...]:
    """Reconcile every unclosed tool call in one pass, in event order."""

    pass


@dataclass(frozen=True)
class SafeCheckpoint:
    """The largest manifest that may be resumed, or a cold fallback reason."""

    manifest: CacheManifest | None
    reason: str  # "resume" | "cold_no_checkpoint" | "cold_" + reason

    @property
    def can_resume(self) -> bool:
        pass


def largest_safe_checkpoint(
    manifests: tuple[CacheManifest, ...],
    *,
    model_hash: str,
    tokenizer_hash: str,
    layers: int,
    tool_catalog_hash: str,
    workspace_fingerprint: str,
) -> SafeCheckpoint:
    """Return the largest checkpoint that passes every fail-closed check."""

    pass
