# WARNING: Under review - generated by LLM.

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .generation import Message


@dataclass(frozen=True)
class SessionEvent:
    """One immutable event in an append-only agent transcript."""

    id: str
    timestamp: str
    type: str
    parent_id: str | None
    data: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        pass

    @classmethod
    def from_dict(cls, value: Any) -> "SessionEvent":
        pass


class SessionLog:
    """A memory-backed or fsync-backed append-only session event stream."""

    session_id: str
    workspace: Path
    model: str
    path: Path | None

    def __init__(
        self,
        session_id: str,
        workspace: Path,
        model: str,
        *,
        path: Path | None = None,
        events: tuple[SessionEvent, ...] = (),
    ):
        pass

    @property
    def events(self) -> tuple[SessionEvent, ...]:
        pass

    @property
    def instructions(self) -> tuple[dict[str, str], ...]:
        pass

    def append(
        self, event_type: str, *, parent_id: str | None = None, **data: Any
    ) -> SessionEvent:
        pass

    def messages(self, system_prompt: str) -> list[Message]:
        pass

    def recover_unmatched_tool_calls(self) -> tuple[SessionEvent, ...]:
        pass

    def recover_incomplete_turns(self) -> tuple[SessionEvent, ...]:
        pass


class SessionStore:
    """Create and resume workspace-bound local session transcripts."""

    workspace: Path
    model: str
    directory: Path

    def __init__(self, workspace: Path, model: str):
        pass

    def create(self, session_id: str | None = None) -> SessionLog:
        pass

    def load(self, session_id: str) -> SessionLog:
        pass

    def latest(self) -> SessionLog:
        pass


def memory_session(workspace: Path, model: str) -> SessionLog:
    """Create an event log that never writes a transcript to disk."""

    pass
