# WARNING: Under review - generated by LLM.

"""Public status cards derived from the durable event trace (Week 4, Day 6).

An operator may ask "what are you doing?" while an agent is running.  The
answer is a deterministic ``AgentStateCard`` derived only from the durable
event trace — never from hidden chain-of-thought.  A status question is
answered on the main run via sequential snapshot and rewind so the main trace,
cache, and workspace stay unchanged.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from .branch import BranchStats

if TYPE_CHECKING:
    from .generation import GenerationSession
    from .session import SessionLog


@dataclass(frozen=True)
class AgentStateCard:
    """Deterministic public state derived only from the durable event trace."""

    goal: str
    current_action: str
    approval_state: str
    last_evidence: str
    next_safe_step: str
    phase: str = "running"

    def to_dict(self) -> dict[str, Any]:
        pass

    def render(self) -> str:
        """Render the card as plain text for display or a status query."""

        pass


def build_state_card(
    session: "SessionLog",
    *,
    approval_state: str = "unknown",
    goal: str = "",
) -> AgentStateCard:
    """Derive a public state card from the durable event trace only."""

    pass


@dataclass(frozen=True)
class StatusQueryResult:
    """The answer plus honest accounting of the sequential side query."""

    response: str
    stats: BranchStats


class StatusQuery:
    """Answer one status question on the main run via snapshot + rewind."""

    def __init__(self, session: "GenerationSession"):
        pass

    def ask(self, card: AgentStateCard, generate: Any) -> StatusQueryResult:
        """Run one status paraphrase from the current prefix, then rewind."""

        pass

    def close(self) -> None:
        pass
