# WARNING: Under review - generated by LLM.

"""Week 4, Day 2: authorize effects and record durable receipts (starter).

This is the solution-free learner surface for the workspace: bounded tools
over one explicit root, protected/secret path rejection, symlink rejection,
inspection-before-overwrite with observed digests, atomic writes,
default-deny operator approvals, an exact command allowlist, and an
``execute`` dispatcher that records an immutable ``EffectReceipt`` per tool.

Implement the bodies yourself; the reference solution lives in
``tiny_llm_ref``.  This module deliberately has no mutation journal or undo
machinery — Day 6's exactly-once reconcile covers crash/effect recovery.
"""

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from .protocol import ToolAction
from .receipts import EffectReceipt, ReceiptStore


@dataclass(frozen=True)
class ToolPolicy:
    """Filesystem and command boundaries for one workspace."""

    root: Path
    allow_writes: bool = False
    allowed_commands: tuple[tuple[str, ...], ...] = ()
    max_file_bytes: int = 64 * 1024
    max_write_bytes: int = 64 * 1024
    max_list_entries: int = 200
    max_tool_output_chars: int = 16_000
    command_timeout_seconds: float = 30.0
    _root_identity: tuple[int, int] = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        """Normalize the root and reject invalid limits."""

        # TODO: resolve root, reject non-positive limits, too-broad roots,
        # and protected roots; record (st_dev, st_ino) identity.
        pass


@dataclass
class Workspace:
    """Bounded tools over one explicit workspace root."""

    policy: ToolPolicy
    confirm_tool: Callable[[ToolAction], bool] | None = None
    observed_files: dict[Path, bytes] = field(default_factory=dict, init=False)
    modified_files: set[Path] = field(default_factory=set, init=False)
    uncertain_modified_files: set[Path] = field(default_factory=set, init=False)
    receipt_store: ReceiptStore | None = field(default=None, init=False)
    last_receipt: EffectReceipt | None = field(default=None, init=False)

    def bind_receipt_store(self, store: ReceiptStore) -> None:
        """Attach a durable receipt store; every effect after this is recorded."""

        # TODO: bind before any effect; reject a second binding.
        pass

    def _record_receipt(
        self,
        action: ToolAction,
        result: str,
        changed_artifacts: tuple[str, ...],
        *,
        tool_call_id: str | None = None,
    ) -> None:
        """Persist one immutable effect receipt for a dispatched tool."""

        # TODO: derive exit_state (ok/error/uncertain), key the receipt to the
        # session tool_call id when given, and store it if bound.
        pass

    @property
    def available_tools(self) -> frozenset[str]:
        """Expose only tools enabled by operator policy."""

        # TODO: list_files/read_file always; write/edit only when
        # allow_writes; run_command only when commands are allowlisted.
        pass

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Reject escapes, protected files, and symlink traversal."""

        # TODO: resolve relative to root, reject escapes and protected
        # components, reject symlinked components, require existence.
        pass

    def _reject_protected(self, relative: Path) -> None:
        """Keep repository metadata and common secrets hidden."""

        # TODO: reject .git, dotfile secrets, and *.pem/*.key components.
        pass

    def list_files(self, raw: str = ".") -> str:
        """List one directory without following symlinks."""

        # TODO: bounded, sorted listing; skip symlinks and protected entries.
        pass

    def read_file(self, raw: str) -> str:
        """Read one bounded UTF-8 regular file."""

        # TODO: reject symlinks/special files, bound the size, record the
        # observed digest for stale-write detection.
        pass

    def write_file(self, raw: str, content: str) -> str:
        """Atomically create or replace an inspected file."""

        # TODO: validate (allow_writes, size, inspection), then commit
        # atomically; report "wrote <relative>".
        pass

    def _prepare_write(self, raw: str, content: str) -> "_PreparedWrite":
        """Validate a write completely before asking for operator approval."""

        # TODO: return a validated prepared write (see _PreparedWrite).
        pass

    def _commit_write(self, prepared: "_PreparedWrite") -> str:
        """Revalidate and commit one previously prepared write."""

        # TODO: revalidate digests, atomic-replace, track modified files.
        pass

    def edit_file(self, raw: str, old: str, new: str) -> str:
        """Make one exact, reviewable replacement in a read file."""

        # TODO: require prior read, require exactly one match, commit.
        pass

    def _prepare_edit(self, raw: str, old: str, new: str) -> "_PreparedWrite":
        """Validate and compute an edit without changing the workspace."""

        # TODO: return a validated prepared write for the edited content.
        pass

    def run_command(self, argv: list[str]) -> str:
        """Run only an operator-approved exact argv without a shell."""

        # TODO: reject when commands are disabled or argv is not allowlisted;
        # run with a bounded timeout and bounded output.
        pass

    def _prepare_command(self, argv: list[str]) -> tuple[str, ...]:
        """Validate one command against the exact operator allowlist."""

        # TODO: reject disabled/unallowlisted commands; return the tuple.
        pass

    def _run_command(self, argv: tuple[str, ...]) -> str:
        """Execute one command with a hard timeout, returning bounded output."""

        # TODO: Popen in the workspace root, drain output, enforce timeout,
        # kill the process group on timeout, track uncertain modifications.
        pass

    def _require_confirmation(self, action: ToolAction) -> None:
        """Default-deny one model-requested side effect."""

        # TODO: raise AgentError unless confirm_tool approves the action.
        pass

    def execute(self, action: ToolAction, *, tool_call_id: str | None = None) -> str:
        """Dispatch a validated action and return recoverable errors."""

        # TODO: dispatch each tool, wrap recoverable errors as
        # "error: ...", truncate output, record an effect receipt.
        pass

    def _truncate_result(self, result: str) -> str:
        """Bound a tool result to the configured output limit."""

        # TODO: truncate with a visible marker when over the limit.
        pass

    def _open_parent_directory(self, relative: Path) -> tuple[int, str]:
        """Open the parent directory of a relative path without following links."""

        # TODO: walk components with O_NOFOLLOW, reject protected/unsafe ones.
        pass

    def _read_regular_at(
        self, parent: int, name: str, *, tool: str
    ) -> tuple[bytes, object] | None:
        """Read one bounded regular file by parent dir fd, rejecting links."""

        # TODO: O_NOFOLLOW open, reject non-regular/multi-link files, bound size.
        pass

    def _revalidate_prepared_write(self, prepared: "_PreparedWrite") -> None:
        """Reject a write whose target changed after preparation."""

        # TODO: compare live digests/mode against the prepared expectation.
        pass

    def _read_bounded_file(self, path: Path, *, tool: str) -> bytes:
        """Read one bounded regular file, rejecting symlinks and special files."""

        # TODO: O_NOFOLLOW open, reject non-regular files, bound the size.
        pass

    @staticmethod
    def _digest(content: bytes) -> bytes:
        """Fingerprint observed bytes for stale-write detection."""

        # TODO: return sha256(content).digest().
        pass

    def _atomic_write(
        self,
        path: Path,
        content: bytes,
        *,
        expected_digest: bytes | None,
        expected_mode: int | None,
        after_mode: int,
        parent_identity: tuple[int, int],
    ) -> None:
        """Replace a file without exposing a partial write."""

        # TODO: write temp in the same directory, fsync, rename, fsync parent.
        pass


@dataclass(frozen=True)
class _PreparedWrite:
    """A validated write and the file state it is allowed to replace."""

    path: Path
    content: bytes
    expected_digest: bytes | None
    expected_mode: int | None
    after_mode: int
    parent_identity: tuple[int, int]
