# WARNING: Under review - generated by LLM.

"""Week 4, Day 2 learner surface for bounded workspace effects."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from .protocol import ToolAction
from .receipts import EffectReceipt, ReceiptStore


@dataclass(frozen=True)
class ToolPolicy:
    """Filesystem and command boundaries for one workspace."""

    root: Path
    allow_writes: bool = False
    allowed_commands: tuple[tuple[str, ...], ...] = ()
    max_file_bytes: int = 64 * 1024
    max_write_bytes: int = 64 * 1024
    max_list_entries: int = 200
    max_tool_output_chars: int = 16_000
    command_timeout_seconds: float = 30.0
    _root_identity: tuple[int, int] = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        # TODO: normalize the root and reject unsafe policies.
        pass


@dataclass
class Workspace:
    """Bounded tools over one explicit workspace root."""

    policy: ToolPolicy
    confirm_tool: Callable[[ToolAction], bool] | None = None
    observed_files: dict[Path, bytes] = field(default_factory=dict, init=False)
    modified_files: set[Path] = field(default_factory=set, init=False)
    uncertain_modified_files: set[Path] = field(default_factory=set, init=False)
    receipt_store: ReceiptStore | None = field(default=None, init=False)
    last_receipt: EffectReceipt | None = field(default=None, init=False)
    _receipt_ids: set[str] = field(default_factory=set, init=False, repr=False)

    def bind_receipt_store(self, store: ReceiptStore) -> None:
        """Bind a receipt store before the first dispatched tool action."""

        pass

    @property
    def available_tools(self) -> frozenset[str]:
        """Expose only tools enabled by operator policy."""

        pass

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Resolve one relative path without escapes or symlink traversal."""

        pass

    def list_files(self, raw: str = ".") -> str:
        """List one bounded directory without exposing protected entries."""

        pass

    def read_file(self, raw: str) -> str:
        """Read one bounded UTF-8 regular file and remember its digest."""

        pass

    def write_file(self, raw: str, content: str) -> str:
        """Atomically create or replace an inspected file."""

        pass

    def edit_file(self, raw: str, old: str, new: str) -> str:
        """Apply one exact replacement to a previously inspected file."""

        pass

    def run_command(self, argv: list[str]) -> str:
        """Run one exact allowlisted argument vector with a hard timeout."""

        pass

    def execute(self, action: ToolAction, *, tool_call_id: str | None = None) -> str:
        """Preflight, authorize, execute, and receipt one model tool action."""

        pass
