# Build and test the reference solution automatically on M1 runners.
# This helps prevent breakage of the dev setup.
name: macOS

on: push

jobs:
  test-refsol:
    name: Test reference solution
    runs-on: macos-15 # ARM64
    steps:
      - uses: actions/checkout@v5

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true

      - run: pdm install

      - run: pdm run check-installation

      - name: Try building extensions
        run: |
          pdm run build-ext
          pdm run build-ext-test

      - run: pdm run build-ext-ref

      - run: pdm run test-refsol
